### ISSUE TITLE
Cannot compile testers

### ISSUE THREAD

**Issue by MigMuc** [CNugteren/CLBlast#104]
I am trying to compile the testers as explained in the installation instructions but it fails with the following
error message:
~Downloads/CLBlast-master/test/correctness/tester.hpp:27:22: fatal error: clBLAS.h: Datei oder Verzeichnis nicht gefunden
   #include <clBLAS.h>
                      ^
compilation terminated.

I also set the variable for clBlas:
mycomputer-desktop:~/Downloads/CLBlast-master/build$ echo $CLBLAS_ROOT
/opt/clBLAS_dbg

I'm not really used to cmake environment.
Thanks.

**Comment by CNugteren** [comment]
Could you test with the `development` branch instead? I believe this issue was already discovered and solved: https://github.com/CNugteren/CLBlast/pull/101

**Comment by MigMuc** [comment]
Yes, compiling from development solved the issue.
