### ISSUE TITLE
Tests require OpenCL 2.0

### ISSUE THREAD

**Issue by shehzan10** [CNugteren/CLBlast#105]
On the readme it states that CLBlast requires OpenCL 1.1. However, the tests seem to require OpenCL 2.0 with the use of `clCreateCommandQueueWithProperties`. I believe this is the only function from OpenCL 2.0.
Would you consider replacing this function so that the tests too are OpenCL 1.x?

**Comment by shehzan10** [comment]
Looks like this is extending to `clblast_sample_sgemm_c` as well.

**Comment by CNugteren** [comment]
I don't see why that's the case. The only place where `clCreateCommandQueueWithProperties` is in the code is in `src/clpp11.hpp` and the snippet is as follows:
```
    #ifdef CL_VERSION_2_0
      size_t ocl_version = device.VersionNumber();
      if (ocl_version >= 200)
      {
        cl_queue_properties properties[] = {CL_QUEUE_PROPERTIES, CL_QUEUE_PROFILING_ENABLE, 0};
        *queue_ = clCreateCommandQueueWithProperties(context(), device(), properties, &status);
      }
      else
      {
        *queue_ = clCreateCommandQueue(context(), device(), CL_QUEUE_PROFILING_ENABLE, &status);
      }
    #else
      *queue_ = clCreateCommandQueue(context(), device(), CL_QUEUE_PROFILING_ENABLE, &status);
    #endif
```
I could remove the whole #ifdef/#else/#endif, but then OpenCL 2.0 compilers will emit a deprecation warning.

**Comment by shehzan10** [comment]
My bad. The OpenCL headers had 2.0 enabled, but the library was only 1.2. Hence I was getting undefined references.
