### ISSUE TITLE
Timeout when pulling clblast.json

### ISSUE THREAD

**Issue by akssri** [CNugteren/CLBlast#106]
The link to the tuned database times out in `database.py`
http://www.cedricnugteren.nl/tuning/clblast.json
(so does the website apparently).

Could you please host a copy on Github. Thanks!

**Comment by CNugteren** [comment]
Indeed, there seems to be something wrong with the host. Hopefully it will be up again soon.

Does Github have a specific place to store such files? I don't want to make it part of the repository because of its size.

**Comment by akssri** [comment]
I don't think so, but perhaps it would make sense to put it in its own repository ?

**Comment by CNugteren** [comment]
The website is working again. But your suggestion is valid: I'll create a separate repository for the database.

**Comment by CNugteren** [comment]
Your suggestion is implemented in the `development` branch. There is now a [CLBlast-database](https://github.com/CNugteren/CLBlast-database) repository in which history can be properly tracked. The database is automatically downloaded as was the case before.

**Comment by akssri** [comment]
Thank you!
