### ISSUE TITLE
tune CLBlast's GEMM primitives for rectangular matrix inputs

### ISSUE THREAD

**Issue by ovaler16** [CNugteren/CLBlast#109]
I am a bit but confuse how to specifically tune CLBlast primitives such as GEMM for specific rectangular matrix inputs.

It seems that the tuning function available in tuning directory only target 1024*1024.

Thanks,

Olivier

**Comment by CNugteren** [comment]
The command-line tuner programs (e.g. clblast_tuner_xgemm) take command-line arguments. You can pass for example -m 255 -n 2048 -k 16.

**Comment by ovaler16** [comment]
Thanks for very fast reply. Your answer really helps.

I also have another question connected to the first one. 

Once my kernel is tuned for 1 particular size (for example, m=255 n=2048 k=16), such as shown in your post, I can use your script to include my results in the database. However, this result is specific to one configuration. 

Is it possible to store several configurations in the database for different input size ?

Thanks a lot,

**Comment by CNugteren** [comment]
Good point. No, it's not possible unfortunately, there is only one configuration per device possible. I thought about doing this differently, but I'm not sure how.

There is another project that creates a model and tunes on the fly for specific sizes (https://github.com/ptillet/isaac). I am in contact with the author to see if something like that can be incorporated into CLBlast.


Do you have any thoughts?

**Comment by ovaler16** [comment]
Thanks again for your answer. In fact, i had in mind a system a little bit like that. I will take a look at their code.

Thanks for everything

**Comment by CNugteren** [comment]
I'm closing this issue now, since it is now possible to override parameters through the CLBlast API, see #130. It is not yet possible to store multiple binaries (for specific sizes) in the cache, that will be the next step.
