### ISSUE TITLE
Recommendations for LAPACK?

### ISSUE THREAD

**Issue by blueberry** [CNugteren/CLBlast#111]
Hi all,

I intend to add some LAPACK functionality to my Clojure library that is using CLBlast when GPU is needed. At the CPU side, it's no problem - I'll integrate ATLAS's LAPACK layer that I have already compiled long ago. Lots and lots of grunt work, but I know what needs to be done.
On the GPU side, I am not sure which path to choose: I know about ViennaCL and clmagma, but they seem quite beefy and overblown (although I haven't tried to actually work with them - so I might be wrong).

So, my question to you all, and especially @CNugteren would be:
1) Does CLBlast have (at least some) LAPACK integration support baked somewhere deep inside?
2) What do you use/recommend as LAPACK layer on top of CLBlast?
3) Is there any CLBlast-like clean, performant LAPACK library, at least in alpha stages of development?
4) Any future plans for LAPACK support/integration?

Please note that I need to use this from Java, so solutions that have a C interface are highly preferred to C++ only libraries (especially the ones that do heavy templating :)

**Comment by CNugteren** [comment]
I haven't looked at LAPACK yet, so I am unsure. Brief answers to your questions from my side:

1. There are no LAPACK algorithms implemented in CLBlast.
2. I don't have an answer, I haven't tested it myself. Perhaps MAGMA (OpenCL version)?
3. I am not aware of any new attempts to implement LAPACK for OpenCL. But then again I haven't searched for it.
4. Not at the moment. Let's first get CLBlast working perfectly :-)

**Comment by CNugteren** [comment]
I am closing this issue since it is now something related to CLBlast (at least not for now).
