### ISSUE TITLE
Segmentation fault when running samples

### ISSUE THREAD

**Issue by MigMuc** [CNugteren/CLBlast#113]
I get segmentation faults when running  samples from development branch.
`~/Downloads/CLBlast-development/build$ ./clblast_sample_dgemv_c                    
Speicherzugriffsfehler (Speicherabzug geschrieben)'

The same program runs fine from master branch. I think something went wrong when merging
gemm_direct into development. How can I trace back and find the error? Are there any debug flags I can set when compiling?

**Comment by CNugteren** [comment]
This example is the GEMV kernel, which has no relation to GEMM. Perhaps there are new tuning results for your device which are incorrect? Which device are you running on?

And can you run CMake with the VERBOSE option given? (e.g. `-DVERBOSE=ON`) and then re-compile the library? That way we'll get a little bit extra information about which actual kernel is run and when the segfault occurs.

**Comment by MigMuc** [comment]
The device is a Radeon R9 380 (Tonga). I compile with the AMDAPP-3.0 SDK.
Now I configured with `cmake --DVERBOSE=ON  -DSAMPLES=ON ..`. Then I start with
`./clblast_sample_sgemm` and I get no output except `Speicherzugriffsfehler (Speicherabzug geschrieben)`. 
One strange thing is that I get many warnings like `/Downloads/CLBlast-development/samples/cl.hpp:3101:39: warning: ‘cl_int clEnqueueBarrier(cl_command_queue)’ is deprecated (declared at /opt/AMDAPPSDK-3.0/include/CL/cl.h:1349) [-Wdeprecated-declarations]
             ::clEnqueueBarrier(object_),
                                       ^`.
[clinfo.txt](https://github.com/CNugteren/CLBlast/files/529994/clinfo.txt)

**Comment by MigMuc** [comment]
I have also attached the output of clinfo.

**Comment by MigMuc** [comment]
I think I have localised the error. Using valgrind I get the following:
`~/Downloads/CLBlast-development/build$ valgrind ./clblast_tuner_xgemv
==9512== Memcheck, a memory error detector
==9512== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==9512== Using Valgrind-3.10.1 and LibVEX; rerun with -h for copyright info
==9512== Command: ./clblast_tuner_xgemv
==9512== 
==9512== Invalid read of size 4
==9512==    at 0x578A45B: std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&) (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19)
==9512==    by 0x4E63B44: __static_initialization_and_destruction_0(int, int) [clone .constprop.167] (xaxpy.hpp:32)
==9512==    by 0x4010109: call_init.part.0 (dl-init.c:78)
==9512==    by 0x40101F2: call_init (dl-init.c:36)
==9512==    by 0x40101F2: _dl_init (dl-init.c:126)
==9512==    by 0x4001309: ??? (in /lib/x86_64-linux-gnu/ld-2.19.so)
==9512==  Address 0xfffffffffffffff8 is not stack'd, malloc'd or (recently) free'd
==9512== 
==9512== 
==9512== Process terminating with default action of signal 11 (SIGSEGV)
==9512==  Access not within mapped region at address 0xFFFFFFFFFFFFFFF8
==9512==    at 0x578A45B: std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&) (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19)
==9512==    by 0x4E63B44: __static_initialization_and_destruction_0(int, int) [clone .constprop.167] (xaxpy.hpp:32)
==9512==    by 0x4010109: call_init.part.0 (dl-init.c:78)
==9512==    by 0x40101F2: call_init (dl-init.c:36)
==9512==    by 0x40101F2: _dl_init (dl-init.c:126)
==9512==    by 0x4001309: ??? (in /lib/x86_64-linux-gnu/ld-2.19.so)
==9512==  If you believe this happened as a result of a stack
==9512==  overflow in your program's main thread (unlikely but
==9512==  possible), you can try to increase the size of the
==9512==  main thread stack using the --main-stacksize= flag.
==9512==  The main thread stack size used in this run was 8388608.
==9512== 
==9512== HEAP SUMMARY:
==9512==     in use at exit: 562 bytes in 13 blocks
==9512==   total heap usage: 13 allocs, 0 frees, 562 bytes allocated
==9512== 
==9512== LEAK SUMMARY:
==9512==    definitely lost: 0 bytes in 0 blocks
==9512==    indirectly lost: 0 bytes in 0 blocks
==9512==      possibly lost: 562 bytes in 13 blocks
==9512==    still reachable: 0 bytes in 0 blocks
==9512==         suppressed: 0 bytes in 0 blocks
==9512== Rerun with --leak-check=full to see details of leaked memory
==9512== 
==9512== For counts of detected and suppressed errors, rerun with: -v
==9512== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
Speicherzugriffsfehler (Speicherabzug geschrieben)`

It looks like something is going on in `(xaxpy.hpp:32)`. I think I cannot help further since I am used to program in Fortran not heavy C++.

**Comment by CNugteren** [comment]
Thanks for running it in valgrind. I managed to reproduce it, I'll fix it as soon as possible.

**Comment by MigMuc** [comment]
This has been fixed in the development branch.
