### ISSUE TITLE
clBLAS.h not being found from custom install directory for test/performance/client.cpp

### ISSUE THREAD

**Issue by shehzan10** [CNugteren/CLBlast#114]
I wanted to compile CLBlast with clients on.
I built clBLAS from source and installed it to `/path/to/clBLAS/build/package`. The tree structure for which is:
```
/workspace/clBLAS/build/package/
├── bin
│   ├── clBLAS-tune
│   ├── make-ktest
│   ├── t_blkmul
│   ├── t_dblock_kgen
│   ├── test-correctness
│   ├── test-functional
│   ├── test-medium
│   ├── test-short
│   ├── t_gens_cache
│   └── t_tilemul
├── include
│   ├── clAmdBlas.h
│   ├── clAmdBlas.version.h
│   ├── clBLAS-complex.h
│   ├── clBLAS.h
│   └── clBLAS.version.h
└── lib64
    ├── cmake
    │   └── clBLAS
    │       ├── clBLASConfig.cmake
    │       ├── clBLASConfigVersion.cmake
    │       ├── clBLASTargets.cmake
    │       └── clBLASTargets-release.cmake
    ├── libclBLAS.so -> libclBLAS.so.2
    ├── libclBLAS.so.2 -> libclBLAS.so.2.11.0
    ├── libclBLAS.so.2.11.0
    ├── libmkl_rt.so
    └── pkgconfig
        └── clBLAS.pc
```

In my cmake command, I use, `-DCLBLAS_ROOT=/workspace/clBLAS/build/package`, and I verified that the `CLBLAS_INCLUDE_DIRS` and `CLBLAS_LIBRARIES` variables are being populated correctly.

However, I still get a `clblas.h` not found error. Here is the full error:
```
[  1%] Building CXX object CMakeFiles/test_performance_common.dir/test/performance/client.cpp.o
/usr/bin/c++    -I/workspace/af_projects/CLBlast/include -I/workspace/af_projects/CLBlast/src -I/usr/local/cuda/include -I/workspace/af_projects/CLBlast  -O3 -std=c++11 -Wall -Wno-comment -Wno-return-type -Wno-switch -Wno-missing-noreturn -O3 -DNDEBUG    -DCLBLAST_REF_CLBLAS  -DCLBLAST_REF_CBLAS -o CMakeFiles/test_performance_common.dir/test/performance/client.cpp.o -c /workspace/af_projects/CLBlast/test/performance/client.cpp
In file included from /workspace/af_projects/CLBlast/test/performance/client.cpp:14:0:
/workspace/af_projects/CLBlast/test/performance/client.hpp:30:22: fatal error: clBLAS.h: No such file or directory
compilation terminated.
CMakeFiles/test_performance_common.dir/build.make:62: recipe for target 'CMakeFiles/test_performance_common.dir/test/performance/client.cpp.o' failed
```

As you can see, the clBLAS include directory is not listed in the compilation command.

**Comment by CNugteren** [comment]
Is this on the `development` branch? I believe this issue was already discovered and solved here: https://github.com/CNugteren/CLBlast/pull/101

**Comment by shehzan10** [comment]
Yes, I am using the development branch.

I did see the REF_INCLUDES in CMakeLists.txt and could not figure out why they were not showing up in the verbose command. Hence opened the issue.

```
build(development)$ cmake .. -LA | grep CLBLAS
CLBLAS_INCLUDE_DIRS:PATH=/workspace/clBLAS/build/package/include
CLBLAS_LIBRARIES:FILEPATH=/workspace/clBLAS/build/package/lib64/libclBLAS.so
```

**Comment by CNugteren** [comment]
OK, I think I found the reason. PR #101 fixed this for the correctness tests, but not for the performance tests. Can you let me know what happens if you change the relevant CMakeLists.txt part (around line 325) to:
```
    target_include_directories(test_performance_common PRIVATE
                               $<TARGET_PROPERTY:clblast,INTERFACE_INCLUDE_DIRECTORIES>
                               ${clblast_SOURCE_DIR} ${REF_INCLUDES})
```
(adding `${REF_INCLUDES}` like in the mentioned PR)

**Comment by shehzan10** [comment]
That fixed it thanks.

As a follow up, I've been trying to run the tests, and I end up with nothing but a database error. Any help?
```
build(development)$ CLBLAST_PLATFORM=1 ./clblast_test_xgemm

* Options given/available:
    -platform 1 [=default]
    -device 0 [=default]
    -full_test [false]
    -verbose [false]
    -clblas 0 [=default]
    -cblas 1 [=default]

* Running on OpenCL device 'GeForce GTX 780'.
* Starting tests for the 'SGEMM' routine. Legend:
   : -> Test produced correct results
   . -> Test returned the correct error code
   X -> Test produced incorrect results
   / -> Test returned an incorrect error code
   \ -> Test not executed: OpenCL-kernel compilation error
   o -> Test not executed: Unsupported precision
   - -> Test not completed: Reference CBLAS doesn't output error codes
* Testing 'regular behaviour' for '101 (row-major) 111 (regular) 111 (regular)':
terminate called after throwing an instance of 'std::runtime_error'
  what():  Database error, could not find a suitable entry
   Aborted (core dumped)

```

I've tried running `python ../scripts/database/database.py . ..` and compiling again, tried `cblas=1`, `clblas=1`, used intel and nvidia platforms, but always ended up with the same thing.

**Comment by CNugteren** [comment]
Hmm, that's not good. You seem quite unlucky with trying the library... By the way, the original problem is now fixed in the `development` branch.

Are you testing on Windows? I can't reproduce the issue on Linux or OS X myself, but I'll test on Windows as well (soon).

**Comment by shehzan10** [comment]
I'm testing on linux. I wanted to create a regular [testing framework on ArrayFire CI](http://ci.arrayfire.org/view/All/job/other/job/CLBlast-Linux/) for Linux, Windows and OSX.
For now, I'm trying to put linux together, OSX, Windows will follow.

**Comment by CNugteren** [comment]
Hmmm... is this in the very last version of the `development` branch? Perhaps it is related to #113?

**Comment by shehzan10** [comment]
Awesome it works now with 0f9311d.
However I did not see the `${REF_INCLUDES}` fix pushed to development.

**Comment by CNugteren** [comment]
Good to hear! The other fix was committed but not yet pushed. It is now in commit c0482ace6c78ddce0a2fcf37020302a41fbc5ee9.

**Comment by shehzan10** [comment]
Closing this issue as the relevant matters have been resolved.
Thanks for your help.
