### ISSUE TITLE
Add prefix to C enum typedefs and values

### ISSUE THREAD

**Issue by matze** [CNugteren/CLBlast#119]
Because C has no namespace concept, having public names like `StatusCode` or `kSuccess` will eventually lead to clashes with existing code. The most viable fix would be to prefix them the same way as the function calls.

**Comment by CNugteren** [comment]
Makes sense. I will implement this in the next few days.

**Comment by CNugteren** [comment]
All enums in the C API now have `CLBlast` as a prefix. For example `StatusCode` became `CLBlast StatusCode`, `kSuccess` became `CLBlastSuccess`, and so on. See the new `clblast_c.h` header in the development branch for more details.
