### ISSUE TITLE
static linking?

### ISSUE THREAD

**Issue by hughperkins** [CNugteren/CLBlast#120]
For tensorflow/bazel usage, I reckon static linking is somewhat more in line with how their system works.  So, for example for EasyCL, I'm building that as a static library, and I just removed clew altogether for now, since too lazy to figure out how to build it statically.

Thoughts on adding an option to CMakeLists.txt to build statically?

**Comment by CNugteren** [comment]
That's already possible in the `development` branch:

Building a static version of the library instead of shared one (.dylib/.so/.dll) can be done by disabling the `BUILD_SHARED_LIBS` option when calling CMake. For example:

    cmake -DBUILD_SHARED_LIBS=OFF ..

**Comment by hughperkins** [comment]
Cool :-)

**Comment by hughperkins** [comment]
(Note that CLBlast is in Tensorflow-cl now :-)  A bit in draft, not very tested, but seems like it could be working ok :-) 

- https://github.com/hughperkins/tensorflow-cl#whats-working
- https://github.com/hughperkins/tensorflow-cl#designarchitecture

**Comment by CNugteren** [comment]
Good to hear. Interesting approach you are taking to make Tensorflow compile with OpenCL.

By the way, CLBlast is gradually becoming more and more mature. Thanks to the guys at Arrayfire we now have [automated tests running](http://ci.arrayfire.org/view/Other/job/other/) on various devices (some still failing though).

**Comment by hughperkins** [comment]
> By the way, CLBlast is gradually becoming more and more mature. Thanks to the guys at Arrayfire we now have automated tests running on various devices (some still failing though).

Nice!

(By the way, nuance, I might finally link libcocl as so, to save rebuilding the entire world each time I change some slight detail.  If I do that, I'll probably switch CLBlast back to .so too, since seems only fair. Anywya, seems I have both options available to me :-) )
