### ISSUE TITLE
AMD not support cl_khr_fp16

### ISSUE THREAD

**Issue by zazd** [CNugteren/CLBlast#122]
I use fp16 from your project in AMD. But find it not support by AMD which can not support cl_khr_fp16.
Would you tell me which gpu of AMD can support cl_khr_fp16? If not, how can you do it in CLBlast to support half-vector

Thank your!

**Comment by CNugteren** [comment]
Half-precision is indeed only available for devices which support `cl_khr_fp16`. I don't know of an extensive list of such devices. For AMD I understood that near-future GPUs will have support for FP16, but I am not sure. Otherwise, without `cl_khr_fp16`, it is not possible within CLBlast.

**Comment by zazd** [comment]
Get it
thank you！
