### ISSUE TITLE
build warnings, in master branch

### ISSUE THREAD

**Issue by hughperkins** [CNugteren/CLBlast#123]
Very low priority obviously, and maybe already fixed in `dev` branch?  I get the following warnings on `master` branch:
```
/Users/travis/build/hughperkins/cuda-on-cl/src/CLBlast/src/routines/level3/xtrmm.cpp:114:16: warning: 27 enumeration values not handled in switch: 'kKernelLaunchError', 'kKernelRunError', 'kInvalidLocalMemUsage'... [-Wswitch]
```
(this is `master as of several weeks, might have been fixed since?)

Example build:

https://travis-ci.org/hughperkins/cuda-on-cl/builds/176383672#L1827

**Comment by CNugteren** [comment]
On line 118 in the `development` branch there is now a default for the switch statement:
https://github.com/CNugteren/CLBlast/blob/development/src/routines/level3/xtrmm.cpp

You can expect a new release of CLBlast in a week or 2.

**Comment by hughperkins** [comment]
Cool :-)
