### ISSUE TITLE
CL kernel compilation error trying to use double precision on Intel CPU

### ISSUE THREAD

**Issue by PlutoniumHeart** [CNugteren/CLBlast#129]
Hi,
I am trying to use CLBlast on Intel CPU, and met with the following error:
```
CLBlast: OpenCL error: clBuildProgram: -11
OpenCL compiler error/warning: Compilation started
39:79:27: error: use of type 'double' requires cl_khr_fp64 extension to be enabled
39:79:37: error: use of type 'double' requires cl_khr_fp64 extension to be enabled
39:97:11: error: use of type 'double' requires cl_khr_fp64 extension to be enabled
Compilation failed
```
It seems that CLBlast's kernels don't have "cl_khr_fp64" enabled, is there any reason for this? Or is this option planned in the future?

Thanks!

**Comment by CNugteren** [comment]
Not sure what's happening here. CLBlast indeed enables `cl_khr_fp64` if you are on OpenCL 1.1 and it is supported by your device. If it is not supported it should give back error code `-2044` and not `-11`. Are you perhaps on OpenCL 1.0?

Also, what are you running? The included test, an example program from the included `samples`, or your own code?

**Comment by PlutoniumHeart** [comment]
Yes, I noticed that. Intel CPU's OpenCL version is 1.2, but for some reason, it still needs this options enabled. I am running the same program on Nvidia GPUs which is also with CL version 1.2, and it works just fine. 

In the end, I have to change src/kernels/common.opencl file and increase the macros that checks version from 1.1 to 1.2 to make it run on Intel CPU. But I am sure if this is what the CL 1.2 standard required. 

I hope this information helps.

**Comment by CNugteren** [comment]
Then that's a bug in your OpenCL implementation I would say. According to the documentation for [OpenCL 1.1](https://www.khronos.org/registry/cl/sdk/1.1/docs/man/xhtml/cl_khr_fp64.html) it is required, but for [OpenCL 1.2](https://www.khronos.org/registry/cl/sdk/1.2/docs/man/xhtml/cl_khr_fp64.html) it is only still part of the specification for backwards compatibility.

Which OS are you on? And which OpenCL implementation (+ version) are you using?

**Comment by PlutoniumHeart** [comment]
I am running the program on Ubuntu 16.04 and Debian Testing (stretch), both systems have the same behavior. 

I do have to enable the fp64 extension in my own kernel as well, in order to use it in both CPU and GPU.
But the clblast lib's kernels work fine on the GPU by default, but have this problem on CPU, maybe this is some implementation difference in the OpenCL's driver?

I am not entirely sure what you meant by OpenCL implementation you are talking about, but the CPU OpenCL driver is "intel-opencl-icd-5.0.0.57", and the GPU driver is the one comes with CUDA-8.0

Thanks!

**Comment by CNugteren** [comment]
I've also just tested on a Debian system with an Intel CPU and the Intel OpenCL implementation and it indeed requires the extension to be enabled. However, enabling it always should give warnings with other OpenCL 1.2 or higher compilers, as is also [described here](https://williamjshipman.wordpress.com/2014/06/24/correctly-enabling-cl_khr_fp64-in-both-opencl-1-1-and-1-2/). Perhaps I can find a way to automatically ignore those warnings.

**Comment by CNugteren** [comment]
I think it's OK to emit a warning, because [CLBlast only outputs the compiler message if there are also errors](https://github.com/CNugteren/CLBlast/blob/master/src/routine.cpp#L121). Also, in another library, ArrayFire, it's [always enabled independent of the OpenCL version](https://github.com/arrayfire/arrayfire/blob/devel/src/backend/opencl/program.cpp#L27).

Thus, `cl_khr_fp64` is now always enabled if double-precision is required. I'm closing this issue now, the 'fix' is in the `development` branch and will automatically be included in the next release of the library.
