### ISSUE TITLE
Passing tuning parameters manually to routines

### ISSUE THREAD

**Issue by ari-wwu** [CNugteren/CLBlast#130]
Hello,

is there there a possibility to pass tuning parameter values manually to the routines, e.g. gemm?
For example, in case of the gemm routine, I will determine values for its tuning parameters (MWG, NWG, ...) that are also optimized for the input matrices' sizes (M,N and K). Assumed I have determined such optimized tuning parater values for different matrix sizes, can I pass these to the CLBlast library?

Many thanks in advance.

**Comment by blueberry** [comment]
Just to add that I would Also like if such thing is available through API, but I guess that the compiler would not be able to do some optimizations?

**Comment by CNugteren** [comment]
Indeed, this is something that should be added to CLBlast. I will continue with my current efforts (implementing triangular solvers) and afterwards work on this request. Note that some ground-work is already in place, it is possible to [override the default database](https://github.com/CNugteren/CLBlast/pull/84/commits/e4e1f05079273f60f4f15280b3f103810c7eb31f).

I see two options to implement this:
1. A C++ API to provide database overrides, e.g. `clblast::OverrideParameters("gemm", {{"MWG", 8}, {"NWG":32}}`. This allows fine-grained control. This can be useful if you want to supply fine-tuned parameters, e.g. in one program for a specific matrix-size and then afterwards supply other parameters for another matrix-size. This would require either storing multiple compiled OpenCL kernels in the internal cache (one per parameter setting) or possibly just invalidating the cache if the parameters change.
2.An environmental variable (e.g. `CLBLAST_DATABASE_OVERRIDE`) pointing to a file on disk with tuning parameter overrides. This way the user has less control, but it might have the advantage that such a file is easy to edit and exchange (e.g. JSON) and could be automatically generated by the tuners.

My current preference would be for point 1, but I welcome any opinions or suggestions for alternatives.

**Comment by CNugteren** [comment]
Or perhaps a more natural (and easier to implement?) third option is an optional argument to each CLBlast routine which allows you to specify one or more parameter overrides. This way there is no additional global state required (apart from the existing cache) and it is clear from the user's perspective when parameters are overridden or defaulted.

By the way, are you using the C++ API or do you also need this feature in the C version?

**Comment by blueberry** [comment]
I am using CLBlast from Clojure and JVM, so C Is the only option for me.

**Comment by CNugteren** [comment]
@ari-wwu 
I've started working on this. Currently I have the following interface defined:
```
StatusCode OverrideParameters(const cl_device_id device, const std::string &kernel_name,
                              const Precision precision,
                              const std::unordered_map<std::string,size_t> &parameters)
```

Usage would be for example as follows:
```
    auto status = clblast::OverrideParameters(
      device, "Gemm",
      clblast::Precision::kSingle,
      { {"KWG",32}, {"KWI",2}, {"MDIMA",8}, {"MDIMC",8}, {"MWG",32}, {"NDIMB",8}, {"NDIMC",8}, {"NWG",64}, {"SA",0}, {"SB",0}, {"STRM",0}, {"STRN",0}, {"VWM",2}, {"VWN",2} }
    );
```

I'll keep you updated. Any feedback on the API is welcome. And I'll work on a C version after the C++ version is working.

**Comment by ari-wwu** [comment]
Oh great, thanks :-) What also would be great is to add the input size as attribute to the data base, e.g. sth like:
  StatusCode OverrideParameters( const cl_device_id device, 
                                                           const input_size_t& input_size,
                                                           const std::string &kernel_name,
                                                           const Precision precision,
                                                           const std::unordered_map<std::string,size_t> &parameters
                                                        )

where input_size_t is a type for representing a routine's input parameters' sizes in each dimension -- in case of GEMM: ( (M,K), (K,N) )

**Comment by CNugteren** [comment]
If I understand you correctly you would want to use `input_size` to specify that the given parameters should only be applied for a specific size? That's actually a lot more involved than the current version... it would require some re-writing of the whole organisation within CLBlast, because it would mean that there can be multiple kernels available for a single device-routine combination. Maybe this is something for later to add to CLBlast? Or is this crucial for you? What would be your use-case?

I was actually just going to report that I finished the implementation. Still need some testing and documentation, but soon it will be merged into the `development` branch. The C++ interface is still as above - and the example would still work. The C interface is (of course) a lot more unsafe and tricky to use:
```
CLBlastStatusCode OverrideParameters(const cl_device_id device, const char* kernel_name,
                                     const CLBlastPrecision precision, const size_t num_parameters,
                                     const char** parameters_names, const size_t* parameters_values);
```
Here is an example of how to use it:
```
  char* kernel_name = "Xgemm";
  const size_t num_parameters = 14;
  size_t parameters_values[14];
  char* parameters_names[14];
  parameters_values[0] = 32; parameters_names[0]  = "KWG";
  parameters_values[1] =  2; parameters_names[1]  = "KWI";
  parameters_values[2] =  4; parameters_names[2]  = "MDIMA";
  parameters_values[3] =  4; parameters_names[3]  = "MDIMC";
  parameters_values[4] = 32; parameters_names[4]  = "MWG";
  parameters_values[5] =  4; parameters_names[5]  = "NDIMB";
  parameters_values[6] =  4; parameters_names[6]  = "NDIMC";
  parameters_values[7] = 32; parameters_names[7]  = "NWG";
  parameters_values[8] =  0; parameters_names[8]  = "SA";
  parameters_values[9] =  0; parameters_names[9]  = "SB";
  parameters_values[10] = 0; parameters_names[10] = "STRM";
  parameters_values[11] = 0; parameters_names[11] = "STRN";
  parameters_values[12] = 1; parameters_names[12] = "VWM";
  parameters_values[13] = 1; parameters_names[13] = "VWN";
  CLBlastStatusCode status2 = OverrideParameters(device, kernel_name, CLBlastPrecisionSingle, num_parameters,
                                                  parameters_names, parameters_values);
```
After I wrote this example I felt sorry for people not using the C++ interface ;-)

**Comment by ari-wwu** [comment]
Yes, you understood correctly. The suggested extension is not crucial for now but would be very nice to have. For example, in context of deep learning (e.g., the Caffe Framework), BLAST routines usually are called multiple times on the same input sizes. Having optimized kernels for that input sizes would surely contribute to a better performance of a  deep learning application.

**Comment by CNugteren** [comment]
The current implementation is now merged in to the `development` branch. Documentation is available [here](https://github.com/CNugteren/CLBlast/blob/development/doc/clblast.md#overrideparameters-override-tuning-parameters-auxiliary-function). Could you test the function?

About your other request of having optimized kernels for different input sizes, that's surely something on my to-do list. But it's quite big change from the way things are currently in CLBlast, so I am afraid it will take a couple of months before I will have any news on that. Some other things need to be fixed first. I hope you understand.

**Comment by CNugteren** [comment]
In the meantime everything has been merged into master and released, so I'm closing this issue.
