### ISSUE TITLE
Run CLBlast on Android

### ISSUE THREAD

**Issue by kindloaf** [CNugteren/CLBlast#146]
Hi,
I would like to run CLBlast on Android (arm64-v8a). How should I compile the library to get binaries for the Android system? Do I need to tweak the Makefile?

**Comment by CNugteren** [comment]
I don't have an Android development machine, so I'm not sure. However, Android Studio has [support for C++ and CMake](https://developer.android.com/studio/projects/add-native-code.html), so I don't think you should have to write a Makefile. CLBlast's build system is CMake.

Or do you perhaps have any specific issues you encounter?

**Comment by kindloaf** [comment]
@CNugteren My specific issue is that, by using the provided compilation commands (cmake; make ...) I got binaries that runs on x86-64. My question is, how can I make binaries that run on android (arm64-v8a)? I assume I need to specify compilers for Android in the makefile, or something similar.

**Comment by CNugteren** [comment]
@kindloaf As I said, I don't have an Android system to test on. Yes, you should cross-compile. So you should follow the instructions given by Android Studio or the Android NDK. See my earlier link for something I quickly found on the web, but perhaps there are better resources. If you encounter any specific issue related to CLBlast, let me know.

**Comment by kindloaf** [comment]
Thanks @CNugteren ! The info was very helpful.

**Comment by psyhtest** [comment]
The easiest way to build CLBlast for Android is via [CK](http://cknowledge.org) e.g.:
```
$ ck pull repo:ck-math
$ ck install package:lib-clblast-master-universal --target_os=android21-arm64
```

**Comment by kindloaf** [comment]
@psyhtest Thanks for the info!

**Comment by janboeye** [comment]
@CNugteren @psyhtest Android does not support c++ exception, and how can I build it?

Thanks

**Comment by psyhtest** [comment]
@janboeye As I said above, you can build CLBlast via [Collective Knowledge](https://github.com/ctuning/ck). You will of course need an [Android SDK](https://developer.android.com/studio/index.html) and CK installed. In many cases, it should be sufficient to run:
```
$ sudo pip install ck
$ ck pull repo:ck-math
$ ck install package:lib-clblast-master-universal --target_os=android21-arm64
```
Please let me know if you have any problems.

**Comment by janboeye** [comment]
@psyhtest I resolved it.

Thanks a lot!
