### ISSUE TITLE
http://www.cedricnugteren.nl/tuning/clblast.json 404

### ISSUE THREAD

**Issue by iamqk** [CNugteren/CLBlast#154]
when use tuner
on step:
python ../scripts/database/database.py . ..

get an error on http

**Comment by CNugteren** [comment]
Is that the URL in the title of the issue? If so then you are on a very old version of CLBlast. I would suggest to update to the latest version of the master branch. Then you'll see this URL instead:
```
DATABASE_SERVER_URL = "https://raw.githubusercontent.com/CNugteren/CLBlast-database/master/database.json"
```

**Comment by iamqk** [comment]
thx, i compile clblast code that contained in cud-on-cl project
