### ISSUE TITLE
Benchmarking CLBlast routines that execute multiple kernels

### ISSUE THREAD

**Issue by RichardSchulze** [CNugteren/CLBlast#159]
I am trying to benachmark the CLBlast routines asum, dot, gemv and scal. I am doing this by passing an event to the CLBlast calls and reading the profilling information from that event:
```
cl::Event event;
clblast::Asum<float>(
            N,
            result, 0,
            vector, 0, 1,
            &command_queue(), &event());
event.getProfilingInfo(CL_PROFILING_COMMAND_START, &start_time);
event.getProfilingInfo(CL_PROFILING_COMMAND_END, &end_time);
```
For gemv this works just fine, but I have problems with benachmarking asum, dot and scal. I noticed that these routines execute multiple kernels and that the event will only be passed to the last kernel. I therefore only measure the execution time of the last kernel and not the overall routine.

Is there a way of measuring the runtime of all kernels involved in a CLBlast routine?

**Comment by CNugteren** [comment]
GEMV and SCAL are single-kernel routines, that should not give a problem. For ASUM and DOT there are 2 kernels indeed. For the first kernel a new event is created, which is then passed on to the second kernel as a dependency (i.e. please finish the first kernel first). The second kernel is recorded using the original event, but perhaps the dependency on the first kernel makes the timing include it as well? I am not sure about this, I have never tried myself.

If you have any suggestion how this can be done better, let me know. But as far as I know this is also what has been done in AMD's clBLAS library.

You can of course always time the code by waiting for the event afterwards and using normal CPU timers to time the whole thing. That is how the CLBlast benchmark clients measure execution time.

**Comment by RichardSchulze** [comment]
Thanks for getting back to me.
Unfortunately the event can only be used to measure the runtime of the second kernel. The OpenCL specification states that the `CL_PROFILING_COMMAND_
START` value is:

> A 64-bit value that describes the
current device time counter in
nanoseconds when the command
identified by event starts execution
on the device

That matches with what I experienced in my tests.

I think measuring the runtime with CPU timers is a problem in my case, because I am also measuring fairly small input sizes. The overhead of the library call might distort the results and make for an unfair comparison.

Ideally I would like to submit an extra event to the library call that will be submitted to the first kernel. I could then add the two runtimes.

**Comment by CNugteren** [comment]
> The overhead of the library call might distort the results and make for an unfair comparison.

But this is part of the actual time spent in the library of course... Mostly minor things, but compilation (first time only) can be a major contributor.

> Ideally I would like to submit an extra event to the library call that will be submitted to the first kernel. I could then add the two runtimes.

That would require a change to the API, so I would prefer another solution. Do you know how the users of clBLAS profile routines with multiple kernels?

**Comment by RichardSchulze** [comment]
> Do you know how the users of clBLAS profile routines with multiple kernels?

No, but after a quick Google search it seems like clBLAS supplies executables for profiling. I couldn't find information about profiling routines with multiple kernels.

> That would require a change to the API, so I would prefer another solution.

As a temporary solution I altered the CLBlast library myself in a way that preserved the signature of the API. For `Asum` for example I made the following changes:

**include/clblast.h**:
```
template <typename T>
StatusCode Asum(...,
                cl_event* event = nullptr,
                cl_event* event2 = nullptr); // additional event parameter
```

**src/clblast.cpp**:
```
// Absolute sum of values in a vector: SASUM/DASUM/ScASUM/DzASUM/HASUM
template <typename T>
StatusCode Asum(..., cl_event* event, cl_event* event2) {

  // ...

    auto routine = Xasum<T>(queue_cpp, event, "ASUM", event2);

  // ...

}
template StatusCode PUBLIC_API Asum<float>(..., cl_event*, cl_event*);
template StatusCode PUBLIC_API Asum<double>(..., cl_event*, cl_event*);
template StatusCode PUBLIC_API Asum<float2>(..., cl_event*, cl_event*);
template StatusCode PUBLIC_API Asum<double2>(..., cl_event*, cl_event*);
template StatusCode PUBLIC_API Asum<half>(..., cl_event*, cl_event*);
```

**src/routines/level1/xasum.hpp**:
```
// Constructor
Xasum(Queue &queue, EventPointer event,
      const std::string &name = "ASUM",
      EventPointer event2 = NULL); // additional event parameter

// ...

private:
    EventPointer event2_; // member to save additional event parameter
```

**src/routines/level1/xasum.cpp**:
```
// Constructor: forwards to base class constructor
template <typename T>
Xasum<T>::Xasum(..., EventPointer event2):
    ..., event2_(event2) {
}

// ...

// The main routine
template <typename T>
void Xasum<T>::DoAsum(...) {

  // ...

  // Launches the main kernel
  auto global1 = std::vector<size_t>{db_["WGS1"]*temp_size};
  auto local1 = std::vector<size_t>{db_["WGS1"]};
  if (event2_ != NULL) { // second event was submitted
    RunKernel(kernel1, queue_, device_, global1, local1, event2_);
    eventWaitList.emplace_back(*event2_);
  } else { // no second event, use old way
    auto kernelEvent = Event();
    RunKernel(kernel1, queue_, device_, global1, local1, kernelEvent.pointer());
    eventWaitList.push_back(kernelEvent);
  }

  // ...

}
```

This works for my purposes. Since it doesn't change the API, maybe you can incorporate it into your library. Anyway, thank you for your help!

**Comment by CNugteren** [comment]
> No, but after a quick Google search it seems like clBLAS supplies executables for profiling. I couldn't find information about profiling routines with multiple kernels.

Yes, indeed I think clBLAS has this same 'issue'. CLBlast provides executable for profiling as well by the way (set `TESTS=ON` when running CMake).

> As a temporary solution I altered the CLBlast library myself in a way that preserved the signature of the API.

OK, indeed it preserves the old API as well. But for the C API this wouldn't hold actually - it doesn't support default arguments. So, yes, implementing it wouldn't be difficult, but I'm still not convinced it is necessary. What is your use-case really? If you are doing some specific research into the kernels themselves, then it is easy to modify the code. If you are just measuring the CLBlast performance, then you should measure the whole thing including the overhead (e.g. use the provided client or use CPU timers).

**Comment by RichardSchulze** [comment]
You are correct, it is not really necessary. As I wrote in my last post, altering the library myself works in my case. I was just wondering if you were planning to implement such a feature.

I'll close the issue, thanks for your time.

**Comment by CNugteren** [comment]
Of course it is useful for me to get feedback from the users and their use-cases, so thanks for pointing this out! If there will be any other API change in the future I'll reconsider adding this.
