### ISSUE TITLE
What is OPENCL_COMPILER_DIR in the cmake config?

### ISSUE THREAD

**Issue by ksze** [CNugteren/CLBlast#162]
When I run `ccmake`, I see that there is a field called `OPENCL_COMPILER_DIR`.

cmake seems unable to autodetect a value for it: cmake just leaves it at "OPENCL COMPILER PATH" as I press 'c' to configure.

What does that field actually affect? I seem still able to build CLBlast and run all the applicable tuners via `make alltuners`.

Hardware: Intel Core i5-4590T CPU (Haswell), with integrated Intel HD Graphics 4600
OS: Ubuntu 14.04.5 64-bit server edition.
OpenCL related packages installed:
- beignet-dev version 1.1.1-2ubuntu7
- beignet-opencl-icd:amd64 version 1.1.1-2ubuntu7
- ocl-icd-libopencl1:amd64 version 2.2.8-1
- ocl-icd-opencl-dev:amd64 version 2.2.8-1

**Comment by CNugteren** [comment]
I don't see this field myself, and I can't find any occurrence to it when I search the code. So not sure if this is related to CLBlast and also not sure if it is an issue at all.

**Comment by ksze** [comment]
Sorry for the noise. That field is actually in clBLAS's cmake config, not CLBlast's. I got a bit confused as I was building both clBLAS and CLBlast on the same day.
