### ISSUE TITLE
GEMM: matrix size overflow

### ISSUE THREAD

**Issue by mcian** [CNugteren/CLBlast#163]
Hi,
there is an overflow issue when the size of the matrix is bigger than (2^32 - 1) (for example m = n = k = 2048).  
In this case  `DoGemm` will select `GemmDirect` because  `do_gemm_direct`  will be 1.   
(see https://github.com/CNugteren/CLBlast/blob/master/src/routines/level3/xgemm.cpp#L105 )

**Comment by CNugteren** [comment]
Good catch, thanks for reporting! But if I am right this is only an issue on 32-bit systems, since `size_t` is used. I'll change this computation (and search for other similar cases?) such that it uses `unsigned long` and should work fine again.

**Comment by mcian** [comment]
Yes, you right this is an issue  only on 32-bit systems. I forgot to mention it

**Comment by CNugteren** [comment]
This is fixed now in `master`, thanks for reporting!
