### ISSUE TITLE
Why does GEMM/GEMMBatched require a_ld >= m (or k?)_

### ISSUE THREAD

**Issue by Ulfgard** [CNugteren/CLBlast#168]
Hi,

I know that in many cases,using GEMM with a too small a_ld is an error. However, is there a technical requirement for this? I am currently using GemmBatched to implement a 2D-convolution (see previous issue that you fixed) and i am playing around with different ways to implement it. One way is taking a row fn an image with values (x1,x2,x3,...,xn) and reshape it to
(x1,x2,x3;
x2,x3,x4;
x3, x4, x5
...
xn-2, xn-1, xn)
where the number of columns equals the number of channels * width of the filter. in this case, a_ld is the same as number of channels (in the example above, 1 channel and filter width is 3). And we obtain one such matrix per row of the image. A convolution is then turned into a simple set of matrix-matrix multiplications. This should be very cache efficient and should lead to good performance, especially on large images. 

Is it possible to relax the requirement to make the above possible?

**Comment by Ulfgard** [comment]
Maybe we can create an "expert" kernel? i.e. a kernel where all c-arrays are replaced by buffers?

This could a) allow running a kernel to generate the indices instead of a memory transfer and
b) when a kernel is to be run repeatedly with different data but same indices, indices could be reused.

Here we could than say: expert kernels can do more but are less safe so an check on a_ld etc might be less strict.

**Comment by CNugteren** [comment]
> Is it possible to relax the requirement to make the above possible?

Without looking at the code, I do believe it should be possible, since matrix A (and also B of course) are read-only, so having an `ld` value smaller than `m` or `k` should be possible. However, it is implemented as a requirement in other BLAS libraries, such as clBLAS and MKL (see e.g. https://software.intel.com/en-us/mkl-developer-reference-c-cblas-gemm). To play around with it, you could comment out [the check on the validity of the A matrix](https://github.com/CNugteren/CLBlast/blob/master/src/routines/level3/xgemm.cpp#L100).

> Maybe we can create an "expert" kernel? i.e. a kernel where all c-arrays are replaced by buffers?

Are you talking about the batched interface now? Perhaps you mean the same as what blueberry suggests [in another issue](https://github.com/CNugteren/CLBlast/issues/95#issuecomment-301723360)? If so, I could prioritise that perhaps.

Also relevant perhaps is that I'm currently working on an implementation of the im2col algorithm (in a separate branch currently), used as a pre-processing step to express convolution in neural networks as a GEMM operation (similar to what you're trying to achieve in one go I guess).

**Comment by Ulfgard** [comment]
I will try your first suggestion later today. I know that this is a standard requirement for GEMM and i feel that it has more use there than in the batched case (overlapping matrices are already allowed after all). I also agree that it is less error prone for new users to have this check. And it is a quite esoteric use-case. I would therefore opt to only allow it in the Batched versions.

I think the strided offsets would not work for me. I would rather have a version which takes a cl_mem object.

Regarding im2col: 
I think this is a red hering. There are only two operations where im2col is needed: to either multiply a matrix from the left (convolution) or to the right (derivative of the convolution wrt its parameters). For the convolution it is known that im2col has huge disadvantages which makes it unfavourable compared to specialised kernels. First of all, by blowing up the matrix in memory, we waste a lot of the bandwith by saving and loading the same element from different memory locations. In comparison, GemmBatched can make much use of the cards L1 and L2 caches as memory can be reused repeatedly which saves Memory Bandwith. In the example above, loading a whole block can be coalesced by the card into much less memory accesses.

In my benchmarks i can see that as my GemmBatched based convolution gives in certain regimes(many, large images) far better performance than GEMM on large matrices (on my R9 390 GEMM performance peaks at a size m=n=k=1024 at 1.1Tflops and then drops to ~260Gflops)

The other operation requires special kernels as the filter matrix is typically small, so max(m,n)<<k and m*n<<number of parallel processors. I am not sure whether clBLAS can handle this case.

**Comment by CNugteren** [comment]
OK, thanks for the valuable feedback! I'll act on that separately. For now, I've relaxed the requirements on a_ld and b_ld for the batched GEMM routine as you requested. Could you verify whether the branch `relax_gemmbatched_ld_requirements` contains the changes as you expected?

**Comment by CNugteren** [comment]
@Ulfgard In the meantime I've merged the changes into master. Could you check if this 'resolves' the issue?

**Comment by Ulfgard** [comment]
i am on vacation until Tuesday. You are on top of my todo-list!

**Comment by Ulfgard** [comment]
works. Performance is not as good as thought, but at least it does not crash anymore!

Closing this!

**Comment by CNugteren** [comment]
> Performance is not as good as thought

Could you let me know what values of m, n, k you use? I know the batched version uses the same parameters as the non-batched version and is therefore sub-optimal for most use-cases. It's on my to-do list, but at the same time it is part of a bigger project to improve performance across many possible arguments. Work is already ongoing thanks to external contributors, see also https://github.com/CNugteren/CLBlast/issues/169#issuecomment-313055136

**Comment by Ulfgard** [comment]
Hi,

Again sorry for the delay. I have several settings i am interested in based on my convolution implementation(s).


The first one is designed for the case where I apply the same set of M filters to N images independently. K is typically small in this case (width of the filters x number of input channels).

Important settings are
M in {32,64}
N in {32,64,128} (where 128 might be stretching it ressource wise)
K in {3*3, 3*64}
and the kernel is run for image_width * image_height positions (typically around 30*30 positions). This kernel is then run for each row of the kernel.

The other important case is when applying the filters on a single (possibly large) image. Here, 
M is as before the number of filters, K is the number of pixels x input channels and N is the image_width (here is the overlapping matrix case as we treat the row of an input image as one matrix for each patch).  image_width can be very large, ranging from 128 to maybe 2048. This kernel has one matrix-multiplication for each row of the image (also possibly large).

**Comment by CNugteren** [comment]
OK, thanks for letting me know. I'm working in general to make things faster for non-default sizes, and I'll come back to these configurations when I'm testing performance. I'll keep you posted (but nothing short term unfortunately, more like ~2 months).
