### ISSUE TITLE
CLBlast error -54 with Caffe Framework

### ISSUE THREAD

**Issue by mcian** [CNugteren/CLBlast#179]
Hi Cedric,

I have some problems with Caffe Framework after this [commit](https://github.com/CNugteren/CLBlast/commit/0ea16a0e635ebc9699bc83517b95f33547fadd3e)

I am not able to run it because the library raises the following error : "CLBlast: OpenCL error: clEnqueueNDRangeKernel: -54". 

I tried to revert the changes to the previous version of the code and it works.
I tested on GTX1080 and on Mali-T860.

**Comment by CNugteren** [comment]
That might indeed be the case, another user reported a similar issue. I'm on holiday now with only a mobile phone: if you have the time could you create a pull request that undoes this change and I'll merge it in asap. Thanks!

**Comment by CNugteren** [comment]
Thanks a lot, I merged it in. This should be fixed now.
