### ISSUE TITLE
Assuming that "default vendor / device type is last in the database"

### ISSUE THREAD

**Issue by newling** [CNugteren/CLBlast#189]
https://github.com/CNugteren/CLBlast/blob/297159d5b99f33f4e49cea238e66f1a1f05389a3/src/database/database.cpp#L160

This assumption tripped me up. I ran database.py adding a new device "gfx803", which appears after "default" alphabetically and was thus put after "default" in the database. As a result "default" kernel was returned by Database::Search. This could lead to an annoying performance bug for lower-case devices!

Please let me know if I should modify the logic here (either in database.cpp or database.hpp) to make "default" the last resort option.

**Comment by CNugteren** [comment]
Thanks for reporting. I'll fix this assumption early next week.

**Comment by CNugteren** [comment]
This assumption is now resolved in commit `28462aa`. Not sure how your issue was created however, because the `database.py` script only cares about alphabetically for non-default devices. Many device names appear alphabetically before "default", so not sure what exactly went wrong there?

**Comment by newling** [comment]
Great, thanks. I thought gfx803 was appearing after default, but I'm not
sure now. I thought it was because all the other devices start with
upper-case.
