### ISSUE TITLE
Random tuner GEMM Complex64 (Fiji on ROCm 1.6)  

### ISSUE THREAD

**Issue by newling** [CNugteren/CLBlast#190]
I am trying to run the full tuning suite on a Fiji Nano (with AMD ROCm 1.6). 

All's fine until part 2 (random search) of tuning for GEMM complex double (6464), where  a memory access fault is occasionally reported.

Running with VERBOSE=1 for CLTune and CLBlast, example output is

```
.
.
. 
[ VERBOSE  ] Completed kernel in 143.88 ms
[ VERBOSE  ] Launching kernel (2 out of 2 for averaging)
[ VERBOSE  ] Completed kernel in 144.13 ms
[       OK ] Completed Xgemm (143.9 ms) - 25 out of 199
[ VERBOSE  ] Exploring configuration (26 out of 199)
[ VERBOSE  ] Starting compilation
[ VERBOSE  ] Finished compilation
[ VERBOSE  ] Creating a copy of the output buffer
[ VERBOSE  ] Setting kernel arguments
[ RUN      ] Running Xgemm
[ VERBOSE  ] Launching kernel (1 out of 2 for averaging)
Memory access fault by GPU node-1 on address 0x4000. 
Reason: Page not present or supervisor privilege.
```

This might be specific to running on AMD ROCm. I'm not sure what the easiest way to print kernel parameters is to debug further?

**Comment by CNugteren** [comment]
Normally the kernel parameters are printed when an error occurs or when the results are incorrect. However, in your case this crash is too severe and doesn't let the program continue. I'll see if I can add always-on parameter printing in verbose mode just before the kernel starts.

**Comment by CNugteren** [comment]
The latest `master` branch of CLTune now adds printing of the parameter configuration in verbose mode before compiling and running. So that should at least give you information about which kernel is causing the crash.

**Comment by newling** [comment]
Thank you for making that change. I have run,

```
./clblast_tuner_xgemm --precision 6464
```

twice (only the random sampling part) and these are my outputs. 

run 1)
```
.
.
.
[ VERBOSE  ] Exploring configuration (18 out of 199):
[ VERBOSE  ]    MWG 64;  NWG 128;   KWG 16;  MDIMC 8;  
NDIMC 8;  MDIMA 8;  NDIMB 8;    KWI 2;    
VWM 8;    VWN 8;   STRM 0;   STRN 1;     SA 1;     SB 0;PRECISION 6464;
[ VERBOSE  ] Starting compilation
[ VERBOSE  ] Finished compilation
[ VERBOSE  ] Creating a copy of the output buffer
[ VERBOSE  ] Setting kernel arguments
[ RUN      ] Running Xgemm
[ VERBOSE  ] Launching kernel (1 out of 2 for averaging)
Memory access fault by GPU node-1 on address 0x902916000. 
Reason: Page not present or supervisor privilege.
Aborted (core dumped)
```

run 2)
```
.
.
.
[ VERBOSE  ] Exploring configuration (3 out of 199):
[ VERBOSE  ]   MWG 128;  NWG 128;   KWG 32;  MDIMC 8;  
NDIMC 8;  MDIMA 8; NDIMB 32;    KWI 2;    
VWM 8;    VWN 4;   STRM 1;   STRN 0;     SA 0;     SB 0;PRECISION 6464;
[ VERBOSE  ] Starting compilation
[ VERBOSE  ] Finished compilation
[ VERBOSE  ] Creating a copy of the output buffer
[ VERBOSE  ] Setting kernel arguments
[ RUN      ] Running Xgemm
[ VERBOSE  ] Launching kernel (1 out of 2 for averaging)
[ VERBOSE  ] Completed kernel in 2.94 ms
[ VERBOSE  ] Launching kernel (2 out of 2 for averaging)
[ VERBOSE  ] Completed kernel in 0.75 ms
[       OK ] Completed Xgemm (0.8 ms) - 3 out of 199
[  WARNING ] Results differ: L2 norm is 6.33e+08
[  WARNING ] Xgemm;      0.8 ms;  MWG 128;  NWG 128;   KWG 32;  MDIMC 8;  
NDIMC 8;  MDIMA 8; NDIMB 32;    KWI 2;    
VWM 8;    VWN 4;   STRM 1;   STRN 0;     SA 0;     SB 0;PRECISION 6464;
[ VERBOSE  ] Exploring configuration (4 out of 199):
.
.
.
[ VERBOSE  ] Exploring configuration (11 out of 199):
[ VERBOSE  ]   MWG 128;  NWG 128;   KWG 16;  MDIMC 8;
NDIMC 16; MDIMA 16; NDIMB 32;    KWI 2;    
VWM 8;    VWN 4;   STRM 0;   STRN 1;     SA 0;     SB 1;PRECISION 6464;
[ VERBOSE  ] Starting compilation
[ VERBOSE  ] Finished compilation
[ VERBOSE  ] Creating a copy of the output buffer
[ VERBOSE  ] Setting kernel arguments
[ RUN      ] Running Xgemm
[ VERBOSE  ] Launching kernel (1 out of 2 for averaging)
Memory access fault by GPU node-1 on address (nil). 
Reason: Page not present or supervisor privilege.
Aborted (core dumped)
```

A few more runs (and the iteration at which a problem is detected): 

15) MWG 128;   NWG 64;   KWG 32;  MDIMC 8;  NDIMC 8; MDIMA 16; NDIMB 32;    KWI 2;    VWM 8;    VWN 1;   STRM 1;   STRN 1;     SA 1;     SB 0;PRECISION 6464;

11) MWG 128;  NWG 128;   KWG 16;  MDIMC 8; NDIMC 16; MDIMA 16; NDIMB 32;    KWI 2;    VWM 8;    VWN 4;   STRM 0;   STRN 1;     SA 0;     SB 1;PRECISION 6464;

2)  MWG 128;   NWG 64;   KWG 16;  MDIMC 8;  NDIMC 8; MDIMA 16; NDIMB 32;    KWI 2;    VWM 8;    VWN 1;   STRM 0;   STRN 0;     SA 0;     SB 0;PRECISION 6464;

2) MWG 128;  NWG 128;   KWG 16; MDIMC 16;  NDIMC 8;  MDIMA 8; NDIMB 32;    KWI 2;    VWM 1;    VWN 2;   STRM 1;   STRN 0;     SA 0;     SB 0;PRECISION 6464;

19) MWG 128;  NWG 128;   KWG 32;  MDIMC 8;  NDIMC 8; MDIMA 16;  NDIMB 8;    KWI 2;    VWM 8;    VWN 4;   STRM 0;   STRN 1;     SA 0;     SB 1;PRECISION 6464;

7) MWG 128;  NWG 128;   KWG 16;  MDIMC 8;  NDIMC 8; MDIMA 32;  NDIMB 8;    KWI 2;    VWM 1;    VWN 1;   STRM 0;   STRN 0;     SA 0;     SB 0;PRECISION 6464;

1) MWG 128;   NWG 64;   KWG 32;  MDIMC 8;  NDIMC 8;  MDIMA 8; NDIMB 32;    KWI 2;    VWM 2;    VWN 1;   STRM 1;   STRN 0;     SA 1;     SB 0;PRECISION 6464;

1)  MWG 128;  NWG 128;   KWG 32; MDIMC 16;  NDIMC 8; MDIMA 32;  NDIMB 8;    KWI 2;    VWM 2;    VWN 1;   STRM 0;   STRN 1;     SA 0;     SB 0;PRECISION 6464;

3)  MWG 128;   NWG 64;   KWG 16;  MDIMC 8;  NDIMC 8; MDIMA 16;  NDIMB 8;    KWI 2;    VWM 1;    VWN 2;   STRM 1;   STRN 1;     SA 0;     SB 0;PRECISION 6464;

7) MWG 128;   NWG 64;   KWG 16;  MDIMC 8;  NDIMC 8; MDIMA 32;  NDIMB 8;    KWI 2;    VWM 2;    VWN 4;   STRM 1;   STRN 1;     SA 0;     SB 1;PRECISION 6464;

Could it be MWG 128? There are runs kernels with MWG 128 which pass. When MWG is not 128 all pass. So far though, I'll run some more.

**Comment by CNugteren** [comment]
What you could do is modify the code starting at [line 77 of the xgemm tuner](https://github.com/CNugteren/CLBlast/blob/master/src/tuning/kernels/xgemm.cpp#L77) to run only cases with MWG 128 and then try to narrow it down. But my guess is that this is an edge case in ROCm, also given that it only occurs for the double-complex precision.

To 'fix' your issue you can just exclude MWG 128 from the tuning parameters and continue running the tuner. Note sure if it is worth digging deeper here...

**Comment by newling** [comment]
Ya, probably not worth digging deeper at this point. I thought it'd be good to send you a complete tuning, but this can wait.

**Comment by CNugteren** [comment]
I'm closing this issue, since this is probably an issue with the ROCm compiler. The tuners of CLBlast catch all C++ exceptions and check for compilation errors, but if the driver just crashes then there is nothing I can do about it.
