### ISSUE TITLE
Why override for static runtime library with MSVC?

### ISSUE THREAD

**Issue by fzimmermann89** [CNugteren/CLBlast#200]
Hey,
I am trying to get arrayfire to compile using clBLast and stumbled upon linker errors because clblast is compiled with a static runtime library (MT) and arrayfire with a dynamic runtime (MD)
What is the reasoning for the override of the CXX flags?
Did you test this change with your build_clblast.cmake over at arrayfire?
Do you know how I can "override the override"? ;)

**Comment by CNugteren** [comment]
Sorry, I'm not too familiar with building for Windows, so I'm not 100% sure what you mean. I also don't know what this `build_clblast.cmake` is that you refer to? But note that there is a CMake option in CLBlast named `BUILD_SHARED_LIBS`. Default is ON, but perhaps you've set it to OFF?

**Comment by fzimmermann89** [comment]
I was refering to https://github.com/arrayfire/arrayfire/blame/master/CMakeModules/build_CLBlast.cmake

The problem is caused by dynamic vs. static linking of the MSVC runtime. This behavior is not affected by BUILD_SHARED_LIBS but by added "/MT" in https://github.com/CNugteren/CLBlast/blob/master/cmake/cxx_flag_overrides.cmake.

The problem is if one is static linking against ClBlast from e.g. arrayfire, both have to use the same type of runtime-linking (either MT or MD). Arrayfire is currently using MD/dynamic linking so one has to do same ugly overwriting of the overwritten CXX_Flags like 
`string(TOUPPER "CMAKE_CXX_FLAGS_${CMAKE_BUILD_TYPE}" cxx_flags_name)
[...]
"-D${cxx_flags_name}:STRING=${${cxx_flags_name}} -w -fPIC"`

to undo what https://github.com/CNugteren/CLBlast/blob/master/cmake/cxx_flag_overrides.cmake does. It would be nice if there was a way to disable the cxx_flags-overwrite. For example there could be an additional option MSVC_LINK_MD that is checked before the overwrite

**Comment by CNugteren** [comment]
Hmmm, yes, that piece of code. It got in by request of a user in #59. It is a bit of a strange bit of code, as it has to go all the way at the start of the CMakeLists.txt, but apparently this is what the recommended way is [according to the CMake documentation](https://cmake.org/Wiki/CMake_FAQ#How_can_I_build_my_MSVC_application_with_a_static_runtime.3F)

What I can do is indeed add a CMake option to disable these overrides. Would that solve it for you?

**Comment by fzimmermann89** [comment]
Thanks, that would definitively solve the issue for me, it seems like there is no more elegant way (quite surprising)

**Comment by CNugteren** [comment]
I've added the `OVERRIDE_MSVC_FLAGS_TO_MT` option, which is default to ON. Could you test with the latest master and set this option to OFF?
