### ISSUE TITLE
Adreno 330 GPU - GEMM tuner gets killed with custom M, N, K sizes

### ISSUE THREAD

**Issue by sivagnanamn** [CNugteren/CLBlast#201]
GEMM tuner gets killed for few custom M, N, K settings 

`./clblast_tuner_xgemm -m 256 -n 784 -k 1152 -precision 32 -alpha 1.00 -beta 1.00`

```
[       OK ] Completed Xgemm (454.1 ms) - 18 out of 360
[ RUN      ] Running Xgemm
[       OK ] Completed Xgemm (274.6 ms) - 19 out of 360
[ RUN      ] Running Xgemm
W/Adreno-GSL (26790): <gsl_ldd_control:476>: ioctl fd 3 code 0x400c0907 (IOCTL_KGSL_DEVICE_WAITTIMESTAMP_CTXTID) failed: errno 35 Resource deadlock avoided
W/Adreno-GSL (26790): <log_gpu_snapshot:385>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL (26790): <gsl_umd_context_waittimestamp:271>: error:-12 ctx 00000001 ts 62
W/Adreno-GSL (26790): <gsl_ldd_control:476>: ioctl fd 3 code 0xc02c093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock avoided
W/Adreno-GSL (26790): <log_gpu_snapshot:385>: panel.gpuSnapshotPath is not set.not generating user snapshot
E/Adreno-GSL (26790): <os_exit:1759>: Exiting the process clblast_tuner_xgemm from function cl_oxili_cmdbuffer_issue and line 366
Killed
```
[TunerError.txt](https://github.com/CNugteren/CLBlast/files/1390369/TunerError.txt)

Attached the full error as a file. Currently I've tuned GEMM for few of my custom M,N,K parameters and I have their respective best MWG, NWG, KWG... etc parameters. Until the next release with the following feature

`- Kernels are now cached based on their tuning parameters: fits the use-case of 'OverrideParameters'`

is there any quick hack to use these MWG, NWG, KWG... based on input M,N,K sizes? Please let me know if you have any suggestions.

**Comment by CNugteren** [comment]
About the error you are seeing: it seems this is an error message from your Qualcomm GPU driver, so I'm not sure how to handle this. Running this particular tuner command on my test system with Intel GPU actually works fine. The only viable solution I see is to make the CLBlast tuners more resilient against such crashes, making it continue anyway with the next tuning parameter and considering this particular one erroneous. I thought there was already something like that in place, but maybe this driver error is of some more sever form?

About your remark w.r.t. the change in the next release: you can of course check out the latest master and make use of that feature right away :-) If you use that feature in the 1.1.0 release then it will work but it will have to re-compile the kernel every time you override the parameters - not sure how often that will be for your use-case.

**Comment by sivagnanamn** [comment]
Thank you for the clarification. 

I have a suggestion regarding tuners. After making tuners resilient to such crashes, can the parameters that caused the crash be logged in separate database? So that these parameters can be ignored while tuning in a different machine with the same make.

**Comment by CNugteren** [comment]
Neither option would work: CLBlast currently just stores one single set of tuned parameters per device per kernel unfortunately.

What you would have to do is use the [OverrideParameters API](https://github.com/CNugteren/CLBlast/blob/master/include/clblast.h#L662) in your code every time you want to change the parameters. This would require re-compilation of the kernels every time, but not anymore in the latest master (that's the message in the changelog you referred to).

**Comment by sivagnanamn** [comment]
Okay :+1:  got it. I assumed that this feature will store mutliple sets of parameters per device based on user preference and launch kernels respectively based on input. Sorry for the misunderstanding.

I'll try the override API option.

**Comment by sivagnanamn** [comment]
I tried using OverrideParameters API.

1. Tune XGEMM for MNK - Lets refer this M,N,K as Set A
`./clblast_tuner_xgemm -m 32 -n 50176 -k 144 -precision 32 -alpha 1.00 -beta 1.00`

Best result of `clblast_xgemm_1_32.json`:
```
[----------] Printing best result to stdout
[     BEST ] Xgemm;   72.08 ms or 6.4 GFLOPS
```
Best result of `clblast_xgemm_2_32.json`:
```
[----------] Printing best result to stdout
[     BEST ] Xgemm;   91.04 ms or 5.1 GFLOPS
```
2. `python ../scripts/database/database.py . ..`
3. `make`
4. `make install`
5. Check XGEMM client with the same M,N,K parameters ( -m 32 -n 50176 -k 144 -precision 32 -alpha 1.00 -beta 1.00):
`./clblast_client_xgemm  -m 32 -n 50176 -k 144 -precision 32 -alpha 1.00 -beta 1.00`
```
                                                                                                                                             | <--       CLBlast       --> | <--       clBLAS        --> |
        m;        n;        k;   layout;   transA;   transB;      lda;      ldb;      ldc;     offa;     offb;     offc;    alpha;     beta;     ms_1; GFLOPS_1;    GBs_1;     ms_2; GFLOPS_2;    GBs_2
       32;      49K;      144;      101;      111;      111;      144;      49K;      49K;        0;        0;        0;     1.00;     1.00;   174.67;      2.6;      0.2;   471.41;      1.0;      0.1
```
6. Tune XGEMM for different M,N,K - Lets refer this M,N,K as Set B
Got Best result parameters after tuning. Used parameters from Set B's clblast_xgemm_1_32.json to override existing Xgemm kernel that was compiled with best parameters from Set A.

Even after using override, I'm not able to see any improvement in performance. Below is my overriding C API code:
```

char* kernel_name = "Xgemm";
const size_t num_parameters = 14;
char* parameters_names[14] = {"MWG", "NWG","KWG","MDIMC", "NDIMC", "MDIMA", "NDIMB", "KWI", "VWM", "VWN", "STRM", "STRN", "SA", "SB"};
size_t parameters_values[14] = {16, 32, 32, 8, 8, 8, 8, 2, 2, 1, 0, 0, 1, 1};
parameters_values[0] = 32; parameters_names[0]  = "KWG";
parameters_values[1] =  2; parameters_names[1]  = "KWI";
parameters_values[2] =  4; parameters_names[2]  = "MDIMA";
parameters_values[3] =  4; parameters_names[3]  = "MDIMC";
parameters_values[4] = 32; parameters_names[4]  = "MWG";
parameters_values[5] =  4; parameters_names[5]  = "NDIMB";
parameters_values[6] =  4; parameters_names[6]  = "NDIMC";
parameters_values[7] = 32; parameters_names[7]  = "NWG";
parameters_values[8] =  0; parameters_names[8]  = "SA";
parameters_values[9] =  0; parameters_names[9]  = "SB";
parameters_values[10] = 0; parameters_names[10] = "STRM";
parameters_values[11] = 0; parameters_names[11] = "STRN";
parameters_values[12] = 1; parameters_names[12] = "VWM";
parameters_values[13] = 1; parameters_names[13] = "VWN";

CLBlastStatusCode status = CLBlastOverrideParameters(get_device(), kernel_name, CLBlastPrecisionSingle, num_parameters, parameters_names, parameters_values);
``` 
Is there anything wrong in the usage of Override API ?

And there's a huge difference between  best GEMM execution time after TUNING (72.08 ms) & GEMM execution time during CLIENTS (174 ms), is this expected?

**Comment by CNugteren** [comment]
I will look at this in more detail later, but two things that you have to consider are:
1) For small sizes it will use the gemm_direct kernel, not the gemm kernel. You'll have to run those tuners as well.
2) When it runs the gemm kernel, it might have to run some pre-processing and post-processing kernels, perhaps they are slow.

To get more insight, you can compile the library in verbose mode (`-DVERBOSE=ON` to cmake). This will tell you which kernels are running and how long each kernel takes.

**Comment by sivagnanamn** [comment]
Thank you.

As you said, couple of the custom M,N,K sizes uses `gemm_direct` kernel. `gemm_direct` kernels seems to be slow for these M,N,K values, whereas the best results of `gemm` kernels are faster. Can they be forced to use `gemm` instead of `gemm_direct` kernels?

```
M: 16, N: 200704, K: 27, ALPHA: 1.000000, BETA: 1.000000, lda: 27, ldb: 200704, ldc: 200704, a_off: 0, b_off: 0, c_off: 0
[DEBUG] GEMM_Copy_32_8_8_1_Pad_32_8_2_1_Transpose_8_1_1_4_Padtranspose_0_8_2_Xgemm_32_2_8_8_32_8_8_32_1_1_0_0_4_1_XgemmDirect_2_8_8_8_8_1_1_2_1_16_KernelSelection_134217728
[DEBUG] Running kernel 'XgemmDirectTN'
[DEBUG] Completed kernel in 125.70 ms
M: 32, N: 50176, K: 144, ALPHA: 1.000000, BETA: 1.000000, lda: 144, ldb: 50176, ldc: 50176, a_off: 0, b_off: 0, c_off: 0
[DEBUG] GEMM_Copy_32_8_8_1_Pad_32_8_2_1_Transpose_8_1_1_4_Padtranspose_0_8_2_Xgemm_32_2_8_8_32_8_8_32_1_1_0_0_4_1_XgemmDirect_2_8_8_8_8_1_1_2_1_16_KernelSelection_134217728
[DEBUG] Running kernel 'TransposePadMatrix'
[DEBUG] Completed kernel in 0.36 ms
[DEBUG] Running kernel 'CopyPadMatrix'
[DEBUG] Completed kernel in 21.08 ms
[DEBUG] Running kernel 'TransposePadMatrix'
[DEBUG] Completed kernel in 7.26 ms
[DEBUG] Running kernel 'Xgemm'
[DEBUG] Completed kernel in 64.02 ms
[DEBUG] Running kernel 'TransposeMatrix'
[DEBUG] Completed kernel in 8.78 ms
M: 64, N: 12544, K: 288, ALPHA: 1.000000, BETA: 1.000000, lda: 288, ldb: 12544, ldc: 12544, a_off: 0, b_off: 0, c_off: 0
[DEBUG] GEMM_Copy_32_8_8_1_Pad_32_8_2_1_Transpose_8_1_1_4_Padtranspose_0_8_2_Xgemm_32_2_8_8_32_8_8_32_1_1_0_0_4_1_XgemmDirect_2_8_8_8_8_1_1_2_1_16_KernelSelection_134217728
[DEBUG] Running kernel 'TransposePadMatrix'
[DEBUG] Completed kernel in 0.40 ms
[DEBUG] Running kernel 'TransposePadMatrix'
[DEBUG] Completed kernel in 3.55 ms
[DEBUG] Running kernel 'Xgemm'
[DEBUG] Completed kernel in 55.77 ms
[DEBUG] Running kernel 'TransposeMatrix'
[DEBUG] Completed kernel in 4.58 ms
M: 128, N: 3136, K: 576, ALPHA: 1.000000, BETA: 1.000000, lda: 576, ldb: 3136, ldc: 3136, a_off: 0, b_off: 0, c_off: 0
[DEBUG] GEMM_Copy_32_8_8_1_Pad_32_8_2_1_Transpose_8_1_1_4_Padtranspose_0_8_2_Xgemm_32_2_8_8_32_8_8_32_1_1_0_0_4_1_XgemmDirect_2_8_8_8_8_1_1_2_1_16_KernelSelection_134217728
[DEBUG] Running kernel 'TransposePadMatrix'
[DEBUG] Completed kernel in 1.23 ms
[DEBUG] Running kernel 'TransposePadMatrix'
[DEBUG] Completed kernel in 2.77 ms
[DEBUG] Running kernel 'Xgemm'
[DEBUG] Completed kernel in 58.19 ms
[DEBUG] Running kernel 'TransposeMatrix'
[DEBUG] Completed kernel in 2.88 ms
M: 256, N: 784, K: 1152, ALPHA: 1.000000, BETA: 1.000000, lda: 1152, ldb: 784, ldc: 784, a_off: 0, b_off: 0, c_off: 0
[DEBUG] GEMM_Copy_32_8_8_1_Pad_32_8_2_1_Transpose_8_1_1_4_Padtranspose_0_8_2_Xgemm_32_2_8_8_32_8_8_32_1_1_0_0_4_1_XgemmDirect_2_8_8_8_8_1_1_2_1_16_KernelSelection_134217728
[DEBUG] Running kernel 'TransposePadMatrix'
[DEBUG] Completed kernel in 1.59 ms
[DEBUG] Running kernel 'CopyPadMatrix'
[DEBUG] Completed kernel in 2.40 ms
[DEBUG] Running kernel 'TransposePadMatrix'
[DEBUG] Completed kernel in 2.10 ms
[DEBUG] Running kernel 'Xgemm'
[DEBUG] Completed kernel in 55.38 ms
[DEBUG] Running kernel 'TransposeMatrix'
[DEBUG] Completed kernel in 1.28 ms
M: 512, N: 196, K: 2304, ALPHA: 1.000000, BETA: 1.000000, lda: 2304, ldb: 196, ldc: 196, a_off: 0, b_off: 0, c_off: 0
[DEBUG] GEMM_Copy_32_8_8_1_Pad_32_8_2_1_Transpose_8_1_1_4_Padtranspose_0_8_2_Xgemm_32_2_8_8_32_8_8_32_1_1_0_0_4_1_XgemmDirect_2_8_8_8_8_1_1_2_1_16_KernelSelection_134217728
[DEBUG] Running kernel 'TransposePadMatrix'
[DEBUG] Completed kernel in 4.98 ms
[DEBUG] Running kernel 'CopyPadMatrix'
[DEBUG] Completed kernel in 1.67 ms
[DEBUG] Running kernel 'TransposePadMatrix'
[DEBUG] Completed kernel in 0.97 ms
[DEBUG] Running kernel 'Xgemm'
[DEBUG] Completed kernel in 62.74 ms
[DEBUG] Running kernel 'TransposeMatrix'
[DEBUG] Completed kernel in 1.55 ms
M: 1024, N: 49, K: 4608, ALPHA: 1.000000, BETA: 1.000000, lda: 4608, ldb: 49, ldc: 49, a_off: 0, b_off: 0, c_off: 0
[DEBUG] GEMM_Copy_32_8_8_1_Pad_32_8_2_1_Transpose_8_1_1_4_Padtranspose_0_8_2_Xgemm_32_2_8_8_32_8_8_32_1_1_0_0_4_1_XgemmDirect_2_8_8_8_8_1_1_2_1_16_KernelSelection_134217728
[DEBUG] Running kernel 'TransposePadMatrix'
[DEBUG] Completed kernel in 31.72 ms
[DEBUG] Running kernel 'CopyPadMatrix'
[DEBUG] Completed kernel in 1.75 ms
[DEBUG] Running kernel 'TransposePadMatrix'
[DEBUG] Completed kernel in 2.02 ms
[DEBUG] Running kernel 'Xgemm'
[DEBUG] Completed kernel in 68.72 ms
[DEBUG] Running kernel 'TransposeMatrix'
[DEBUG] Completed kernel in 1.26 ms
M: 256, N: 49, K: 9216, ALPHA: 1.000000, BETA: 1.000000, lda: 9216, ldb: 49, ldc: 49, a_off: 0, b_off: 0, c_off: 0
[DEBUG] GEMM_Copy_32_8_8_1_Pad_32_8_2_1_Transpose_8_1_1_4_Padtranspose_0_8_2_Xgemm_32_2_8_8_32_8_8_32_1_1_0_0_4_1_XgemmDirect_2_8_8_8_8_1_1_2_1_16_KernelSelection_134217728
[DEBUG] Running kernel 'XgemmDirectTN'
[DEBUG] Completed kernel in 126.40 ms
```

**Comment by CNugteren** [comment]
Three remarks:

1. You could also tune the gemm_direct kernels (there is a tuner for that as well), perhaps you can improve performance there?
2. Sometimes the pre-processing kernels (e.g. TransposePadMatrix) seem to take a lot of time, around 50% of the actual GEMM kernel. On desktop hardware that percentage is typically a lot lower, but then also I see that you have large values for K and small for M and N. Perhaps that could influence the results a lot as well.
3. You can manually set the switching point between the two kernels [here in code](https://github.com/CNugteren/CLBlast/blob/master/src/database/kernel_selection.hpp#L62). I'm working on making this selection automatic (i.e. part of the tuning), see also #195.

**Comment by sivagnanamn** [comment]
Thank you for the pointers. This result is after tuning `gemm_direct` kernels only.

I'm doing trial & error for improving the performance. Will let you know if I come accross some possible solution.

**Comment by CNugteren** [comment]
From your results posted above it seems the regular ('in-direct') kernel with pre/post processing kernels is the best choice, since the direct kernel is a lot slower. But you tuned only the direct kernel, not the regular one? You can control the switching point between the two kernels in the `src/database/kernel_selection.hpp` file as I mentioned already above. Alternatively, you can use the OverrideParameters function to set this kernel selection if you need to change it dynamically.

But in general the kernels might not be so well suited for the Adreno hardware. I'm still planning on investigating myself a bit and see if the kernel design can be tweaked. I've just made a [public roadmap](https://github.com/CNugteren/CLBlast/blob/master/ROADMAP.md) on which you can see that I planned some time in November to get the code running on Android. In the meantime I've found a suitable Qualcomm Adreno Android phone, so I should be able to do some basic tests soon. After that, I plan to work on some optimizations for ARM Mali. I have some hope that those might help on Adreno GPUs as well, although that's just guessing. I'll keep you up-to-date of course on my progress :-)

**Comment by sivagnanamn** [comment]
Thank you for adding it to the roadmap. These results are after tuning both direct and regular(in-direct) kernels.

**Comment by sivagnanamn** [comment]
@CNugteren Need your help on tuning CopyPad in gemm in-direct kernel.

Output before tuning pre/post processing kernels:
```
M: 32, N: 50176, K: 144, ALPHA: 1.000000, BETA: 1.000000, lda: 144, ldb: 50176, ldc: 50176, a_off: 0, b_off: 0, c_off: 0
[DEBUG] GEMM_Copy_32_8_8_1_Pad_32_8_2_1_Transpose_8_1_1_4_Padtranspose_0_8_2_Xgemm_32_2_8_8_32_8_8_32_1_1_0_0_4_1_XgemmDirect_2_8_8_8_8_1_1_2_1_16_KernelSelection_2097152
[DEBUG] Running kernel 'TransposePadMatrix'
[DEBUG] Completed kernel in 0.40 ms
[DEBUG] Running kernel 'CopyPadMatrix'
[DEBUG] Completed kernel in 21.32 ms
[DEBUG] Running kernel 'TransposePadMatrix'
[DEBUG] Completed kernel in 7.11 ms
[DEBUG] Running kernel 'Xgemm'
[DEBUG] Completed kernel in 63.79 ms
[DEBUG] Running kernel 'TransposeMatrix'
[DEBUG] Completed kernel in 7.44 ms
```

Output after tuning pre/post processing kernels & using Override API for `Pad` , `Padtranspose` , `Xgemm` kernels:
```
M: 32, N: 50176, K: 144, ALPHA: 1.000000, BETA: 1.000000, lda: 144, ldb: 50176, ldc: 50176, a_off: 0, b_off: 0, c_off: 0
[DEBUG] GEMM_Copy_32_8_8_1_Pad_8_16_2_2_Transpose_8_1_1_4_Padtranspose_1_16_1_Xgemm_32_2_8_8_32_8_8_32_1_1_0_0_4_4_XgemmDirect_2_8_8_8_8_1_1_2_1_16_KernelSelection_2097152
[DEBUG] Running kernel 'TransposePadMatrix'
[DEBUG] Completed kernel in 0.39 ms
[DEBUG] Running kernel 'CopyPadMatrix'
[DEBUG] Completed kernel in 36.75 ms
[DEBUG] Running kernel 'TransposePadMatrix'
[DEBUG] Completed kernel in 9.35 ms
[DEBUG] Running kernel 'Xgemm'
[DEBUG] Completed kernel in 64.08 ms
[DEBUG] Running kernel 'TransposeMatrix'
[DEBUG] Completed kernel in 8.14 ms
```
How should I tune CopyPadMatrix in this case? Input matrices to the gemm function are of shape M=32, N=50176, K=144. So I tuned TransposePad & CopyPad kernels with  M=32, N=50176. Best tuning result for CopyPad is 1.44ms. But if I Override API, I'm not getting anywhere near 1.44ms.

Since there's a Transpose operation happening before CopyPad, should I tuner CopyPad with M=50176 & N=32 ? Please clarify.

**Comment by CNugteren** [comment]
Hmm, that's strange indeed. If you achieve 1.4ms and you see 30ms, then something is wrong. If you run this multiple times do you see consistent values? Because in some experiments you've posted a bit earlier in this issue I see quite a lot of variation in the results, e.g. here I quote you on a fast experiment:
```
M: 256, N: 784, K: 1152, ALPHA: 1.000000, BETA: 1.000000, lda: 1152, ldb: 784, ldc: 784, a_off: 0, b_off: 0, c_off: 0
[DEBUG] GEMM_Copy_32_8_8_1_Pad_32_8_2_1_Transpose_8_1_1_4_Padtranspose_0_8_2_Xgemm_32_2_8_8_32_8_8_32_1_1_0_0_4_1_XgemmDirect_2_8_8_8_8_1_1_2_1_16_KernelSelection_134217728
[DEBUG] Running kernel 'TransposePadMatrix'
[DEBUG] Completed kernel in 1.59 ms
[DEBUG] Running kernel 'CopyPadMatrix'
[DEBUG] Completed kernel in 2.40 ms
[DEBUG] Running kernel 'TransposePadMatrix'
[DEBUG] Completed kernel in 2.10 ms
[DEBUG] Running kernel 'Xgemm'
[DEBUG] Completed kernel in 55.38 ms
[DEBUG] Running kernel 'TransposeMatrix'
[DEBUG] Completed kernel in 1.28 ms
```
Is that because of those particular sizes? Or is it just that there's a lot of variation in execution time? Perhaps the OS doing something with OpenGL occassionally?

As for your question how to tune them: I don't think these kernels are too sensitive to the input size. So already just tuning them with some defaults values should be OK, but what you are doing should even be better but perhaps not necessary. Note that the padding part is not tuned, as far as I know it is just the regular copy/transpose kernels being tuned and then those parameters are re-used for the padded versions.

**Comment by sivagnanamn** [comment]
Even if run multiple times, I can see consistent value of 30 - 36ms. This slower execution time in CopyPad is only for few M,N,K setting (Ex: M: 32, N: 50176, K: 144), not for all M,N,K values. I couldn't find a common pattern between these M,N,K setting though.

**Comment by sivagnanamn** [comment]
Just to bring to your notice, clBLAS outperforms CLBlast for just one of my custom M,N,K setting.

If I'm not wrong, it will be faster if an internal switch can be made to convert this as GEMV operation for such M,N,K setting automatically.

```
./clblast_client_xgemm -m 1 -n 1029 -k 12544 -precision 32 -lda 12544 -ldb 12544 -ldc 1029 -alpha 1.00 -beta 1.00
                                                                                                                                            | <--       CLBlast       --> | <--       clBLAS        --> |
        m;        n;        k;   layout;   transA;   transB;      lda;      ldb;      ldc;     offa;     offb;     offc;    alpha;     beta;     ms_1; GFLOPS_1;    GBs_1;     ms_2; GFLOPS_2;    GBs_2
        1;     1029;    12544;      101;      111;      111;    12544;    12544;     1029;        0;        0;        0;     1.00;     1.00;   203.06;      0.1;      0.3;    26.10;      1.0;      2.0

```

**Comment by CNugteren** [comment]
Yes, that's a good remark.I'll add that feature when I have the time.

**Comment by sivagnanamn** [comment]
I'm able to observe an unaccounted time delay in  `gemm_indirect` kernels. I measured the time taken for Sgemm in C by using the snippet below:

```
struct timeval  tv1, tv2;
gettimeofday(&tv1, NULL);
cl_command_queue queue = cl.queue;
cl_event event;
cl.error = CLBlastSgemm(CLBlastLayoutRowMajor, 
                        TA?CLBlastTransposeYes:CLBlastTransposeNo, 
                        TB?CLBlastTransposeYes:CLBlastTransposeNo, 
                        M, N, K, ALPHA,
                        A_gpu, a_off, lda,
                        B_gpu, b_off, ldb, BETA,
                        C_gpu, c_off, ldc,
                        &queue, &event);
check_error_cl(cl);
gettimeofday(&tv2, NULL);
double gemm_time = (double) (tv2.tv_usec - tv1.tv_usec) / 1000000 + (double) (tv2.tv_sec - tv1.tv_sec);
printf ("SGEMM time = %f seconds\n", gemm_time);
```
Time taken by `gemm_direct` kernel:
```
[DEBUG] GEMM_Copy_32_8_8_1_Pad_32_8_2_1_Transpose_8_1_1_4_Padtranspose_0_8_2_Xgemm_32_2_8_8_32_8_8_32_1_1_0_0_4_1_XgemmDirect_2_8_8_8_8_1_1_2_1_16_KernelSelection_134217728
[DEBUG] Running kernel 'XgemmDirectTN'
[DEBUG] Completed kernel in 126.49 ms
SGEMM time = 0.127031 seconds
```
The timing metrics from DEBUG statements (126.49 ms) & C (127.031ms) are matching for `gemm_direct` kernels.

Time taken by `gemm_indirect` kernel:
```
[DEBUG] GEMM_Copy_32_8_8_1_Pad_32_8_2_1_Transpose_8_1_1_4_Padtranspose_0_8_2_Xgemm_32_2_8_8_32_8_8_32_1_1_0_0_4_1_XgemmDirect_2_8_8_8_8_1_1_2_1_16_KernelSelection_134217728
[DEBUG] Running kernel 'TransposePadMatrix'
[DEBUG] Completed kernel in 30.54 ms
[DEBUG] Running kernel 'CopyPadMatrix'
[DEBUG] Completed kernel in 0.82 ms
[DEBUG] Running kernel 'TransposePadMatrix'
[DEBUG] Completed kernel in 0.48 ms
[DEBUG] Running kernel 'Xgemm'
[DEBUG] Completed kernel in 66.66 ms
[DEBUG] Running kernel 'TransposeMatrix'
[DEBUG] Completed kernel in 1.23 ms
SGEMM time = 0.165009 seconds
```
Total time from `DEBUG` statements add up to `99.73 ms`, whereas C reports `165 ms`. There seems to be an unaccounted delay of `65 ms`. I can observe this behaviour for all `gemm_indirect` kernels, the unaccounted time delay varies for different M,N,K values.

Are there any other pre/post processing kernels that are not logging during DEBUG?

**Comment by CNugteren** [comment]
There is optionally also a temporary buffer being created (see [here](https://github.com/CNugteren/CLBlast/blob/master/src/routines/level3/xgemm.cpp#L176)), perhaps that's causing the extra time? You can time it as follows:
```
const auto start_time = std::chrono::steady_clock::now();
(...)
const auto elapsed_time = std::chrono::steady_clock::now() - start_time;
const auto time_ms = std::chrono::duration<double,std::milli>(elapsed_time).count();
```

**Comment by sivagnanamn** [comment]
Can I comment out these 4 temp buffers and check? Will it affect the gemm results by any chance?

**Comment by CNugteren** [comment]
I double-checked the status of this issue and it seems there is quite a lot of things ongoing, but I propose to close this issue now, because:

1. The original issue discussed here is a bug in the Qualcomm drivers and should be reported there. The tuners cannot catch such errors, it can only check for a valid status code returned and catch C++ exceptions, but not just any crash.

2. There is now a new tuner in the master branch which always outputs the parameter configuration before compiling, so it is now easier to diagnose which parameter combination(s) caused the compiler to crash.

3. Issue #195 is now closed. Buffer creation time can still be costly, but there is now a new tuner to decide which kernel to run (with or without temporary buffer creation).

4. We are aware of bad performance on Qualcomm GPUs, but there is a plan to implement a pre-processor first, and you also reported this in other issues which are still open. I propose to continue discussing there if needed.

If there is anything specific, please open a new issue. This issue contains a bit of everything ;-)
