### ISSUE TITLE
ARM Mali - SGEMM performance (example & questions)

### ISSUE THREAD

**Issue by sat8** [CNugteren/CLBlast#205]
Hi

You may have identified issues with ARM hardware already as I read  #128 before posting this issue. I will provide a bit more info, hoping it helps.
My [DNN inference engine](https://github.com/sat8/YoloOCLInference) works fine on desktop GPUs but on ARM boards (with Mali for now), it is not performing at all (produces 0.5 fps speed). I have tracked the issue down to slow SGEMM performance from CLBlast on Mali hardware. Here is an example with screenshots.

The first screenshot is the execution times (milliseconds) of various kernels **without GEMM calculation  in convolution layers** . The kernels are all queued up and the real execution time of the inference engine can be seen during a *blocking read* call (highlighted in red). As in screenshot, this produces ~11Fps inference processing speed on [Asus Tinkerboard](https://en.wikipedia.org/wiki/Asus_Tinker_Board).

![image](https://user-images.githubusercontent.com/8937796/31797173-e6f3b5d4-b524-11e7-824c-a2bbdb938480.png)

The 2nd screenshot is the execution time of all kernels **including GEMM in convolution layers**. The difference in this case is that after every kernel launch **clFinish** is issued, otherwise as before, the real execution times will end up calculated towards the end during the blocking read call(makes it difficult to find choke points). The GEMM related execution times are highlighted with the respective M, N, K values on which SGEMM call is invoked. 
As in screenshot, it's not looking very good with execution speeds of SGEMM entering triple digit range(s) (highlighted).

![image](https://user-images.githubusercontent.com/8937796/31797110-8559ec76-b524-11e7-8b5f-0417d8b58c7c.png)

**Q.** CLBlast is quite good with desktop grade GPUs. I have experimentally verified that CLBlast performs better than clBlas. Can you comment on whether clBlas performs any better than CLBLast on ARM Mali devices supposing you have run some experiments? I ask this as my board is running Yocto and it's quite tedious to build clBlas for the board to verify the performance myself.

**Q.** Is it in your priority list to investigate and optimize CLBlast for Mali GPUs? This is just so that I can give a shot at other BLAS implementations for OpenCL (eg: [ARM compute library](https://github.com/ARM-software/ComputeLibrary)) and make provisions in my project to link against CLBLast for desktop grade GPUs and a different BLAS library for ARM boards.

thnx

**Comment by sivagnanamn** [comment]
@sat8 I'm also facing similar issue in Adreno GPU's.

 Did you try tuning your CLBlast GEMM & GEMM direct kernels?? As of now, CLBlast just stores one single set of tuned parameters per device per kernel unfortunately. 

I'm using the [Override API](https://github.com/CNugteren/CLBlast/blob/master/doc/clblast.md#overrideparameters-override-tuning-parameters-auxiliary-function) to improve the performance.

Please give this a try, you haven't tried it yet.

**Comment by CNugteren** [comment]
I will write an answer later today or tomorrow when I have more time. But now for, maybe @psyhtest can also help you out, he is running GEMM and deep learning frameworks on Mali using CLBlast.

**Comment by sat8** [comment]
@sivagnanamn, thnx. I am just quoting @CNugteren here from #128 and a hypothesis is that ARM's OpenCL compiler is not doing it's best compared to other counterparts. So may be the compiler ought to be fixed. Can you share more details on your experiments with tuning so I can tune for Mali T760? 

@psyhtest , can you give me a hand here with how to go about getting the best out of CLBlast on ARM Mali? thnx.

**Comment by sivagnanamn** [comment]
@sat8 

First suggestion would be to use `-DVERBOSE=ON` with cmake and build CLBlast again. Now if you execute you DNN inference engine, it will print [DEBUG] statements like shown below:

```
[DEBUG] GEMM_Copy_32_8_8_1_Pad_32_8_2_1_Transpose_8_1_1_4_Padtranspose_0_8_2_Xgemm_32_2_8_8_32_8_8_32_1_1_0_0_4_1_XgemmDirect_2_8_8_8_8_1_1_2_1_16_KernelSelection_134217728
[DEBUG] Running kernel 'TransposePadMatrix'
[DEBUG] Completed kernel in 1.59 ms
[DEBUG] Running kernel 'CopyPadMatrix'
[DEBUG] Completed kernel in 2.40 ms
[DEBUG] Running kernel 'TransposePadMatrix'
[DEBUG] Completed kernel in 2.10 ms
[DEBUG] Running kernel 'Xgemm'
[DEBUG] Completed kernel in 55.38 ms
[DEBUG] Running kernel 'TransposeMatrix'
[DEBUG] Completed kernel in 1.28 ms
```
Now you'll get a better picture of which kernels are taking more time. Based on this, you can use different tuners (`-DTUNERS=ON ` with cmake) available in you build directory to tune the kernels that take more time with your custom M,N,K setting.

Ex: My `gemm_direct` kernel took a lot of time for `-m 16 -n 200704 -k 27 `

So, I tuned it using `./clblast_tuner_xgemm_direct -m 16 -n 200704 -k 27 -precision 32 -alpha 1.00 -beta 1.00`. At the end of tuning, you can see the best kernel parameters like shown below:
```
[----------] Printing best result to stdout
[     BEST ] XgemmDirectTN;    113.7 ms;   WGD 16; MDIMCD 8; NDIMCD 8; MDIMAD 8; NDIMBD 8;   KWID 2;   VWMD 2;   VWND 2;   PADA 1;   PADB 1;PRECISION 32;

[----------] Printing best result in database format to stdout
{ "QUALCOMM Adreno(TM)", { {"WGD",16}, {"MDIMCD",8}, {"NDIMCD",8}, {"MDIMAD",8}, {"NDIMBD",8}, {"KWID",2}, {"VWMD",2}, {"VWND",2}, {"PADA",1}, {"PADB",1}, {"PRECISION",32} } }
[ -------> ] 113.68 ms or 1.5 GFLOPS
```
Use the best parameter set (WGD, MDIMCD ...) to override your `gemm_direct` kernel while invoking that particular YOLO layer gemm.

Ex:  C - API of CLBlast Override
```
char* xgemm_direct_kernel_name = "XgemmDirect";
const size_t xgemm_direct_num_parameters = 10;
char* xgemm_direct_parameters_names[10] = {"WGD", "MDIMCD","NDIM
CD","MDIMAD", "NDIMBD", "KWID", "VWMD", "VWND", "PADA", "PADB"};

if(M==16 && <other conditions>) {
            size_t parameters_values[10] = {16, 8, 8, 16, 16, 2, 1, 1, 1, 0};
            CLBlastStatusCode status = CLBlastOverrideParameters(get_device(), xgemm_direct_kernel_name, CLBlastPrecisionSingle, xgemm_direct_num_parameters, xgemm_direct_parameters_names, parameters_values);

            if (status != CLBlastSuccess) {
                printf("------------- CLBlast GEMM Override error!!!! -------------- \n");
            }
}
```
This should be done before invoking your `CLBlastSgemm` kernel. The overridded set of parameters will be used until override function is invoked again.

**Comment by sat8** [comment]
@sivagnanamn , is there a typo **parameter_values**? They are different to what the tuner suggest as the best combination?

**Comment by CNugteren** [comment]
I still promised you an answer on your original questions:

Q1: Yes, clBLAS is tricky to compile for ARM, but I have done it before. Performance was not good. [Here is a graph on Mali-T628](https://github.com/CNugteren/CLBlast/files/1403292/hgemm_plot.pdf)
 I managed to quickly find of CLBlast versus clBLAS FP32. This shows the poor performance of clBLAS, managing just around ~1GFLOP on a device that should theoretically have more than 20GFLOPS possible if I recall correctly.

Q2: I'm still planning to spend time on optimising CLBlast for ARM Mali. However, it is not an easy task as it will probably require writing a simple pre-processor which unrolls loops and promotes small arrays to register values. I've just added a [roadmap document](https://github.com/CNugteren/CLBlast/blob/master/ROADMAP.md) to the repository in which I planned it in for November/December. Not sure how realistic this is though. 

About your experiments: these execution times don't mean much to me. Perhaps you can translate to GFLOPS while printing them? As you can see in the above graph I linked to, it should be possible to reach ~15GFLOPS on Mali-T628. If you can't come near those, I would suggest to try square matrices first (e.g. 512x512x512) to see if that might be causing the issue.

**Comment by sivagnanamn** [comment]
@sat8  Sorry, the `parameters_values` are different. You can replace with your best parameters after tuning.

**Comment by sat8** [comment]
@CNugteren thnx for the detailed explanation. I will convert the timing info to GFlops as indicated and update here. @sivagnanamn thnx for the confimation.

One thing I have noticed during tuning was that there were several warnings that inidicated the L2Norm was 10+e8 range. It sounds like the computed result from tuner is quite distant to what's expected (ground truth/similar). Any suggestion on how to fix this? 

Also, supposing I have fine tuned various instances of GEMM with the parameter combination of different m,n,k values, does CLBlastOverrideParameters cache (I may not be the using the right terminology) these combinations separately? If multiple combinations are not cached/stored, then what is the best strategy to select a single instance of those combinations?

**Comment by sivagnanamn** [comment]
@sat8 CLBlast does not cache all the combinations of M,N,K. It caches only one setting at a time. 

Assume you're using Override API with parameters "Set A" (Ex:  WGD 16; MDIMCD 8; NDIMCD 8; MDIMAD 8; NDIMBD 8;   KWID 2;   VWMD 2;   VWND 2;   PADA 1;   PADB 1) and executing `gemm_direct` kernel.

Until you use Override API again for `gemm_direct` kernel, the above "Set A" parameters will be used for launching the `gemm_direct` kernel. Since multiple combinations of same kernel is not cached now, the best strategy is to use the Override API for every layer in DNN inference engine :(

Regarding the L2Norm error, I too got similar warning while tuning. I didn't observer any change in my output precision. So I assumed those parameters (that caused the L2Norm difference) will be ignored while finding the best set. @CNugteren Please clarify regarding this.

**Comment by CNugteren** [comment]
Regarding the caching: @sivagnanamn is right, you'll need to use the override API everytime before you launch a new kind of GEMM call. So easiest is to write a small helper function which always calls the override API with the settings you want based on your m/n/k values. With the latest master version calling the override API is cheap, as no re-compilation of the kernel is needed if this kernel was already compiled before: the kernels themselves are thus cached properly based on the M/N/K values.

I would just ignore cases with a high L2 norm error in the tuner as long as there are not too many of them. They will automatically be ignored by the tuner, so you don't have to worry about erroneous kernels in the end. This could happen if a kernel crashes, uses too many registers, too large workgroup, or too much local memory or something like that. Although there are specific guards against this, sometimes erroneous kernels still run but luckily they will not be considered if the results are bad.

**Comment by janboeye** [comment]
@CNugteren I run clblast_tuner_xgemm on our mali platform, when I fill the result from the tuner into xgemm_32.h, the performance even worse than the default one. Is there any guide howto use tuner?

Thanks

**Comment by CNugteren** [comment]
It's explained in the [README](https://github.com/CNugteren/CLBlast#using-the-tuners-optional): you can either edit it manually, or you can use the python script, or you can use the override API. Keep in mind that there are two types of GEMM kernels. You can compile the library with `-DVERBOSE=ON` to get more insight.

Currently, Mali performance is ~2x lower than what it should be. There's an issue open for this #128, but since ARM doesn't seem to be working on fixing their compiler, I'm now [planning](https://github.com/CNugteren/CLBlast/blob/master/ROADMAP.md) to create my own pre-processor to fix those issues. Hopefully some results in a month or two.

**Comment by CNugteren** [comment]
I'm closing this issue now as I believe all your questions are answered now. Of course there is still the issue of performance, but there's #128 for that and I'm planning on working on that - I have access to my own Mali device now.

**Comment by tingxingdong** [comment]
> Q1: Yes, clBLAS is tricky to compile for ARM, but I have done it before.

Can you share your instruction of building clBLAS on ARM Mali? Thank you.

**Comment by psyhtest** [comment]
@tingxingdong 

1. [Install CK](https://github.com/ctuning/ck#installation)
2. Run:
```
$ ck pull repo:ck-math
$ ck install package:lib-clblas-2.12
...
Environment entry added (345eb92ddaca7213)!

Recording CK configuration to /home/anton/CK_TOOLS/lib-clblas-2.12-gcc-7.4.0-linux-64/ck-install.json ...

Installation path: /home/anton/CK_TOOLS/lib-clblas-2.12-gcc-7.4.0-linux-64

Installation time: 185.515856981 sec.
```
I've just installed clBLAS on [Firefly RK-3399](https://en.t-firefly.com/product/Rk3399/index.html).

But are you sure you want clBLAS, not CLBlast?

**Comment by tingxingdong** [comment]
Thanks  @psyhtest  for sharing.  Yes, I am talking about AMD's clBLAS.

**Comment by psyhtest** [comment]
You are welcome. Please let me know if you hit any issues or it just works (like it has for me).
