### ISSUE TITLE
implement (lapack) getrfBatched

### ISSUE THREAD

**Issue by iame6162013** [CNugteren/CLBlast#209]
I'm currently intending to implement getrf(Batched) (in opencl) and I wonder if this project is the best place to implement it in.

cuBlas implemented getrfbatched, thus implementing it here would improve compatibility between the 2 projects.

**Comment by CNugteren** [comment]
I had to look `getrf` up, but it seems it is LU-factorisation. 

Not sure if it is the best place indeed. Although CLBlast implements several non-BLAS routines, it doesn't do any LAPACK functions. Perhaps [clMagma](http://icl.cs.utk.edu/magma/software/view.html?id=207) or [ArrayFire](https://github.com/arrayfire/arrayfire) is a better starting point?

**Comment by iame6162013** [comment]
It appears that clMagma and ArrayFire do have the function implemented.
Thank you.
