### ISSUE TITLE
Adreno 330 - HGEMM tests fail

### ISSUE THREAD

**Issue by sivagnanamn** [CNugteren/CLBlast#211]
HGEMM correctness tests fail in Adreno 330 GPU. Complete log attached. I wanted to test correctness of HGEMM alone, so commented the remaining tests like SGEMM, DGEMM etc in [test/correctness/routines/level3/xgemm.cpp](https://github.com/CNugteren/CLBlast/blob/master/test/correctness/routines/level3/xgemm.cpp)

```
* Completed all test-cases for this routine. Results:
   176 test(s) passed
   278 test(s) skipped
   58 test(s) failed
```
Full test log ==> [hgemm_test.log](https://github.com/CNugteren/CLBlast/files/1436287/hgemm_test.log)

Verbose test log ==> [hgemm_verbose_test.log](https://github.com/CNugteren/CLBlast/files/1436620/hgemm_verbose_test.log)

**Comment by CNugteren** [comment]
Thanks for the complete report. From the logs you can see that the errors are only reported for ~5% of the cases and they are quite small. And given that SGEMM works fine, this might just be an inherent precision issue of FP16. I already put some total L2 error checking in the tests to test for correctness, but still tests 'fail' apparently.

So not sure if this an actual issue or whether this is just FP16 precision and we need to increase the error margins for the tests?

**Comment by sivagnanamn** [comment]
I tried using HGEMM instead of SGEMM, the results were totally different. That's why I ran the tests.
As you said, may be its just because of FP16 precision. I'm also not sure whether to spend time on this or not.

**Comment by sivagnanamn** [comment]
I came across a strange scenario while trying to benchmark CPU, SGEMM & HGEMM with my custom matrix size:

I created an HGEMM sample, similar to [SGEMM](https://github.com/CNugteren/CLBlast/blob/master/samples/sgemm.c). The outputs matched with CPU GEMM with loss in precision (expected).
```
 CPU GEMM      HGEMM
-------------------------
'-1.005429': '-0.999023',
'-0.162174': '-0.162231',
 '0.715662': '0.712402',
 '0.813231': '0.807617',
 '0.813230': '0.808594',
 '0.222859': '0.221924',
 '0.222858': '0.221191',
 '0.813235': '0.808594'
```

But when I add the same code to my DNN inference engine, HGEMM outputs are always 0. Only the sign bit matches with the CPU GEMM output, all other bits are always zero. Included `<clblast_half.h>`, to use `FloatToHalf` & `HalfToFloat` provided by CLBlast.
```
 CPU GEMM      HGEMM
-------------------------
'-1.005429': '-0.000000',
'-0.162174': '-0.000000',
 '0.715662': '0.000000',
 '0.813231': '0.000000',
 '0.813230': '0.000000',
 '0.222859': '0.000000',
 '0.222858': '0.000000',
 '0.813235': '0.000000'
```
I verified the input arrays to HGEMM API, thery're fine. Couldn't spot any abnormalities in debug logs too.

```
[DEBUG] GEMM_Copy_32_8_8_1_Pad_16_8_4_2_Transpose_8_0_0_4_Padtranspose_0_8_8_Xgemm_32_2_8_8_32_8_8_64_1_1_0_0_4_4_XgemmDirect_2_16_16_16_16_1_1_1_1_16_KernelSelection_134217728
[DEBUG] Compiling routine 'GEMM-16 (half)' for device 'QUALCOMM Adreno(TM)'
[DEBUG] Completed compilation in 1031.85 ms
[DEBUG] Running kernel 'XgemmDirectTN'
[DEBUG] Completed kernel in 306.99 ms
```

Could you please suggest if there's anything I should look into while using HGEMM ( or ) is there any other external library that should be linked inorder to use HGEMM?

**Comment by CNugteren** [comment]
So the sample works (up to some precision), but when you integrate it in your application it doesn't work anymore? Did you wait for the CLBlast event afterwards (or finish the queues) like in the example? Did you copy back the results to the CPU buffer properly? This seems to me like a bug in your application...

**Comment by sivagnanamn** [comment]
That's why I checked all the input array's and other parameters. The same code works for SGEMM. Yes, I waited for queue to finish, checked the return status & released the events.

**Comment by sivagnanamn** [comment]
cl_half alpha & beta initializations were the culprits :) Got HGEMM to work for most of the matrices.

However, in few cases the output varies a lot. It may be inherent precision issue. Below are few excerpts from the output matrix.

```
Expected   :   Actual      
-------------------------
-0.865050    -0.343750
-0.590155    -0.163452
-0.711898    -0.270264
-0.400125    -0.183960
 5.234834     0.667969
```

**Comment by CNugteren** [comment]
Good to hear you've got it working :-)

Yes, the precision is a bit tricky. Since I don't have a reference FP16 version of GEMM and other routines (CLBlast is tested against regular FP32 BLAS), I'm not sure what to expect. Maybe it's a bug in CLBlast, maybe it's not... You or I could implement a reference GEMM in C++ using [the half library](http://half.sourceforge.net/), but I'm not sure I want to do that for all cases of GEMM and all other routines in CLBlast. Also, the order in which you do the multiplications internally can influence the results a lot, so even that might not be conclusive...

**Comment by CNugteren** [comment]
Closing this issue now, because I believe the main issue is solved. There can still be errors, but they might only occur for certain values and for a certain order of computation. It is difficult to check 100% as I said above. Please re-open if you believe this is still an issue.
