### ISSUE TITLE
Latest 'master ' build always uses 'XgemmDirectTN' kernel for GEMM

### ISSUE THREAD

**Issue by sivagnanamn** [CNugteren/CLBlast#215]
After installing the latest [master(c41d219)](https://github.com/CNugteren/CLBlast/commit/c41d219ea42087c1b8d933b733b381005123cb91) build, `CLBlastSgemm` always uses `XgemmDirectTN` kernel irrespective of input M,N,K sizes. Using 'clblast_tuner_routine_xgemm' seems to have no effect on gemm kernel selection.

Step followed:
```
mkdir build
cd build
cmake -DTUNERS=ON ..
make
./clblast_tuner_xgemm -m xx -n yy -k zz
./clblast_tuner_xgemm_direct -m aa -n bb -k cc
./clblast_tuner_routine_xgemm
python ../scripts/database/database.py . ..
make
make install
```

In the previous releases, XgemmInDirect kernels were faster than direct kernels for most of my custom M,N,K settings.

**Comment by CNugteren** [comment]
Indeed, that tuner is new: it automatically determines the switching point. I have just checked on my test system and it does switch (Intel hardware, so at 192 for SGEMM). The default is 896 for SGEMM, so it should switch at that point for you before any tuning.

So either the tuning results are not as you expected or they are not properly set in the database. Could you copy the output that `clblast_tuner_routine_xgemm` gives you? And you can of course double check what the values are in `src/database/kernels/gemm_routine/gemm_routine_32.hpp` (before and after tuning).

**Comment by sivagnanamn** [comment]
I've attached both the output of `clblast_tuner_routine_xgemm` & `src/database/kernels/gemm_routine/gemm_routine_32.hpp` after tuning. 

For Qualcomm GPU's the switching point is 1048. What does this 1048 stands for? I'm still using the same M,N,K setting as mentioned in my previous issues 

```
    { // QUALCOMM GPUs
      kDeviceTypeGPU, "QUALCOMM", {
        { "default", {
          { Name{"QUALCOMM Adreno(TM)                               "}, Params{
1408, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 } },
          { kDeviceNameDefault                                        , Params{ 
1408, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 } },
        } },
      }
    },
```

My M,N,K setting:
```
M: 16 N: 200704 K: 27 
M: 32 N: 50176 K: 144 
M: 64 N: 12544 K: 288 
M: 128 N: 3136 K: 576 
M: 256 N: 784 K: 1152 
M: 512 N: 196 K: 2304 
M: 1024 N: 49 K: 4608 
M: 256 N: 49 K: 9216 
M: 1 N: 1029 K: 12544 
```
For all the above mentioned M,N,K setting, `CLBlastSgemm` is choosing `XgemmDirectTN` kernel now.

[GEMM_kernel_switching_data.zip](https://github.com/CNugteren/CLBlast/files/1481548/GEMM_kernel_switching_data.zip)

**Comment by CNugteren** [comment]
> For Qualcomm GPU's the switching point is 1408. What does this 1408 stands for?

Sorry, this is perhaps not super clear. This value determines the switching point to the in-direct GEMM kernel by comparing the `value^3` with `m*n*k`. So in your case it switches when `m*n*k > 1408*1408*1408`, which might not be true for any of your example tests.

Question is why the tuner would choose such a high value for your GPU when you claim that the direct kernel isn't super fast for large sizes. Could you maybe post the stdout (terminal) output of the routine tuner here (sorry, not the JSON, that's not super informative unfortunately, I'll fix that).

**Comment by sivagnanamn** [comment]
Thank you for the clarification :-)

I updated to the lastest master '[5467c0c](https://github.com/CNugteren/CLBlast/commit/5467c0cac55b02bda69057fe0a130379934b8edb)'.

I've attached the gemm routine stdout output (verbose build).
[gemm_routine.txt](https://github.com/CNugteren/CLBlast/files/1486590/gemm_routine.txt)

After updating the library, I followed the same steps mentioned in the issue description. Below is the content of `src/database/kernels/gemm_routine/gemm_routine_32.hpp` after tuning & using gemm routine function.


```
    { // QUALCOMM GPUs
      kDeviceTypeGPU, "QUALCOMM", {
        { "default", {
          { Name{"QUALCOMM Adreno(TM)                               "}, Params{
1088, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 } },
          { kDeviceNameDefault                                        , Params{
1088, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 } },
        } },
      }
    }
```

**Comment by CNugteren** [comment]
Thanks for the output. I noticed three things:
1. There are some displaying issues since the latest version. I just made a commit that should fix this.
2. I would recommend not running in verbose mode when running the tuners to prevent any overhead.
3. All your results (the final table is in GFLOPS, not in `ms` as displayed) are quite bad, but also not so different from each other. So the algorithm finds a switching point at m=n=k=1088, but the results don't seem to differ much anyway.

As a reference, here is the final output I get on my low-power Intel GPU:
```
|         ||   indirect GEMM   ||    direct GEMM    ||          |
|   m=n=k ||   ms   |  GFLOPS  ||   ms   |  GFLOPS  ||  score   | (lowest score == best switching point)
x---------xx--------x----------xx--------x----------xx----------x
|      64 ||   0.27 |      1.9 ||   0.11 |      4.7 ||    0.525 |
|     128 ||   0.30 |     13.9 ||   0.27 |     15.6 ||    0.014 |
|     192 ||   0.42 |     33.5 ||   0.74 |     19.2 ||    0.013 |
|     256 ||   0.66 |     51.2 ||   1.53 |     22.0 ||    0.522 |
|     320 ||   1.07 |     61.3 ||   2.97 |     22.1 ||    2.052 |
|     384 ||   1.49 |     76.1 ||   4.95 |     22.9 ||    4.602 |
|     448 ||   2.33 |     77.2 ||   7.46 |     24.1 ||    8.172 |
|     512 ||   3.27 |     82.2 ||  12.22 |     22.0 ||   12.763 |
|     576 ||   3.99 |     95.8 ||  17.00 |     22.5 ||   18.374 |
|     640 ||   5.39 |     97.3 ||  22.93 |     22.9 ||   25.006 |
|     704 ||   7.08 |     98.6 ||  31.02 |     22.5 ||   32.658 |
|     768 ||   8.87 |    102.1 ||  41.42 |     21.9 ||   41.331 |
|     832 ||  10.94 |    105.3 ||  52.48 |     21.9 ||   51.023 |
|     896 ||  13.51 |    106.5 ||  67.77 |     21.2 ||   61.737 |
|     960 ||  16.41 |    107.8 ||  84.65 |     20.9 ||   73.470 |
x---------xx--------x----------xx--------x----------xx----------x
```
In the above table it is clear that the in-direct kernel is much better for larger matrices and thus the tuner decides to switch from direct to in-direct at 192.

So not sure if there is a bug, but rather it is just in general an issue with super bad performance on your Qualcomm GPU. Which is a separate issue which hopefully will be resolved at some point :-)

**Comment by sivagnanamn** [comment]
In previous releases, as per your guidance I was able to modify the direct vs in-direct kernel switching point manually in `src/database/kernel_selection.hpp`. After adding auto kernel selection feature this file has been removed.

Can I still modify the `src/database/kernels/gemm_routine/gemm_routine_32.hpp` file manually to make the switching between direct & in-direct kernel selection?

**Comment by sivagnanamn** [comment]
I was able to change `src/database/kernels/gemm_routine/gemm_routine_32.hpp` manually to set a switching point irrespective of tuning results.

Thanks anyways :-)

**Comment by CNugteren** [comment]
Yes, you can still modify it, it has just moved to another place indeed :-)

**Comment by sivagnanamn** [comment]
I belive the kernel selection parameter configuration in old `src/database/kernel_selection.hpp` is now replaced by `src/database/kernels/gemm_routine/gemm_routine_32.hpp` for float32 GEMM in the latest commit. Please correct me if I'm wrong.

**Comment by CNugteren** [comment]
Yes, that's indeed the case. I think you already found this out on Nov 21 and I confirmed it :-)

**Comment by sivagnanamn** [comment]
Oops, sorry for the trouble. Bad memory :( Thanks again for your time :+1:
