### ISSUE TITLE
Cache OpenCL kernels on disk

### ISSUE THREAD

**Issue by haolongzhangm** [CNugteren/CLBlast#217]
as we known to let gpu cl code run more fast, sometimes we need use prebuild cl kernel, any option for
CLBLAST to enable this feature

**Comment by haolongzhangm** [comment]
time example:
result: we can find the most time cost to build cl kernel:
--------------------------------------------------------------------------log
[DEBUG] Found architectures of vendor 'QUALCOMM' and type 'GPU'
[DEBUG] Found devices of architecture type 'default'
[DEBUG] Found parameters for device type 'QUALCOMM Adreno(TM)'
[DEBUG] Searching database for kernel 'GemmRoutine'
[DEBUG] Device type 'GPU'; vendor 'QUALCOMM'
[DEBUG] Device name 'QUALCOMM Adreno(TM)'; architecture ''
[DEBUG] Found architectures of vendor 'default' and type 'default'
[DEBUG] Found devices of architecture type 'default'
[DEBUG] Found parameters for device type 'default'
[DEBUG] GEMM_Copy_32_32_8_1_Pad_32_8_2_1_Transpose_8_1_1_4_Padtranspose_0_8_2_Xgemm_32_2_8_8_32_8_8_32_1_1_0_0_4_1_XgemmDirect_2_8_8_8_8_1_1_2_1_16_GemmRoutine_896
[DEBUG] Compiling routine 'GEMM-32 (single)'
[DEBUG] Completed compilation in 685.97 ms
[DEBUG] Running kernel 'XgemmDirectTN'
[DEBUG] Completed kernel in 0.62 ms
I1120 17:20:23.824442  5786 greentea_math_functions.cpp:244] *** Benchmark begins 1***
[DEBUG] GEMM_Copy_32_32_8_1_Pad_32_8_2_1_Transpose_8_1_1_4_Padtranspose_0_8_2_Xgemm_32_2_8_8_32_8_8_32_1_1_0_0_4_1_XgemmDirect_2_8_8_8_8_1_1_2_1_16_GemmRoutine_896
[DEBUG] Running kernel 'XgemmDirectTN'
[DEBUG] Completed kernel in 1.30 ms
I1120 17:20:23.827507  5786 greentea_math_functions.cpp:244] *** Benchmark begins 1***
[DEBUG] GEMM_Copy_32_32_8_1_Pad_32_8_2_1_Transpose_8_1_1_4_Padtranspose_0_8_2_Xgemm_32_2_8_8_32_8_8_32_1_1_0_0_4_1_XgemmDirect_2_8_8_8_8_1_1_2_1_16_GemmRoutine_896
[DEBUG] Running kernel 'XgemmDirectTN'
[DEBUG] Completed kernel in 1.35 ms
I1120 17:20:23.829249  5786 greentea_math_functions.cpp:244] *** Benchmark begins 1***
[DEBUG] GEMM_Copy_32_32_8_1_Pad_32_8_2_1_Transpose_8_1_1_4_Padtranspose_0_8_2_Xgemm_32_2_8_8_32_8_8_32_1_1_0_0_4_1_XgemmDirect_2_8_8_8_8_1_1_2_1_16_GemmRoutine_896
[DEBUG] Running kernel 'XgemmDirectTN'
[DEBUG] Completed kernel in 1.04 ms
I1120 17:20:23.831645  5786 net.cpp:572] Layers: i = 5 name: bn0_1 use time: 726.44 ms.

**Comment by haolongzhangm** [comment]
already find the logic in file : src/cache.cpp
but sames just cache in DDR,  can imp the log to store into DISK, eg: a dir at emmc , data/....,
which can fast the cl when run cl code in second

**Comment by CNugteren** [comment]
You can indeed run the `FillCache` function (https://github.com/CNugteren/CLBlast/blob/master/include/clblast.h#L656) upfront, but that will take a while since it will pre-compile all kernels. Instead, I advise just to launch the routine you want once (e.g. on a 1x1 matrix) before you start timing your code.

No, it cannot be cached to disk, only to memory. I'm not sure how long disk access takes, but I guess compilation time will be in the same order of magnitude.

**Comment by haolongzhangm** [comment]
@CNugteren u can ref the 

https://github.com/viennacl/viennacl-dev/blob/master/viennacl/ocl/context.hpp 

it use sha1 to calculate the CL kernel code HASH ID, after build the Cl code , 
it will put the binary , which named HASH ID to disk, second time run CL code
will find if the CL code binary exist or not.

this will be more fast on phone GPU, 

test the  GEMM_Copy_32_32_8_1_Pad_32_8_2_1_Transpose_8_1_1_4_Padtranspose_0_8_2_Xgemm_32_2_8_8_32_8_8_32_1_1_0_0_4_1_XgemmDirect_2_8_8_8_8_1_1_2_1_16_GemmRoutine_896  kernel

build time will be take about 700ms , 
load binary time just 1-2 ms

**Comment by CNugteren** [comment]
OK, I will consider this a feature request then. I'll put it on the roadmap, you can expect the feature to be implemented around January or so. Still not sure how many use-cases there are when you cannot spare 700ms at program start-up to compile a kernel, but nevertheless good to have the cache-on-disk option as well.

**Comment by haolongzhangm** [comment]
@CNugteren   thanks for you info, 
because, we are trying use CLBlast on mobile phone, 700ms is so long at a realtime software
