### ISSUE TITLE
clCreateBuffer with mmap for the in-direct GEMM kernels

### ISSUE THREAD

**Issue by haolongzhangm** [CNugteren/CLBlast#218]
as we known, we can use CL_MEM_USE_HOST_PTR when clCreateBuffer API for CL kernel run fast,
so any plan to imp the clCreateBuffer with CL_MEM_USE_HOST_PTR

**Comment by haolongzhangm** [comment]
CL_MEM_USE_HOST_PTR will be quick at mobile GPU ,eg : Mali and QCOM adreno GPU

**Comment by CNugteren** [comment]
Not sure what your feature request is exactly, because it's up to the user to allocate the buffers, anyway he/she wants. Or are you perhaps referring to some of the temporary buffers created inside the GEMM routine? In that case, yes, perhaps it should be configurable how these buffers are allocated.

**Comment by sivagnanamn** [comment]
I believe @haolongzhangm  is refering to the temporary buffer creation in xgemm.cpp ([here](https://github.com/CNugteren/CLBlast/blob/master/src/routines/level3/xgemm.cpp#L176))

**Comment by haolongzhangm** [comment]
@CNugteren  @sivagnanamn  
yes I am refering code at : src/clpp11.hpp  : line 625  flags do not use CL_MEM_USE_HOST_PTR ,

@CNugteren  because , i am just care about the performance on phone GPU, eg ARM mali, QCOM adreno GPU, which is diff to desktop AMD NVIDA GPU, phone GPU, will be more fast when use CL_MEM_USE_HOST_PTR , then use mmap DDR mem to GPU mem,

**Comment by CNugteren** [comment]
Just to clarify again: this is just for the in-direct GEMM kernel, for all other routines there is no temporary memory allocation needed. Do you understand this?

And in that case @sivagnanamn might have a valid point: does it matter how you allocate the temporary buffer if you don't transfer between host and device at all? The temporary buffer is purely used on the device.
