### ISSUE TITLE
Does element-wise vector product function exists in CLBlast

### ISSUE THREAD

**Issue by kuroismith** [CNugteren/CLBlast#224]
aka Hadamard product

similar issue for OpenBLAS: https://github.com/xianyi/OpenBLAS/issues/1083

sbmv or tbmv do the trick but not sure if there is a more efficient way for doing so using OpenCL

**Comment by CNugteren** [comment]
To answer your question: no, it is not in CLBlast. But it makes sense to add it, also because it is in cuBLAS and MKL apparently. I'll put it on the roadmap, but give it 2/3 months because there are other more urgent things to do first.

**Comment by kuroismith** [comment]
great, it will be very helpful
thanks a lot for answering my question

**Comment by CNugteren** [comment]
FYI, I started working on this in the `CLBlast-224-hadamard-product` branch. It's a small task, so it should be finished in the next few days when I find some time. I went for the following definition / API, hope that suits your needs:


Performs the Hadamard element-wise product _z = alpha * x * y + beta * z_, in which _x_, _y_, and _z_ are vectors and _alpha_ and _beta_ are scalar constants. C++ API:
```
template <typename T>
StatusCode Had(const size_t n,
               const T alpha,
               const cl_mem x_buffer, const size_t x_offset, const size_t x_inc,
               const cl_mem y_buffer, const size_t y_offset, const size_t y_inc,
               const T beta,
               cl_mem z_buffer, const size_t z_offset, const size_t z_inc,
               cl_command_queue* queue, cl_event* event)
```

**Comment by CNugteren** [comment]
This is now merged into master. Could you have a look to see if this is indeed what you wanted?

**Comment by CNugteren** [comment]
I'm closing this issue since the routine is in CLBlast for almost a month now. If there is anything wrong with it, feel free to re-open this issue.

**Comment by kuroismith** [comment]
this feature is indeed what i wanted, i will try this in my code
