### ISSUE TITLE
[Feature request] Add CLBlast to common package managers

### ISSUE THREAD

**Issue by mratsim** [CNugteren/CLBlast#233]
Currently it doesn't seem like CLBlast is available through any package manager.

As a library author I would like to have it through at least apt-get on Ubuntu, Homebrew on MacOS and NuGet on Windows.

This has the following benefits:
  - Easier installation instructions for end-users
  - Much easier testing through Travis and Appveyor for libraries built on top of CLBlast

How-To:
 - [macOS via Homebrew](https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md)
 - [Ubuntu via PPA](https://help.launchpad.net/Packaging/PPA)
 - [Windows via Nuget](https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package). Note: OpenBLAS is available on Nuget and can serve as example.

Thank you!

**Comment by CNugteren** [comment]
You are right, it would be nice to have. I'll put it on the roadmap, but in the meanwhile any contributions are welcome.

**Comment by mirh** [comment]
https://aur.archlinux.org/packages/clblast-git/ 😉😉

**Comment by CNugteren** [comment]
I've started working on this, beginning with the Debian/Ubuntu package. I've made a repository for the config files and scripts: https://github.com/CNugteren/CLBlast-packaging.

There are instructions in the (README)[https://github.com/CNugteren/CLBlast-packaging/blob/master/README.md] how to try creating a Debian file. Currently there are still some `lintian` issues, any help is appreciated:
```
W: clblast source: binaries-have-file-conflict libclblast libclblast-dev usr/lib/x86_64-linux-gnu/libclblast.so
W: clblast source: binaries-have-file-conflict libclblast-dbgsym libclblast-dev-dbgsym usr/lib/debug/.build-id/70/3ab5fbc0a5c256682c35a631751815bfc35989.debug
W: clblast source: missing-license-paragraph-in-dep5-copyright apache v2.0 (paragraph at line 5)
W: clblast source: space-in-std-shortname-in-dep5-copyright apache v2.0 (paragraph at line 5)
W: libclblast-dev: package-name-doesnt-match-sonames libclblast
W: libclblast-dev: new-package-should-close-itp-bug
W: libclblast-dev: extended-description-line-too-long
W: libclblast-dev: shlib-without-versioned-soname usr/lib/x86_64-linux-gnu/libclblast.so libclblast.so
E: libclblast-dev: package-must-activate-ldconfig-trigger usr/lib/x86_64-linux-gnu/libclblast.so
W: libclblast: new-package-should-close-itp-bug
W: libclblast: extended-description-line-too-long
W: libclblast: shlib-without-versioned-soname usr/lib/x86_64-linux-gnu/libclblast.so libclblast.so
E: libclblast: package-must-activate-ldconfig-trigger usr/lib/x86_64-linux-gnu/libclblast.so
```

**Comment by CNugteren** [comment]
I've solved the issues and the library is now available on the [PPA](https://launchpad.net/~cnugteren/+archive/ubuntu/clblast). The corresponding scripts are [in a separate repository](https://github.com/CNugteren/CLBlast-packaging). I haven't tried it out myself yet.

I'll continue with NuGet and Homebrew.

**Comment by CNugteren** [comment]
CLBlast is now available in [Homebrew](https://github.com/Homebrew/homebrew-core/pull/24001):
```
brew update
brew install clblast
```

As for NuGet, I have to leave that open to someone more familiar with the Windows ecosystem. It seems it is meant for .NET and C# primarily, and [has no proper documentation for C++ libraries, see the comments](https://docs.microsoft.com/en-gb/nuget/create-packages/native-packages). I have written a [nuspec file](https://github.com/CNugteren/CLBlast-packaging/blob/master/nuget/CLBlast.nuspec), but not sure if that is of any use.

Also, every CLBlast release always has Windows binaries [as part of its release](https://github.com/CNugteren/CLBlast/releases), so that should ease testing a lot already, right?

**Comment by mratsim** [comment]
Awesome work.

I confirm it's available on Homebrew. I will write a CLBlast wrapper for Nim language similar to the current [low-level](https://github.com/nim-lang/opencl) and [high-level](https://github.com/unicredit/nimcl) opencl and [BLAS](https://github.com/unicredit/nimblas) wrappers and integrate it in my library [Arraymancer](https://github.com/mratsim/Arraymancer).

I'm closing this.
Thanks again.

**Comment by mratsim** [comment]
Nim wrapper for CLBlast added at [nim-clblast](https://github.com/numforge/nim-clblast).

The low-level bindings are autogenerated and track CLBlast master branch.

**Comment by CNugteren** [comment]
Thanks for providing these bindings! I've added them to the (new) bindings overview page:
https://github.com/CNugteren/CLBlast/blob/master/doc/bindings.md
