### ISSUE TITLE
Error with clblast_tuner_invert: Exception caught with status -2040 while running the reference

### ISSUE THREAD

**Issue by JayTay135** [CNugteren/CLBlast#235]
Running clblast_tuner_invert (x64) aborts on Windows 10 x64 and XFX Radeon R9 270 Core Edition 925MHZ 2GB 5.6GHZ graphics card. The application was compiled with MVSC 2017 (15.5.2) and the lastest github source commit 936cf26

clblast Diagnostics produce
--- OpenCL device naming:
* Device type                   GPU
* Device name                   Pitcairn
* Platform vendor               Advanced Micro Devices, Inc.
* Platform version              OpenCL 2.0 AMD-APP (2442.9)

 --- CLBlast device naming:
* Device type                   GPU
* Device name                   AMD Radeon (TM) R9 200 Series
* Device vendor                 AMD
* Device architecture           Pitcairn

 --- OpenCL device properties:
* Max work group size           256
* Max work item dimensions      3
* - Max work item size #0       256
* - Max work item size #1       256
* - Max work item size #2       256
* Local memory size             32768KB
* Extensions:
cl_khr_fp64 cl_amd_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_gl_sharing cl_amd_device_attribute_query cl_amd_vec3 cl_amd_printf cl_amd_media_ops cl_amd_media_ops2 cl_amd_popcnt cl_khr_d3d10_sharing cl_khr_d3d11_sharing cl_khr_dx9_media_sharing cl_khr_image2d_from_buffer cl_khr_spir cl_khr_gl_event cl_amd_liquid_flash

**Comment by CNugteren** [comment]
Could this perhaps be the same issue as #229? The invert kernel is used for the TRSM routine...

Perhaps you could try the `trsm_compilation` branch and see if the new `clblast_test_compile_invert` indeed hangs AMD's OpenCL compiler? If not, could you share the output of the invert tuner? And perhaps also run the TRSM test? Thanks!

**Comment by JayTay135** [comment]
I ran clblast_test_compile_invert  from the master branch and it resulted in a Windows restart. I then rebuilt the programs using the source code from the trsm_compilation branch. The three programs clblast_test_compile_invert, clblast_tuner_invert and clblast_test_xtrsm produced abort exceptions or ran out of memory necessitating a restart..

The following is the debug output
> ### clblast_test_xtrsm --verbose

* Options given/available:
    -platform 0 [=default]
    -device 0 [=default]
    -full_test [false]
    -verbose [true]
    -cblas 1 [=default]
    -clblas 0 [=default]

* Running on OpenCL device 'AMD Radeon (TM) R9 200 Series'.
* Starting tests for the 'STRSM' routine. Legend:
   : -> Test produced correct results
   . -> Test returned the correct error code
   X -> Test produced incorrect results
   / -> Test returned an incorrect error code
   \ -> Test not executed: OpenCL-kernel compilation error
   o -> Test not executed: Unsupported precision
   - -> Test not completed: Reference CBLAS doesn't output error codes
* Testing with error margins of 0.5% (relative) and 0.001 (absolute)
* Testing 'regular behaviour' for '101 (row-major) 141 (left) 121 (upper) 111 (regular) 132 (unit)':
   Testing: m=7 n=7 lda=7 ldb=7 offa=0 offb=0 alpha=3.14 [CLBlast][DEBUG] Searching database for kernel 'Copy'
[DEBUG] Device type 'GPU'; vendor 'AMD'
[DEBUG] Device name 'AMD Radeon (TM) R9 200 Series'; architecture 'Pitcairn'
[DEBUG] Found architectures of vendor 'AMD' and type 'GPU'
[DEBUG] Found devices of architecture type 'Pitcairn'
[DEBUG] Found parameters for device type 'default'
[DEBUG] Searching database for kernel 'Pad'
[DEBUG] Device type 'GPU'; vendor 'AMD'
[DEBUG] Device name 'AMD Radeon (TM) R9 200 Series'; architecture 'Pitcairn'
[DEBUG] Found architectures of vendor 'AMD' and type 'GPU'
[DEBUG] Found devices of architecture type 'Pitcairn'
[DEBUG] Found parameters for device type 'default'
[DEBUG] Searching database for kernel 'Transpose'
[DEBUG] Device type 'GPU'; vendor 'AMD'
[DEBUG] Device name 'AMD Radeon (TM) R9 200 Series'; architecture 'Pitcairn'
[DEBUG] Found architectures of vendor 'AMD' and type 'GPU'
[DEBUG] Found devices of architecture type 'Pitcairn'
[DEBUG] Found parameters for device type 'default'
[DEBUG] Searching database for kernel 'Padtranspose'
[DEBUG] Device type 'GPU'; vendor 'AMD'
[DEBUG] Device name 'AMD Radeon (TM) R9 200 Series'; architecture 'Pitcairn'
[DEBUG] Found architectures of vendor 'AMD' and type 'GPU'
[DEBUG] Found devices of architecture type 'Pitcairn'
[DEBUG] Found parameters for device type 'default'
[DEBUG] Searching database for kernel 'Xgemm'
[DEBUG] Device type 'GPU'; vendor 'AMD'
[DEBUG] Device name 'AMD Radeon (TM) R9 200 Series'; architecture 'Pitcairn'
[DEBUG] Found architectures of vendor 'AMD' and type 'GPU'
[DEBUG] Found devices of architecture type 'Pitcairn'
[DEBUG] Found parameters for device type 'default'
[DEBUG] Searching database for kernel 'XgemmDirect'
[DEBUG] Device type 'GPU'; vendor 'AMD'
[DEBUG] Device name 'AMD Radeon (TM) R9 200 Series'; architecture 'Pitcairn'
[DEBUG] Found architectures of vendor 'AMD' and type 'GPU'
[DEBUG] Found devices of architecture type 'default'
[DEBUG] Found parameters for device type 'default'
[DEBUG] Searching database for kernel 'GemmRoutine'
[DEBUG] Device type 'GPU'; vendor 'AMD'
[DEBUG] Device name 'AMD Radeon (TM) R9 200 Series'; architecture 'Pitcairn'
[DEBUG] Found architectures of vendor 'default' and type 'default'
[DEBUG] Found devices of architecture type 'default'
[DEBUG] Found parameters for device type 'default'
[DEBUG] TRSM_Copy_8_16_4_1_Pad_32_8_1_2_Transpose_16_0_1_1_Padtranspose_0_16_4_Xgemm_16_2_16_8_32_16_16_128_0_0_1_0_1_1_XgemmDirect_2_16_16_8_8_1_1_1_1_16_GemmRoutine_768
[DEBUG] Compiling routine 'TRSM-32 (single)'
[DEBUG] Completed compilation in 382.67 ms
[DEBUG] Running kernel 'FillMatrix'
[DEBUG] Completed kernel in 0.20 ms
[DEBUG] Searching database for kernel 'Invert'
[DEBUG] Device type 'GPU'; vendor 'AMD'
[DEBUG] Device name 'AMD Radeon (TM) R9 200 Series'; architecture 'Pitcairn'
[DEBUG] Found architectures of vendor 'default' and type 'default'
[DEBUG] Found devices of architecture type 'default'
[DEBUG] Found parameters for device type 'default'
[DEBUG] INVERT_Invert_16_0_4_4
[DEBUG] Compiling routine 'INVERT-32 (single)'

> ### clblast_test_compile_invert --verbose

* Options given/available:
    -platform 0 [=default]
    -device 0 [=default]

[DEBUG] Searching database for kernel 'Invert'
[DEBUG] Device type 'GPU'; vendor 'AMD'
[DEBUG] Device name 'AMD Radeon (TM) R9 200 Series'; architecture 'Pitcairn'
[DEBUG] Found architectures of vendor 'default' and type 'default'
[DEBUG] Found devices of architecture type 'default'
[DEBUG] Found parameters for device type 'default'
[DEBUG] INVERT_Invert_16_0_4_4
[DEBUG] Compiling routine 'INVERT-32 (single)'

>### clblast_tuner_invert --verbose
* Options given/available:
    -platform 0 [=default]
    -device 0 [=default]
    -precision 32 (single) [=default]
    -n 128 [=default]
    -m 64 [=default]
    -k 16 [=default]
    -fraction 1.00 [=default]
    -runs 10 [=default]
    -max_l2_norm 0.00 [=default]

* Found 2 configuration(s)
* Parameters explored: INTERNAL_BLOCK_SIZE LOCALPAD TMMWGSX TMMWGSY

|   ID | total |               param |       compiles |         time |    N/A |            status |
x------x-------x---------------------x----------------x--------------x--------x-------------------x
|  ref |     - |                   - |

**Comment by CNugteren** [comment]
OK, thanks for testing. Then this is indeed a bug in the AMD APP. We'll try to work around it in #229.

**Comment by CNugteren** [comment]
I'm closing this issue since it seems the same as already reported.

@JayTay135 If you have time could you go to #229 and look at my latest reply and try that out? You can report in that issue if you want. Thanks!
