### ISSUE TITLE
Library interface limits performance

### ISSUE THREAD

**Issue by Ttl** [CNugteren/CLBlast#237]
I tried to use CLBlast to implement F(2x2, 3x3) Winograd convolution for leela-zero (https://github.com/gcp/leela-zero), but I ran into some difficulties that I couldn't solve without copying the OpenCL kernels from CLBlast and calling them directly.

I implemented the Winograd convolution with CLBlast used for the batched sgemm part. The first implementation which called GemmBatched had much worse performance than direct convolution (454 nodes/s vs. 940 nodes/s). The involved matrices are pretty small m, n, k, batches = 64, 100, 64, 16 and more time was spent in transferring alpha, beta and offset buffers to device than actually calculating sgemm. When I copied the direct sgemm kernel and called it directly I was able to reach 1139 nodes/s performance exceeding the direct convolution performance.

Next I implemented Winograd convolution using the non-direct sgemm kernel (kernel copied and called directly), but with zero-padding and transpositions taken care during the Winograd input and output transformations. This version was able to reach 1444 nodes/s. However even if the buffer issue is fixed implementing this version seems impossible using the current interface. The surrounding code needs to know the tuning parameters for the correct zero-padding and I couldn't find a way to get the tuning parameters using the current interface. If the matrix sizes are not right the convolution performance is going to take a serious hit if copying and padding is needed for every sgemm call.

The default parameters for sgemm kernel also don't seem very good. Performance with default parameters was about 50% worse on my computer making Winograd convolution perform worse than the direct convolution implementation. The optimal parameters for my GPU were not good for some other users. Not every GPU is going to be included in the database and for an application like leela-zero tuning on the end-user's computer is necessary.

The original issue can be found at: https://github.com/gcp/leela-zero/issues/498

**Comment by CNugteren** [comment]
Thanks for reporting! OK, let me try to rephrase the issues you report in my own words:

1. The `GemmBatched` routine is slow because it has to transfer all alpha values, all beta values, and all offsets from host to device. If all of these are non-standard, I see no way around it. However, in your case there is some assumption. Are all your alpha/beta values the same? Is the offset to the next matrix always the same? In the latter case it seems also related to the last few posts of #95.

2. You want to prepare you matrices such that the m/n/k values are such that no pre & post-processing kernels are required to run. This is currently indeed not possible, since there is no interface to retrieve these parameters. I see no reason why I couldn't implement this. In fact, there is something similar already being done in the `gemm_api_with_temp_buffer` in which I make it possible to already provide a temporary buffer to GEMM, to avoid memory allocation overhead.

3. The tuning parameters are not always optimal for a particular problem/device combination. Indeed, this is an issue. Also because the parameters are tuned for 1024x1024x1024, which might not be a realistic use-case for the batched version. There is work ongoing on making the tuning problem-specific, but that's perhaps longer term (see #169). What do you suggest to do here?

**Comment by Ttl** [comment]
1. I wouldn't mind passing the device buffers to the function instead of letting the method to allocate them. In this case alpha and beta are constant and offsets are in linear progression. `gemmStridedBatched` mentioned in #95 should work.

2. Also some way of specifying which kernel to use is necessary. If the switching point between direct and non-direct methods is determined with tuning with pre and post processing enabled this small matrices would probably end up using the direct kernel instead.

3. The bigger problem with tuning is that when the library is distributed as a part of a program and user doesn't compile either of them themselves they can't use tuners. If the user doesn't have a device already listed in the database they are stuck with the default values that can give very poor performance with some GPUs. Run-time tuning is necessary to solve this.

**Comment by CNugteren** [comment]
OK, I'll start with point 1, tackling the batched GEMM issue with the alphas/betas/offsets overhead. I suggest to discuss that further in #95 (please see my latest message there). After that's completed and when I have time, we'll discuss points 2 and 3 here.

**Comment by CNugteren** [comment]
Now that a first version of `GemmStridedBatched` is implemented, let's discuss how to tackle point 2. For this point we'll need two things:

*2a*: Make it possible to select the in-direct GEMM kernel for batched routines (the kernels and host-code are implemented, but not used). Perhaps make it another tuning parameter.

*2b*: An interface to retrieve the tuning parameters. Would it be OK to create a generic CLBlast-wide interface, e.g.:
```
StatusCode RetrieveTuningParameters(const cl_device_id device, const std::string &kernel_name,
                                   const Precision precision,
                                   const std::unordered_map<std::string,size_t> &parameters)
```

What do you think?

**Comment by Ttl** [comment]
Sounds good. I would need to first get the tuning parameters, then modify the parameter for choosing the kernel and finally use `OverrideParameters` to set the parameters?

**Comment by CNugteren** [comment]
Regarding point 2b:

I've just added such a function to the master branch of CLBlast (#240):
```
StatusCode PUBLIC_API RetrieveParameters(const cl_device_id device, const std::string &kernel_name,
                                         const Precision precision,
                                         std::unordered_map<std::string,size_t> &parameters);
```
You can use it like this:
```
auto parameters = std::unordered_map<std::string,size_t>();
const auto status = clblast::RetrieveParameters(device, "Xgemm", clblast::Precision::kSingle, parameters);
if (status != clblast::StatusCode::kSuccess) { return; } // handle errors here
std::cout << parameters["NWG"] << std::endl;
```
The above would retrieve the parameters `"KWG", "KWI", "MDIMA", "MDIMC", "MWG", "NDIMB", "NDIMC", "NWG", "SA", "SB", "STRM", "STRN", "VWM", "VWN"` for the `Xgemm` routine for a particular device/precision. For the kernel-selection, you should retrieve parameters for `GemmRoutine`.

> I would need to first get the tuning parameters, then modify the parameter for choosing the kernel and finally use OverrideParameters to set the parameters?

Not 100% sure what you mean. I thought you just wanted to know the parameters so you can already pre-shape your matrices with padding if needed?

**Comment by Ttl** [comment]
Override was for point 2a to use Batched Gemm with in-direct kernel.

**Comment by CNugteren** [comment]
I've also sort-of addressed point 2a by using the same tuning parameter as for the regular GEMM to select direct vs in-direct kernels. See more details in #244. Would that be OK for now for your use-case?

As far as I understand then only point 3 remains: tuning integrated in the library through an API rather than separate binaries. Can you confirm all else is now solved?

**Comment by Ttl** [comment]
I haven't tested the newest changes yet, but they should address everything except the tuning.

**Comment by CNugteren** [comment]
I've started working on the tuning API. First version is now available in the `CLBlast-237-tuning-api` branch. It includes an example of tuning the copy-kernel. Here's the important part:

```
  std::unordered_map<std::string,size_t> parameters;
  auto status = clblast::TuneCopyMatrixFast<float>(&queue, m, n, fraction, parameters);

  for (const auto parameter: parameters) {
    printf(">  %s = %zu\n", parameter.first.c_str(), parameter.second);
  }

  status = clblast::OverrideParameters(device(), "Copy", clblast::Precision::kSingle, parameters);
```

Any remarks before I continue? The `fraction` argument can be set between 0.0 and 1.0 to tune only a random part of the kernels.

**Comment by Ttl** [comment]
It looks good to me.

I had some problems with compiling the branch. It seems that there is extra main definition in "tuning/kernels/xger.hpp". After removing that it compiled fine and I was able to run the tuning sample program successfully.

**Comment by CNugteren** [comment]
OK, thanks for your feedback.

Yes, I noticed that issue as well, I fixed it but did not push yet.

I'll continue with this and will add all kernels and documentation.

**Comment by CNugteren** [comment]
I finished the implementation and documentation, PR is waiting for some tests (#262). Let me know if you still think something is missing or incorrect.

**Comment by Ttl** [comment]
I tested the code by running the tuner on Xgemm and it looks like it's working fine.

I believe that all the problems in this issue are now fixed. Thanks for your work.
