### ISSUE TITLE
How to adjust AMD GPU frequency?

### ISSUE THREAD

**Issue by ysh329** [CNugteren/CLBlast#241]
Hello, I wanna ask a basic question about performance setting. My hardware device is an APU but I only run it's GPU to execute CLBlast. However, before that, I need to adjust frequency to performance mode and check current frequency (mode)? 

I'm not familiar AMD GPU setting. Thus, I want to ask what tools should I install to make gpu setting?

Thanks in advance 🙇 

My detailed GPU info. is below:

```shell
Number of platforms:                             1
  Platform Profile:                              FULL_PROFILE
  Platform Version:                              OpenCL 2.0 AMD-APP (1912.5)
  Platform Name:                                 AMD Accelerated Parallel Processing
  Platform Vendor:                               Advanced Micro Devices, Inc.
  Platform Extensions:                           cl_khr_icd cl_amd_event_callback cl_amd_offline_devices 


  Platform Name:                                 AMD Accelerated Parallel Processing
Number of devices:                               2
  Device Type:                                   CL_DEVICE_TYPE_GPU
  Vendor ID:                                     1002h
  Board name:                                    AMD Radeon R6 Graphics
  Name:                                          AMD Embedded R-Series RX-416GD Radeon R6
  Vendor:                                        AuthenticAMD
```

My relative issues:

- Support AMD Embedded R-Series RX-416GD Radeon R6? · Issue #27 · ROCmSoftwarePlatform/MIOpen https://github.com/ROCmSoftwarePlatform/MIOpen/issues/27
- How to set Performance mode for AMD GPU · Issue #327 · clMathLibraries/clBLAS
clMathLibraries/clBLAS#327

**Comment by CNugteren** [comment]
I don't think this question is related to CLBlast, it seems like an AMD/driver/OS issue instead. This is not the right place to ask, I cannot help you here.
