### ISSUE TITLE
how to use use tuned parameters in pyclblast?

### ISSUE THREAD

**Issue by kodonnell** [CNugteren/CLBlast#254]
Question as above - it doesn't yet seem supported? There's probably a way to run the tuners and recompile pyclblast and `pip setup.py install` - but I was hoping one could create a python API for `OverrideParameters` in the python API? I'm happy to have a crack, especially if you provide some basic direction.

**Comment by CNugteren** [comment]
Indeed, this is not possible yet. The Python interface can only call the main routine.

It should be added to [PyCLBlast](https://github.com/CNugteren/CLBlast/blob/master/src/pyclblast/src/pyclblast.pyx) which is written in Cython. I'm no expert either, so if you want to try, please, go ahead.

**Comment by kodonnell** [comment]
Sure, I might have a play - I've used cython a bit before. Some quick questions for you:

- what do you mean by 'the main routine'?
- from [here](https://github.com/CNugteren/CLBlast/blob/master/doc/tuning.md#inspecting-and-changing-tuning-parameters-at-run-time) I gather I only need to call `OverrideParameters` once and the following API calls will obey this ... what do I need to keep 'alive' so I only have to call it once? The cl context? Or is the parameter database just stored in memory somewhere, and calling `OverrideParameters` just alters it?

**Comment by CNugteren** [comment]
Sorry, I fixed my comment, I meant the main BLAS routines, not any of the other APIs.

No, I think you shouldn't worry about anything. It's just a matter of creating an interface to call the `OverrideParameters` function, things are cached automatically. I hope :-) I'll test myself later if the caches in CLBlast are properly working with the Python interface.

**Comment by kodonnell** [comment]
Thanks. I think it's mostly ready to go, but I can't compile as I don't know what `RawDeviceID` (i.e. `cl_device_id` is, and where to get that from - I assume the `ctx`? I'm hoping you can point in the right direction ...

**Comment by CNugteren** [comment]
The `cl_device_id` is just the regular OpenCL device ID. So that should be defined in PyOpenCL somehow,  e.g. [this](https://documen.tician.de/pyopencl/runtime_platform.html#device). You can indeed also decide to change the interface and take the context in indeed and get the device from that.

**Comment by kodonnell** [comment]
Thanks - see #255 for progress. I couldn't figure out how to get it out of pyopencl. I thought I'd posted an issue to pyopencl, but it appears I didn't hit 'send' or something. Maybe tomorrow.

**Comment by kodonnell** [comment]
Implemented in #255, so closing.
