### ISSUE TITLE
glossary?

### ISSUE THREAD

**Issue by kodonnell** [CNugteren/CLBlast#256]
As someone reasonably familiar with nets, but less so with the engineering of them, I'm finding it a bit hard to get my head across all terms - some of which (like direct vs indirect convolution) I can't find via Google either. If anyone else is in my shoes, then maybe a basic glossary would be beneficial? Summarising key algorithms etc. (with references would be great too). It might aid contributions too.

**Comment by CNugteren** [comment]
I don't think CLBlast is the right place for this. It is a BLAS library, which could be used for neural networks and convolutions, but that's just one use-case. So I think there are better places where such answers can be found.

By the way, can you point me to the place in CLBlast where you read about the direct and indirect convolutions? Perhaps what is meant is that direct convolution means doing the actual convolutions (NxM neighbourhood multiplying with filter weights and summing the result) whereas indirect could mean using GEMM instead (e.g. explained on https://petewarden.com/2015/04/20/why-gemm-is-at-the-heart-of-deep-learning/).

**Comment by kodonnell** [comment]
Sorry, my mistake - I meant direct and indirect gemm! Given you're already replied, I won't correct my original post.

I agree - no need to document applications such as neural nets. However, documenting (or at least providing links) to what e.g. batched/stridedbatch, or indirect/direct gemm are, would probably be relevant, as they are functions in CLBlas. That said, I did figure out the former by looking up the cuBLAS documentation. Anyway, your call - I'm just one vote, and maybe no one else needs it. (If so, you can close this.)

**Comment by CNugteren** [comment]
OK, that makes more sense. Yes, I guess it is not a big effort to create such a glossary. I'll make a first version soon!

**Comment by CNugteren** [comment]
A first version of the glossary is now available. I'll add more info later, e.g. on batched routines.
https://github.com/CNugteren/CLBlast/blob/master/doc/glossary.md
