### ISSUE TITLE
[Question] SGEMM with M as 1 too slow compared to clBLAS

### ISSUE THREAD

**Issue by sivagnanamn** [CNugteren/CLBlast#264]
SGEMM with size M 1, N 1029, K 12544 (a_buffer - Transpose::kNo, b_buffer - Transpose::kYes) on Adreno 330.  
```
CLBlast - 177.31 ms
clBLAS - 26.1 ms
```
For other dimensions, CLBlast is 2x or 3x faster compared to clBLAS.

Is it possible to do Vector-Matrix multiplication in CLBlast? i.e vector size 12544, matrix size 12544x1029. I can use `Somatcopy ` to transpose from 1029x12544 to 12544x1029.

 I checked the API's, but couldn't find any such implementation.

**Comment by CNugteren** [comment]
What about GEMV, or is that not what you mean?

**Comment by sivagnanamn** [comment]
Yes, I meant GEMV. 

In my first attempt, I didn't pass the parameters as per the API order. Got it working now 👍 

Note: But clblas gemv is 4x faster than CLBlast gemv (both on Adreno & tinkerboard).

It'll be easier, if GEMM autoswitches to GEMV if one of the matrix dimensions are 1D.

**Comment by CNugteren** [comment]
Yes, you are right. I'll put that on my to-do list.
