### ISSUE TITLE
Getting "CLBlast: OpenCL error: clEnqueueNDRangeKernel: -54"

### ISSUE THREAD

**Issue by romix** [CNugteren/CLBlast#271]
Hi,

I'm trying to use CLBlast to speedup GEMMs in my project.

I replaced the call to my custom kernel by the call of CLBlastGemm as shown below:

```c++
CLBlastSgemm(CLBlastLayoutRowMajor, CLBlastTransposeNo, CLBlastTransposeNo,
             m, n, k,
             alpha,
             a, 0, a_ld,
             b, 0, b_ld,
             beta,
             c, 0, c_ld,
             &commands_queue, nullptr);
```

The dimensions are: m = 3 n = 1000 k = 2048

But now I get the following error:
```
CLBlast: OpenCL error: clEnqueueNDRangeKernel: -54
```

As far as I can see, it is a code for CL_INVALID_WORK_GROUP_SIZE. CLBlastSgemm does not take any workgroup related parameters, so I guess CLBlastSgemm makes certain assumptions about the workgroup related parameters or sets them internally. It is not quite clear to me how I can influence or adjust them to get rid of this issue.

Could you provide any hints for solving this issue?

**Comment by romix** [comment]
After reading a bit more, I suspect that I have to use the OverrideParameters API. It is still not clear to me how I'm supposed to use it though.

Let's say that any run of my project uses a finite, relatively small set of m,n,k combinations for GEMMs. Do I need to invoke override parameters for each such combination? Which parameters should I provide and tweak? Are there any formulas for that? May be I have to use the auto-tuner? If so, how am I supposed to use it?

**Comment by CNugteren** [comment]
Indeed, CLBlast makes assumptions about the work group size for devices it hasn't seen before. To solve that, you will need to run the tuner for your device, as described [here](https://github.com/CNugteren/CLBlast/blob/master/doc/tuning.md).

However, most probably something is wrong or you have a quite weird OpenCL device. Why? Because CLBlast is tuned for many devices already and has defaults per vendor and overall computes as the fastest configuration that was valid across all devices. So if you have a device of a vendor unseen so far it means that your device doesn't support a configuration that was valid on all other seen devices. So I would like to investigate :-) Could you tell me your device / platform? Or perhaps run `clinfo` or `clblast_test_diagnostics` (if you have the tests compiled)?

**Comment by romix** [comment]
It is just a standard MacBook Pro (15-inch, 2017).
Processor: 3.1 GHz Intel Core i7
Graphics: Radeon Pro 555 2 GB
                  Intel HD Graphics 630 1536 MB

```
./clblast_test_diagnostics -device 0 -platform 0

* Options given/available:
    -platform 0 [=default]
    -device 0 [=default]


 --- OpenCL device naming:
* Device type                   CPU
* Device name                   Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
* Platform vendor               Apple
* Platform version              OpenCL 1.2 (Oct 31 2017 18:30:00)

 --- CLBlast device naming:
* Device type                   CPU
* Device name                   Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
* Device vendor                 Intel
* Device architecture

 --- OpenCL device properties:
* Max work group size           1024
* Max work item dimensions      3
* - Max work item size #0       1024
* - Max work item size #1       1
* - Max work item size #2       1
* Local memory size             32768KB
* Extensions:
cl_APPLE_SetMemObjectDestructor cl_APPLE_ContextLoggingFunctions cl_APPLE_clut cl_APPLE_query_kernel_names cl_APPLE_gl_sharing cl_khr_gl_event cl_khr_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_image2d_from_buffer cl_APPLE_fp64_basic_ops cl_APPLE_fixed_alpha_channel_orders cl_APPLE_biased_fixed_point_image_formats cl_APPLE_command_queue_priority

 --- Some OpenCL library benchmarks (functions from clpp11.h):
* queue.GetContext()            0.0004 ms
* queue.GetDevice()             0.0002 ms
* device.Name()                 0.0003 ms
* device.Vendor()               0.0001 ms
* device.Version()              0.0001 ms
* device.Platform()             0.0001 ms
* Buffer<float>(context, 1024)  0.0032 ms
```

```
./clblast_test_diagnostics -device 1 -platform 0

* Options given/available:
    -platform 0 [=default]
    -device 1


 --- OpenCL device naming:
* Device type                   GPU
* Device name                   Intel(R) HD Graphics 630
* Platform vendor               Apple
* Platform version              OpenCL 1.2 (Oct 31 2017 18:30:00)

 --- CLBlast device naming:
* Device type                   GPU
* Device name                   Intel(R) HD Graphics 630
* Device vendor                 Intel Inc.
* Device architecture

 --- OpenCL device properties:
* Max work group size           256
* Max work item dimensions      3
* - Max work item size #0       256
* - Max work item size #1       256
* - Max work item size #2       256
* Local memory size             65536KB
* Extensions:
cl_APPLE_SetMemObjectDestructor cl_APPLE_ContextLoggingFunctions cl_APPLE_clut cl_APPLE_query_kernel_names cl_APPLE_gl_sharing cl_khr_gl_event cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_image2d_from_buffer cl_khr_gl_depth_images cl_khr_depth_images cl_khr_3d_image_writes

 --- Some OpenCL library benchmarks (functions from clpp11.h):
* queue.GetContext()            0.0004 ms
* queue.GetDevice()             0.0002 ms
* device.Name()                 0.0003 ms
* device.Vendor()               0.0002 ms
* device.Version()              0.0002 ms
* device.Platform()             0.0001 ms
* Buffer<float>(context, 1024)  0.0049 ms
```

```
./clblast_test_diagnostics -device 2 -platform 0

* Options given/available:
    -platform 0 [=default]
    -device 2


 --- OpenCL device naming:
* Device type                   GPU
* Device name                   AMD Radeon Pro 555 Compute Engine
* Platform vendor               Apple
* Platform version              OpenCL 1.2 (Oct 31 2017 18:30:00)

 --- CLBlast device naming:
* Device type                   GPU
* Device name                   AMD Radeon Pro 555 Compute Engine
* Device vendor                 AMD
* Device architecture

 --- OpenCL device properties:
* Max work group size           256
* Max work item dimensions      3
* - Max work item size #0       256
* - Max work item size #1       256
* - Max work item size #2       256
* Local memory size             32768KB
* Extensions:
cl_APPLE_SetMemObjectDestructor cl_APPLE_ContextLoggingFunctions cl_APPLE_clut cl_APPLE_query_kernel_names cl_APPLE_gl_sharing cl_khr_gl_event cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_image2d_from_buffer cl_khr_depth_images cl_APPLE_command_queue_priority cl_APPLE_command_queue_select_compute_units cl_khr_fp64

 --- Some OpenCL library benchmarks (functions from clpp11.h):
* queue.GetContext()            0.0004 ms
* queue.GetDevice()             0.0002 ms
* device.Name()                 0.0003 ms
* device.Vendor()               0.0002 ms
* device.Version()              0.0002 ms
* device.Platform()             0.0001 ms
* Buffer<float>(context, 1024)  0.0047 ms
```

So, I guess it should work out of the box.

**Comment by romix** [comment]
I also noticed that when I try to tune gemms sometimes the tuner would fail, e.g.:

```
/clblast_tuner_xgemm --precision 32 --device 1 --platform 0 -beta 0 -m 10 -n 500 -k 800 -alpha 1
* Options given/available:
    -platform 0 [=default]
    -device 1
    -precision 32 (single) [=default]
    -m 10
    -n 500
    -k 800
    -alpha 1.00
    -beta 0.00
    -fraction 1.00 [=default]
    -runs 2 [=default]
    -max_l2_norm 0.00 [=default]

* Found 578 configuration(s)
* Parameters explored: MWG NWG KWG MDIMC NDIMC MDIMA NDIMB KWI VWM VWN STRM STRN SA SB

|   ID | total |                                                                 param |       compiles |         time | GFLOPS |            status |
x------x-------x-----------------------------------------------------------------------x----------------x--------------x--------x-------------------x
|  ref |     - |                                                                     - |             OK |  error -54   |      - |* Exception caught with status -2040 while running the reference, aborting
* Options given/available:
    -platform 0 [=default]
    -device 1
    -precision 32 (single) [=default]
    -m 10
    -n 500
    -k 800
    -alpha 1.00
    -beta 0.00
    -fraction 512.00 [=default]
    -runs 2 [=default]
    -max_l2_norm 0.00 [=default]

* Found 120800 configuration(s)
* Exploring a random subset of 235 configuration(s)
* Parameters explored: MWG NWG KWG MDIMC NDIMC MDIMA NDIMB KWI VWM VWN STRM STRN SA SB

|   ID | total |                                                                 param |       compiles |         time | GFLOPS |            status |
x------x-------x-----------------------------------------------------------------------x----------------x--------------x--------x-------------------x
|  ref |     - |                                                                     - |             OK |  error -54   |      - |* Exception caught with status -2040 while running the reference, aborting
```

**Comment by CNugteren** [comment]
Ah, you are running with Apple's OpenCL CPU implementation, that's a bit of a weird beast. Try running on one of your GPUs.

**Comment by romix** [comment]
> As for the tuning you are trying, that's with non-default m/n/k, try with the default ones. I still need to make a check to use a valid m/n/k size, because there are certain assumptions.

Yes, it works with default settings.

But I thought that the whole idea of tuning was to some extent to prepare for non-default unusual settings as well. How can I tune it if it just fails for certain dimensions? 

More generally, should GEMM routines work with any provided dimensions? I understand that they may be slow without tuning, but should they work or would they fail for some "unusual" dimensions?

**Comment by CNugteren** [comment]
You can inspect the source code by using e.g. `printf("\n%s\n", kernel_string.c_str());` at line 90 of `/src/utilities/compile.cpp`.

However, I suggest to first run the official tests on your devices and report the results here (e.g. `./clblast_test_xgemm -device X`). Then, for those with failing tests, run the relevant tuners with their default values ([see here](https://github.com/CNugteren/CLBlast/blob/master/doc/tuning.md#which-kernels-are-used-for-which-routines)), and re-run the tests with the new tuning results.

**Comment by opti-mix** [comment]
I suspect I found something that could be the reason for my problems. The framework that I use has the following memory allocation strategy. It computes the sizes of all tensors that are going to be used by the computations and then it adds them together to get the total memory size needed and allocates a single OpenCL buffer of that total size. The tensors are then represented as sub-ranges of this huge buffer.

I suspect that allocating memory this way may conflict with some alignment assumptions made by CLBlast or OpenCL.

Do you think that CLBlast should work just fine even in this case or do I need to be careful with alignments? If so, what are the requirements?

**Comment by romix** [comment]
I suspect I found something that could be the reason for my problems. The framework that I use has the following memory allocation strategy. It computes the sizes of all tensors that are going to be used by the computations and then it adds them together to get the total memory size needed and allocates a single OpenCL buffer of that total size. The tensors are then represented as sub-ranges of this huge buffer.

I suspect that allocating memory this way may conflict with some alignment assumptions made by CLBlast or OpenCL.

Do you think that CLBlast should work just fine even in this case or do I need to be careful with alignments? If so, what are the requirements?

**Comment by romix** [comment]
I found a bug in my code. I was passing incorrect parameters to sgemm. Sorry for the noise!
