### ISSUE TITLE
[Question] CLBlast in YOCTO 

### ISSUE THREAD

**Issue by sivagnanamn** [CNugteren/CLBlast#272]
Has anyone tried installing CLBlast using YOCTO linux project? I would like to install CLBlast in Asus Tinkerboard using YOCTO project. Any pointers would be helpful.

**Comment by sivagnanamn** [comment]
Sorry for the late response. 

I spent some time with yocto and could build CLBlast using [https://github.com/CogentEmbedded/meta-opencl/tree/master/meta-ocl-common/recipes-graphics/clblast](https://github.com/CogentEmbedded/meta-opencl/tree/master/meta-ocl-common/recipes-graphics/clblast) as reference.

I installed with tuners & clients. Running the tuner with default size (1024x1024 * 1024x1024) works, but could tune for custom matrix sizes throws error.

```
/ # clblast_tuner_xgemm -m 64 -n 64 -k 64
* Options given/available:
    -platform 0 [=default]
    -device 0 [=default]
    -precision 32 (single) [=default]
    -m 64 
    -n 64 
    -k 64 
    -alpha 2.00 [=default]
    -beta 2.00 [=default]
    -fraction 1.00 [=default]
    -runs 2 [=default]
    -max_l2_norm 0.00 [=default]

Aborted (core dumped)
```

Not sure whether this is because of Yocto build or CLBlast.

**Comment by CNugteren** [comment]
Not sure what is wrong. What about 128/128/128? What about the other tuners? And do the tests work fine?

**Comment by sivagnanamn** [comment]
SGEMM Tuning with 128/128/128 gets core dumped exactly at 210th configuration check.

```
|  208 |   578 |   32   32   32   32   16   32   16    2    1    2    0    0    1    1 |   OK    203 ms |      3.40 ms |    1.2 |     results match |
|  209 |   578 |   32   32   32   32   32   32   32    2    1    1    0    0    0    0 |   OK    175 ms |      5.00 ms |    0.8 |     results match |
|  210 |   578 |   32   32   32   32   32   32   32    2    1    1    0    0    1    1 |Aborted (core dumped)
```

Other tuners also behave in the same way (gets core dumped after checking few configurations). Eventhough I compiled with `-DTUNERS=ON -DCLIENTS=ON -DTESTS=ON` , couldn't find the test executables in the yocto image (only tuners & clients are available).

**Comment by CNugteren** [comment]
What OpenCL are you using? Which device? Maybe a driver issue?

About the tests not being compiled: you need to install a reference CPU BLAS library or otherwise clBLAS. See documentation.

**Comment by sivagnanamn** [comment]
The results posted above are using OpenCL 2.0 in Adreno 506. Initially I planned to use Tinkerboard but couldn't.

`About the tests not being compiled: you need to install a reference CPU BLAS library or otherwise clBLAS. See documentation.`
Thanks, I saw that after posting the comment. I've installed clBLAS, haven't built CLBlast after that.

**Comment by sivagnanamn** [comment]
The Yocto build I tried is with an ReadOnly file system. Before starting the tuner, is CLBlast trying to create any file (json file may be) ?  Can that be the reason for the core dump?

**Comment by CNugteren** [comment]
I just checked the code and the only place in the whole of CLBlast where `fopen` is used is [here](https://github.com/CNugteren/CLBlast/blob/master/src/tuning/tuning.cpp#L35), which is in a function called at the end of tuning. So no, I don't believe other files are being created.

The fact that it happens while tuning might well indicate one of the kernels it is trying to run is either wrong or not handled properly by your compiler/runtime. Given that other platforms work, I would suggest the latter.

Given the parameters it crashes for, you can try to disable that case (and some others) by changing the set of parameters [here](https://github.com/CNugteren/CLBlast/blob/master/src/tuning/kernels/xgemm.hpp#L76). E.g. set SA and SB to 0 always or remove 32 for MDIMC and similar parameters.

**Comment by sivagnanamn** [comment]
JFYI, sharing few updates. I'll spend some more time on this to find the root cause.

As you've mentioned, Its not because of fopen. I havent removed the failing case yet. 

However, I did one more experiment by compiling CLBlast for 32bit architecture using Yocto.

**64bit:**
- Tuner gets killed after few tests.
- Clients work for default M,N,K setting

**32bit:**
- Tuner gets killed without running any tests
- Clients also gets killed

**32 bit tuner:**
```
/ # clblast_tuner_xgemm
* Options given/available:
    -platform 0 [=default]
    -device 0 [=default]
    -precision 32 (single) [=default]
    -m 1024 [=default]
    -n 1024 [=default]
    -k 1024 [=default]
    -alpha 2.00 [=default]
    -beta 2.00 [=default]
    -fraction 1.00 [=default]
    -runs 2 [=default]
    -max_l2_norm 0.00 [=default]

*** Error in `clblast_tuner_xgemm': free(): invalid pointer: 0x41d09048 ***
Aborted (core dumped)
```
**32-bit client:**
```

# clblast_client_xgemm

* Options given/available:
    -m 512 [=default]
    -n 512 [=default]
    -k 512 [=default]
    -layout 101 (row-major) [=default]
    -transA 111 (regular) [=default]
    -transB 111 (regular) [=default]
    -lda 512 [=default]
    -ldb 512 [=default]
    -ldc 512 [=default]
    -offa 0 [=default]
    -offb 0 [=default]
    -offc 0 [=default]
    -alpha 2.00 [=default]
    -beta 2.00 [=default]
    -platform 0 [=default]
    -device 0 [=default]
    -precision 32 (single) [=default]
    -clblas 1 [=default]
    -step 1 [=default]
    -num_steps 0 [=default]
    -runs 10 [=default]
    -h [false]
    -q [false]
    -no_abbrv [false]
    -warm_up [false]
    -tuner_files <none> [=default]

*** Error in `clblast_client_xgemm': free(): invalid pointer: 0x41d09048 ***
Aborted (core dumped)
```

**Comment by CNugteren** [comment]
Have you used a debugger (e.g. gdb) to get some more details?

**Comment by sivagnanamn** [comment]
@CNugteren Apologies for the late response. 

I couldn't find time for working on this, I'll close this issue for now (will reopen later if required).
