### ISSUE TITLE
Shall we tune GEMM with FP16?

### ISSUE THREAD

**Issue by liyancas** [CNugteren/CLBlast#281]
./clblast_tuner_xgemm --precision 16 --device 0 --platform 0
* Options given/available:
    -platform 0 [=default]
    -device 0 [=default]
    -precision 16 (half)
    -m 1024 [=default]
    -n 1024 [=default]
    -k 1024 [=default]
    -alpha 2.000000 [=default]
    -beta 2.000000 [=default]
    -fraction 1.00 [=default]
    -runs 2 [=default]
    -max_l2_norm 0.00 [=default]

* Unsupported precision, skipping this tuning run

* Options given/available:
    -platform 0 [=default]
    -device 0 [=default]
    -precision 16 (half)
    -m 1024 [=default]
    -n 1024 [=default]
    -k 1024 [=default]
    -alpha 2.000000 [=default]
    -beta 2.000000 [=default]
    -fraction 512.00 [=default]
    -runs 2 [=default]
    -max_l2_norm 0.00 [=default]

* Unsupported precision, skipping this tuning run

* Options given/available:
    -platform 0 [=default]
    -device 0 [=default]
    -precision 16 (half)
    -m 1024 [=default]
    -n 1024 [=default]
    -k 1024 [=default]
    -alpha 2.000000 [=default]
    -beta 2.000000 [=default]
    -fraction 1.00 [=default]
    -runs 2 [=default]
    -max_l2_norm 0.00 [=default]

* Unsupported precision, skipping this tuning run

* Options given/available:
    -platform 0 [=default]
    -device 0 [=default]
    -precision 16 (half)
    -m 1024 [=default]
    -n 1024 [=default]
    -k 1024 [=default]
    -alpha 2.000000 [=default]
    -beta 2.000000 [=default]
    -fraction 128.00 [=default]
    -runs 2 [=default]
    -max_l2_norm 0.00 [=default]

* Unsupported precision, skipping this tuning run

**Comment by CNugteren** [comment]
CLBlast is already tuned for FP16 for some devices. The message `Unsupported precision` means that FP16 is unsupported on your device, not that it is not supported by CLBlast's tuner or something. What device are you on?

**Comment by liyancas** [comment]
Many thanks. The device is GeForce GTX 760.

**Comment by liyancas** [comment]
There are two execution files (clblast_tuner_xgemm vs. clblast_tuner_xgemm_direct) after I build.
What're the differences between them?

**Comment by CNugteren** [comment]
That device indeed doesn't support FP16. You'll need a P100 or V100 if you want to stick to NVIDIA.

About the other question: there are two forms of kernels for GEMM, both need to be tuned. See also the table [here](https://github.com/CNugteren/CLBlast/blob/master/doc/tuning.md#which-kernels-are-used-for-which-routines).

**Comment by liyancas** [comment]
Thanks a lot.  Another issue about how to tune gemm.  I change the file tuning_api.cpp, and it shows  "CLBlast: Run-time error: -2041". I don't know what's the reason.
------------------------------
// Example arguments
  const size_t m = 64;
  const size_t n = 64;
  const size_t k = 64;
  const auto fraction = 0.01; // between 0.0 and 1.0
  -----
  auto queue_plain = queue();
  auto status = clblast::TuneXgemmDirect<float>(&queue_plain, m, n, k, fraction, parameters);
  for (const auto parameter: parameters) {
    printf(">  %s = %zu\n", parameter.first.c_str(), parameter.second);
  }

  // Set the new parameters
  auto st = clblast::OverrideParameters(device(), "GEMM", clblast::Precision::kSingle, parameters);
  printf("Completed OverrideParameters with status %d (0 == OK)\n", static_cast<int>(st));
  return 0;

-----

The log is shown as follows:

Starting the tuning...
>  VWND = 1
>  PADB = 1
>  NDIMCD = 32
>  WGD = 32
>  KWID = 2
>  VWMD = 1
>  MDIMAD = 16
>  NDIMBD = 16
>  PADA = 1
>  MDIMCD = 8
CLBlast: Run-time error: -2041
Completed OverrideParameters with status -2041 (0 == OK)

**Comment by liyancas** [comment]
The GEMM function returns -54 on my Android platform, and I tried to generate a set of optimized runnable parameters for it.

**Comment by CNugteren** [comment]
I'll be closing this now as it is getting a bit messy, the original issue is solved. Please open a new issue with a clear description of your hardware/software and problem and what you have already tried (e.g. run the tuners).
