### ISSUE TITLE
ARM Mali GPU no need GlocalToLocal*  and LocalToPrivate* API

### ISSUE THREAD

**Issue by haolongzhangm** [CNugteren/CLBlast#288]
As desktoptop and qcom Adreno GPU has real Local mem or private mem, which is more fast that global
mem, at this sence, use GlocalToLocal*  and LocalToPrivate* API will speed up calculate！
But, as we know ARM Mali GPU implement Local and private mem from Global mem, so use GlocalToLocal*  and LocalToPrivate* API  will do not good for speedup, to the contrary will be slow calculate, caused by GlocalToLocal*  and LocalToPrivate* API will be swith to GlobalToGlobal,

so any possible add a config to user enable/disable GlocalToLocal*  and LocalToPrivate* API

ps: At other side , also I test on Qcom Adreno 510 and 506 GPU, try to disable LocalToPrivate API  also
will be be more fast ,about 1.8X speed up

**Comment by haolongzhangm** [comment]
arm info: 
http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.100614_0303_00_en/ada1432742771415.html

**Comment by CNugteren** [comment]
Thanks for your input. However, this is not an issue: the GEMM kernel is tunable and there are configurations that do not use the local memory. Thus, if it is indeed the case that local memory is not useful, the tuner will automatically find it :-)

**Comment by haolongzhangm** [comment]
Dear CNugteren
Do not understand the "the GEMM kernel is tunable and there are configurations that do not use the local memory"?

eg api :gemm , we can find two possible API GemmDirect and GemmIndirect
GemmDirect will maps to XgemmDirect in xgemm_direct_part3.opencl
GemmIndirect will maps to XgemmBody in xgemm_part3.opencl
both of the two API will use GlocalToLocal , LocalToPrivate or GlocalToPirvate in the kernel code

**Comment by CNugteren** [comment]
Yes, they both do. But there are tuning parameters that will disable/enable parts of the code. In this particular case, the parameters `SA` and `SB` should take care of that. If you look closely, you'll see the parts related to local memory in e.g. an `#if SA == 1` block.

**Comment by CNugteren** [comment]
OK, let me correct my earlier remark and give a bit more details. There are indeed two kernels, the direct and the in-direct kernel. The in-direct kernel is typically the fastest, especially for larger GPUs and for larger matrix sizes.

The in-direct kernel has `SA` and `SB` as tuning parameters to enable/disable usage of the local memory ('shared') for matrix A or for matrix B loading, e.g. [here](https://github.com/CNugteren/CLBlast/blob/master/src/kernels/level3/xgemm_part3.opencl#L78). Thus, if the local memory is slow, the tuner will find fast kernels only with SA = 0 and SB = 0. I don't see a problem in this case.

The direct kernel doesn't have these tuning options and always uses local memory indeed. It does make sense to add this as a tuning parameter. What needs to be done is: 1) change the kernel with this part enabled/disabled, 2) change the tuner to include this parameter, and 3) update the current tuning database parameter with the current values set.

If you tell me which parts exactly you disabled to get that speed-up, that might help me. But all in all I don't think this is a big task, but it is quite important indeed. I'll start working on it soon.

**Comment by haolongzhangm** [comment]
Dear CNugteren
Thanks for update.
1: as U said, In-direct  kernel always good for larger GPU and larger matrx sizes, But for mobile GPU, eg mali and Adreno GPU, they are alwayes small GPU , after I tune the mobile GPU, I can see gemm always into direct gemm when do like deep learning task, so for mobile deep learining case, need add more tuneing param for direct kernel for disable use local and private(or register apd/bpd/cpd), for  apd/bpd/cpd , for mobile GPU do not support #prama promote_to_registers

2:about "if you tell me which parts exactly you disabled to get that speed-up" , let me correct my old commit,  I just find the GlobalToLocal and GlobalToPrivate will  API will take so much time, about 30% about all the time, 
eg:  I remove apd/bpd , and GlobalToPrivate GlobalToLocal  LocalToPriaveAPI , then MutilplyAdd modify to
MutilplyAdd(cpd[...],  alm or agms, blm or bgms), then will find 1.8x speed up in qcom adreno GPU510
(do not care about result , just for test), why GlobalToPrivate GlobalToLocal  LocalToPriaveAPI API take so much time in all the direct kernel

3:ps another query for " In-direct  kernel always good for larger GPU and larger matrx sizes", , I see u check-out a branch named 'adreno_tryout', then I test this branch for gemm, find two issue:
a: the result is err
b: the speed is so low than the master branch(both banch after tuning for adreno 510), I can see adreno_tryout gemm always use Indirect kernel, But really at most case, mobile GPU is small gpu , use
Indirect kernel will slow than direct kernel at most case, so any plan update the adreno_tryout branch?

**Comment by CNugteren** [comment]
Let me first answer to your questions:

1a. About: __for mobile deep learining case, need add more tuneing param__: Indeed, I agree. I'll work on the direct GEMM kernel a bit more. I'll add parameters to disable the local memory.

1b. About: __do not support #prama promote_to_registers__: That's a CLBlast internal thing: CLBlast includes an optional "pre-processor" which promotes small arrays to registers for compilers that don't support that themselves. So far it is only enabled for ARM Mali devices. Does the Qualcomm compiler also has this limitation? If so, we can test with the pre-processor enabled.

2a. I don't follow your explanation 100%, perhaps a [gist](gist.github.com) of the diff could help?

2b. About: __why GlobalToPrivate GlobalToLocal LocalToPriaveAPI API take so much time in all the direct kernel__: These functions load the data, so yes, removing that is going to take up a lot of time.

3 About the __adreno_tryout__ branch: Please read more in the [relevant issue](https://github.com/CNugteren/CLBlast/issues/228#issuecomment-353786474). In short: it is one specific test kernel only. Yes, errors are expected in case you don't use it properly. And yes, speed might be worse. This was just a tryout, not much more.

I'll keep this updated when I have more tuning parameters implemented.

**Comment by CNugteren** [comment]
Actually, I have just implemented a super simple version in the `CLBlast-288-local-memory-optional-for-direct-GEMM` branch. It adds the SA and SB parameters to the direct GEMM kernel which can be both `1` (behaviour like before) or `0` (disable any local memory completely). It is naive in the sense that there can perhaps be things optimised in the SA == SB == 0 case. But you can already play with it if you want by running the tuner `./clblast_tuner_xgemm_direct`. Let me know what your findings are.

**Comment by haolongzhangm** [comment]
so thanks for u update 
about 1b: yes I can see warning about "do not support #prama promote_to_registers" on adreno GPU
about the CLBlast-288-local-memory-optional-for-direct-GEMM branch I will test it

**Comment by CNugteren** [comment]
About 1b: As I said, the fact that your compiler outputs a warning is completely normal, it is a CLBlast internal thing. What I'm asking is whether the Qualcomm compiler is able to promote the small constant-sized arrays to registers, but I think it is (almost all compilers are capable enough).

**Comment by haolongzhangm** [comment]
about 1b , get u idea

CLBlast-288-local-memory-optional-for-direct-GEMM 
command:  python database.py  tuner_result_for_1a3cfe80/ ../../  
will raise a err:

[database] Loading database from '../../scripts/database/database.json'
[database] Processing 'tuner_result_for_1a3cfe80/clblast_xgemv_fast_rot_32.json' with 68 new items
[database] Processing 'tuner_result_for_1a3cfe80/clblast_pad_32.json' with 81 new items
[database] Processing 'tuner_result_for_1a3cfe80/clblast_xgemm_11_32.json' with 395 new items
[database] Processing 'tuner_result_for_1a3cfe80/clblast_gemm_routine_32.json' with 31 new items
[database] Processing 'tuner_result_for_1a3cfe80/clblast_xdot_1_32.json' with 5 new items
[database] Processing 'tuner_result_for_1a3cfe80/clblast_xgemm_direct_1_32.json' with 87 new items
[database] Processing 'tuner_result_for_1a3cfe80/clblast_xgemv_fast_32.json' with 30 new items
[database] Processing 'tuner_result_for_1a3cfe80/clblast_xgemv_32.json' with 12 new items
[database] Processing 'tuner_result_for_1a3cfe80/clblast_xaxpy_32.json' with 80 new items
[database] Processing 'tuner_result_for_1a3cfe80/clblast_xgemm_12_32.json' with 122 new items
[database] Processing 'tuner_result_for_1a3cfe80/clblast_padtranspose_32.json' with 14 new items
[database] Processing 'tuner_result_for_1a3cfe80/clblast_invert_32.json' with 2 new items
[database] Processing 'tuner_result_for_1a3cfe80/clblast_routine_xtrsv_32.json' with 4 new items
[database] Processing 'tuner_result_for_1a3cfe80/clblast_xgemm_2_32.json' with 215 new items
[database] Processing 'tuner_result_for_1a3cfe80/clblast_xdot_2_32.json' with 5 new items
[database] Processing 'tuner_result_for_1a3cfe80/clblast_transpose_32.json' with 24 new items
[database] Processing 'tuner_result_for_1a3cfe80/clblast_xger_32.json' with 132 new items
[database] Processing 'tuner_result_for_1a3cfe80/clblast_xgemm_1_32.json' with 531 new items
[database] Processing 'tuner_result_for_1a3cfe80/clblast_copy_32.json' with 144 new items
[database] Processing 'tuner_result_for_1a3cfe80/clblast_xgemm_direct_2_32.json' with 112 new items
[database] Saving database to '../../scripts/database/database.json'
[database] Calculating the best results per device/kernel...
[database] Calculating the default values...
[database] Warning: No common kernels for: QUALCOMM;GPU;32;xgemm_direct;XgemmDirectTN;256;256;256;2.000000;2.000000 at all
[database] Producing a C++ database in '../../src/database/kernels'...
[database] No results found for trsv_routine:16, retrieving defaults from trsv_routine:32
[database] No results found for trsv_routine:64, retrieving defaults from trsv_routine:32
[database] No results found for trsv_routine:6464, retrieving defaults from trsv_routine:32
Traceback (most recent call last):
  File "database.py", line 185, in <module>
    main(sys.argv[1:])
  File "database.py", line 179, in main
    clblast.print_cpp_database(database_best_results, cpp_database_path)
  File "/media/zhl/second/code/caffe-android-lib/CLBlast/scripts/database/database/clblast.py", line 231, in print_cpp_database
    assert parameter_name == parameter_names[parameter_index]
AssertionError

**Comment by haolongzhangm** [comment]
But on adreno devices , clblast_xgemm_direct_1_32.json show will use local 
best_parameters": "KWID=2 MDIMAD=16 MDIMCD=16 NDIMBD=8 NDIMCD=8 PADA=1 PADB=1 PRECISION=32 SA=1 SB=1 VWMD=2 VWND=4 WGD=32"

I will test on a mali device, then  update

**Comment by haolongzhangm** [comment]
test on MTK6750 with MALI Mali T860@mp2

clblast_xgemm_direct_1_32.json  show do not use local mem
"best_parameters": "KWID=2 MDIMAD=16 MDIMCD=16 NDIMBD=8 NDIMCD=8 PADA=1 PADB=1 PRECISION=32 SA=0 SB=0 VWMD=2 VWND=1 WGD=32",

**Comment by haolongzhangm** [comment]
so It will be use for mali gpu add SA/SB at xgemm_direct

**Comment by CNugteren** [comment]
Any updates from your side? I'm waiting for the results as requested above before I can make a decision if I should make this a real feature of CLBlast.

**Comment by CNugteren** [comment]
Is this still relevant for you? I'll close this issue for now since there is no response, feel free to re-open it (and fill in the above table) if you think it is still an issue.
