### ISSUE TITLE
Using Cuda Gemm

### ISSUE THREAD

**Issue by abhi1212** [CNugteren/CLBlast#289]
Hello,
I just want to use Cuda Gemm frfom the CLBlast Library.
When I directly compile and run the sgemm_cuda.cpp fdrom the samples folder.
I get an error stating 
4_sgemm_cuda.o: In function `main':
sgemm_cuda.cpp:(.text+0x368): undefined reference to `clblast::StatusCode clblast::Gemm<float>(clblast::Layout, clblast::Transpose, clblast::Transpose, unsigned long, unsigned long, unsigned long, float, 

Can someone please help?
@CNugteren

**Comment by CNugteren** [comment]
Have you compiled the library with CUDA? And have you linked to it. See the installation instructions, that will also tell you how to compile and link the samples.

**Comment by abhi1212** [comment]
Hello ,
I was able to run it, I forgot to add the -lclblast flag while compiling.
Thanks for the help @CNugteren
