### ISSUE TITLE
Segfaults using POCL on Debian Stretch

### ISSUE THREAD

**Issue by ranocha** [CNugteren/CLBlast#293]
As described in #291, all tests pass using this configuration but `clblast_sample_cache_c` segfaults. Some of the tuners fail, too:
```
CLBlast/build$ ./clblast_tuner_transpose_fast -precision 32
* Options given/available:
    -platform 0 [=default]
    -device 0 [=default]
    -precision 32 (single) [=default]
    -m 1024 [=default]
    -n 1024 [=default]
    -alpha 2.00 [=default]
    -fraction 1.00 [=default]
    -runs 10 [=default]
    -max_l2_norm 0.00 [=default]

* Found 98 configuration(s)
* Parameters explored: TRA_DIM TRA_WPT TRA_PAD TRA_SHUFFLE 

|   ID | total |               param |       compiles |         time |   GB/s |            status |
x------x-------x---------------------x----------------x--------------x--------x-------------------x
|  ref |     - |                   - |             OK |      0.67 ms |      - |      reference OK |
x------x-------x---------------------x----------------x--------------x--------x-------------------x
|    1 |    98 |    4    1    0    0 |   OK     94 ms |      0.99 ms |    8.5 |     results match |
...
|   96 |    98 |   64    8    1    1 |   OK     76 ms |      3.02 ms |    2.8 |     results match |
Speicherzugriffsfehler
```
```
CLBlast/build$ ./clblast_tuner_transpose_fast -precision 6464
* Options given/available:
    -platform 0 [=default]
    -device 0 [=default]
    -precision 6464 (complex-double) 
    -m 1024 [=default]
    -n 1024 [=default]
    -alpha 2.00+0.50i [=default]
    -fraction 1.00 [=default]
    -runs 10 [=default]
    -max_l2_norm 0.00 [=default]

* Found 92 configuration(s)
* Parameters explored: TRA_DIM TRA_WPT TRA_PAD TRA_SHUFFLE 

|   ID | total |               param |       compiles |         time |   GB/s |            status |
x------x-------x---------------------x----------------x--------------x--------x-------------------x
|  ref |     - |                   - |             OK |      3.73 ms |      - |      reference OK |
x------x-------x---------------------x----------------x--------------x--------x-------------------x
|    1 |    92 |    4    1    0    0 |   OK    197 ms |      4.61 ms |    7.3 |     results match |
...
|   76 |    92 |   32    8    1    1 |   OK    203 ms |      9.80 ms |    3.4 |     results match |
Speicherzugriffsfehler
```

**Comment by CNugteren** [comment]
For completeness, here is the [clinfo](https://github.com/CNugteren/CLBlast/issues/291#issuecomment-400544489) output I presume.

I haven't tested with POCL yet, apparently there are some issues. I'll take a look soon.

**Comment by ranocha** [comment]
Yes, that's correct. Thank you for your work!

**Comment by ranocha** [comment]
The problem with `clblast_sample_cache_c` has been fixed by 49e06d20ab03e85da8ca5e5f70799621aee9f885. However, the are still problems with `clblast_tuner_transpose_fast` as described above.

**Comment by CNugteren** [comment]
OK, I installed POCL myself and indeed managed to reproduce the issue (Debian Linux + Intel CPU + POCL 0.13), although it segfaults at a different instance of the tuned kernel, but still within the double-complex transpose kernel.

What can I do? Not sure... I'm assuming the kernel is OK because it works everywhere else. So perhaps there POCL compiles an incorrect binary? What I did was made a small single-file reproducible examples, which I've made [into a gist here](https://gist.github.com/CNugteren/faf818cc0fac224da254ab2b77a04614). Perhaps you could run that code and see if it also segfaults for you in the same way? Not sure what to do after, file this as a bug for POCL?

**Comment by ranocha** [comment]
As discussed in https://github.com/pocl/pocl/issues/644, the issue may be due to a bug in the old version of LLVM. You can close this issue if you want.

**Comment by CNugteren** [comment]
I saw it, I'll make a note in the readme that it is necessary to upgrade pocl/LLVM if encountering such issues. Thanks for debugging.
