### ISSUE TITLE
The future of CLBlast

### ISSUE THREAD

**Issue by blueberry** [CNugteren/CLBlast#30]
Hi Cedric,

CLBlast is a great work! I also learned a lot from your blog posts about matrix multiplication.
I've noticed that CLBlast development stalled a bit in the last couple of months, after a period of rapid development.
Do you plan to develop/support it further, or is it on hold due to your other commitments?

**Comment by CNugteren** [comment]
Hi there, Thanks for your comment

**Comment by CNugteren** [comment]
Hi there,

Thanks for your comment! You are right that I haven't been as active as I used to be. Two health reasons: back-problems followed-by a dislocated shoulder. Shows the weakness of a one-man project. 

Anyway, I should be picking up development slowely again, so you can expect some updates soon. I plan to tune first for some more devices (and make the tuning easier to do and more automatic) and then later work on unsupported routines. Is there anything in particular you are waiting for?

**Comment by blueberry** [comment]
I am sorry to hear of those problems. Get well soon :)

Anyway, I am not in a hurry. CLBlast is great as it is for what I need, I just wanted to know whether to expect it to be even more complete and updated in the future.

Keep up with the great work!

**Comment by CNugteren** [comment]
Thanks!

New commits are slowly starting to come, so I am closing this issue now.
