### ISSUE TITLE
gemm-NN done by transpose kernel? 

### ISSUE THREAD

**Issue by tingxingdong** [CNugteren/CLBlast#302]
the "clblast_client_xgemm" default is a transA=T, transB=N, a TN case.  Most people care about NN case. When I test NN case 1024x1024x1024, I see it print out kernel "TransposeMatrixFast" for me. So besides, TN, the other transpose cases are all requires an explicit "transpose kernel" ?  Is this an overhead? If so, why it still achieves good performance even with this overhead?  I do not read it on your presentation slides or pdf paper. Thank you.

**Comment by tingxingdong** [comment]
Another thing is, "--run 1" does not work, it still launch 10 runs for me.

**Comment by tingxingdong** [comment]
Yet, for a NN 128x128x128. There is not "TranposeMatrixFast"

**Comment by CNugteren** [comment]
I believe all your questions are [answered in the docs](https://github.com/CNugteren/CLBlast/blob/master/doc/details_gemm.md). Indeed, for 128x128x128 it runs the direct kernel, for large kernels the overhead is indeed minimal.

About the `--run 1` question, the syntax is `--runs 1`.
