### ISSUE TITLE
File descriptor leak with beignet

### ISSUE THREAD

**Issue by vi** [CNugteren/CLBlast#307]
```
$ DISPLAY= ./matmul_clblast -a 5 -n 600
open("/dev/dri/card0", O_RDWR) failed: Too many open files
Device open failed, aborting...
```

Both from CLBlast's tests and from actual programs.

```
$ DISPLAY= strace -fe open ./matmul_clblast -a 5 -n 16 |& grep /dev/dri/renderD128 | tail 
open("/dev/dri/renderD128", O_RDWR)     = 257
open("/dev/dri/renderD128", O_RDWR)     = 257
open("/dev/dri/renderD128", O_RDWR)     = 257
open("/dev/dri/renderD128", O_RDWR)     = 258
open("/dev/dri/renderD128", O_RDWR)     = 258
open("/dev/dri/renderD128", O_RDWR)     = 258
open("/dev/dri/renderD128", O_RDWR)     = 258
open("/dev/dri/renderD128", O_RDWR)     = 258
open("/dev/dri/renderD128", O_RDWR)     = 258
open("/dev/dri/renderD128", O_RDWR)     = 258
```

In the example above [matmul](https://github.com/attractivechaos/matmul) calls `cblas_sdot` 16*16 times. I doubt it really warrant 256 separate independent connections to the GPU.

Split off from #231.

**Comment by vi** [comment]
According to backtraces, opening the new descriptor is caused by CLBlast's `clblast::Context::Context(clblast::Device const&)` and `get_device()` calling Beignet's `clCreateContext` or `cl_get_device_ids` respectively.

**Comment by CNugteren** [comment]
Sorry, I'm not really understanding a few things:
* What is this `matmul_clblast` program?
* What is the relationship to `cblas_sgemm` (regular CPU BLAS)?
* What is such a file descriptor for and when is it supposed to be created normally?

In any case, don't think it is a CLBlast issue, the only interface used is regular OpenCL C API, and if that is misused it should return an error code.

**Comment by vi** [comment]
CLBlast contains cblas-compatible mode. `matmul_clblast` is a maltul linked against clblast instead of usual cblas.

`cblas_sgemm` is another CLBlast-exported function. Looks like it can actually speeds up matrix multiplication my `matmul` compared to CPU mode (usually by a few seconds, only if matrix is large).

---

Are `get_device()` and `clCreateContext` functions supposed to be called often? For beignet they are very heavy-weight and do the initialization of the GPGPU.

**Comment by CNugteren** [comment]
OK, thanks for the explanation. The Netlib BLAS interface of CLBlast indeed has to create a new OpenCL platform/device/context/queue and so on every-time and has to copy back-and-forth (that's why it is not recommended for performance). If that causes an issue with Beignet then that's a Beignet issue I guess? Unless not everything is properly cleaned-up by CLBlast of course...

One thing you could hack in as a try-out is a call to `ClearCache()` at the end of the function of interest in `src/clblast_netlib_c.cpp` to see if the CLBlast cache is the issue perhaps?

**Comment by vi** [comment]
Why not just persist OpenCL state between calls (e.g. using a global variable)?

Clearing something may stop the leak, but make each function call carry performance penalty of searching and initializeing the OpenCL, not just the first call.

**Comment by CNugteren** [comment]
> Why not just persist OpenCL state between calls (e.g. using a global variable)?

Hmm well if you are going to call this function many times, I suggest you take a bit more effort and use the regular interface? This is really not meant for many repeated calls I suppose...

> Clearing something may stop the leak

I'm talking about the OpenCL program/kernel stored in a global cache variable, which is something different. Just wanted to check if that causes your issue perhaps?

> but make each function call carry performance penalty of searching and initializeing the OpenCL, not just the first call.

There are so many other performance penalties with this API as I argued above, not sure if this potentially marginally gain will outweigh the effort/added complexity?

**Comment by vi** [comment]
cblas-compatible API makes CLBlast a good idea not only for developers of programs, but also for advanced users of existing programs. I haven't tried, but maybe CLBlast can boost programs even without recompilation (LD_PRELOAD).

Using CLBlast API means locking a program to GPU mode (and in general bringing GPU concerns to a program that was previously CPU-only).

So speeding up netlib API may be worthy, even tough it can't be as fast as native API.

**Comment by vi** [comment]
```diff
diff --git a/src/clblast_netlib_c.cpp b/src/clblast_netlib_c.cpp
index 9ab663b..0a318b0 100644
--- a/src/clblast_netlib_c.cpp
+++ b/src/clblast_netlib_c.cpp
@@ -689,10 +689,12 @@ float cblas_sdot(const int n,
                                y_buffer(), 0, y_inc,
                                &queue_cl);
   if (s != clblast::StatusCode::kSuccess) {
+      clblast::ClearCache();
     throw std::runtime_error("CLBlast returned with error code " + clblast::ToString(s));
   }
   float dot[dot_size];
   dot_buffer.Read(queue, dot_size, reinterpret_cast<float*>(dot));
+  clblast::ClearCache();
   return dot[0];
 }
 double cblas_ddot(const int n,
```

Stops the leak.

**Comment by CNugteren** [comment]
OK, so Beignet keeps these things open for the OpenCL programs/kernels in the cache, so clearing the cache would solve it, but it would incur re-compilation overheads every-time.

Was it `abysmal` before this change as well? If not, then I suggest to leave the code as it is. What do you think?

**Comment by vi** [comment]
It wasn't "abysmal" (just "low") only with `static` hack [above](https://github.com/CNugteren/CLBlast/issues/307#issuecomment-409337666). Without any of the patches it fails before sensible measurement.

**Comment by CNugteren** [comment]
OK. So the `clblast::ClearCache()` could be called by the user if needed, so let's not add that to the functions. The static variable is effectively the same as making it global, right? Not sure if that is what users might want to have, since they might want to do other (non-OpenCL) things as well, don't think they would like to have OpenCL things freed-up af the very end of the program?

Anyway, I don't really see a solution to your problem other than using another OpenCL implementation without this file descriptors issue? Or just use the regular interface in this case, apparently the combination of Beignet and your use-case don't match with the API of the Netlib BLAS API of CLBlast?

**Comment by vi** [comment]
> The static variable is effectively the same as making it global, right?

Yes.

> don't think they would like to have OpenCL things freed-up af the very end of the program?

They should be freed up by operating system, like other open files.

---

The behaviour (to free up, to leave opened, or to use global var) can be a compilation `#ifdef` option.

**Comment by CNugteren** [comment]
OK, that I can do of course. I've just committed to the `CLBlast-307-netlib-api-static-opencl-vars` branch, there is now an option `NETLIB_STATIC_OPENCL` in CMake (e.g. `cmake -DNETLIB=ON -DNETLIB_STATIC_OPENCL=ON ..`) to make the OpenCL device and context static like in your patch above. Could you see if that is indeed what you need?

**Comment by vi** [comment]
Seems OK.

**Comment by CNugteren** [comment]
This is now merged in, `-DNETLIB_PERSISTENT_OPENCL=ON` is now a CMake option to resolve the issue with Beignet and the Netlib API.
