### ISSUE TITLE
Error tuning Hikey 960

### ISSUE THREAD

**Issue by jcanore** [CNugteren/CLBlast#317]
Hi, I'm trying to tune the library for the Hikey 960 board, and I get the following error when I run the tuner ./clblast_tuner_xgemm -precision 32:

[OpenCL pre-processor] Error in source line: const realN aval = apm[0 * (KREG/VWN) + _ki];
* Exception caught with status -2040 while running the reference, aborting 

Any ideas about the error and/or how to solve it? Thanks.

**Comment by CNugteren** [comment]
Could you try to comment out this line? https://github.com/CNugteren/CLBlast/blob/master/src/utilities/compile.cpp#L107

I'll investigate later what is going on, I'm currently on the move.

**Comment by jcanore** [comment]
Sure, many thanks.

**Comment by jcanore** [comment]
Now the tuner finishes, but after adding the generated JSON files to the database the execution times on the board are much worse. 

Am I doing anything wrong?

**Comment by jcanore** [comment]
Yes, after removing that line the execution time is 3.7x worse (14s vs 52s). 

Once the library is properly tuned I expect a much better time than 14s.

Ok, thanks Cedric.

**Comment by CNugteren** [comment]
I just merged in a fix, could you try again?

**Comment by jcanore** [comment]
Sure, many thanks. I'll try during the weekend.

**Comment by CNugteren** [comment]
Any updates from your side? Did it fix it?

**Comment by jcanore** [comment]
Sorry for the delay. Yes, the code works now, the problem I found is that some tests don't finish, but there are no errors. It seems that the problem is the Hikey board, when it gets too hot it stops working.

**Comment by CNugteren** [comment]
Ok thanks for trying out. This issue is then closed as I understand it.
