### ISSUE TITLE
cl_events are not set properly

### ISSUE THREAD

**Issue by gpu** [CNugteren/CLBlast#32]
The functions in CLBlast receive a pointer to  `cl_event` as their last parameter. This pointer is not properly filled during the actual kernel launches. 

(I tried to analyze the path that the given pointer takes through the actual CLBlast C++ infrastructure, before it actually ends in the [Launch function in clpp11.h](https://github.com/CNugteren/CLBlast/blob/4678fd371df2b928603d051666d5985ba507abe5/include/internal/clpp11.h#L573), but can not point out "the" line that causes this error. Somewhere, the `cl_event` pointer may be copied accidentally)

Steps to reproduce: In the https://github.com/CNugteren/CLBlast/blob/master/samples/sgemm.c sample, after the `CLBlastSgemm` call, change/extend the `clWaitForEvents` call as follows:

    printf("The event is %p\n", event);
    int result = clWaitForEvents(1, &event);
    printf("Result of waiting: %d\n", result);

This prints

    The event is 0000000000000000
    Result of waiting: -58

(where -58 is the CL error code for `CL_INVALID_EVENT`)

I'd expect the `cl_event` pointer that is passed to the API function to be properly filled with the pointer that was returned from the internal `clEnqueueNDRangeKernel` call.

**Note:** In most OpenCL functions and libraries, the `cl_event` is **optional**. This means that it should also be possible to pass a `nullptr` as the event parameter to the CLBlast functions. Currently, this is not possible (causes a nasty crash/segfault). I assume that this can be fixed together with this issue - otherwise, I'd open it as a dedicated RFE.

**Comment by CNugteren** [comment]
Indeed, thanks for pointing out this issue. I'll make sure the event is properly filled. Furthermore, I agree with your suggestion to make it an optional argument.You can expect to see an update to the development version within a week.

**Comment by CNugteren** [comment]
This is now fixed in the latest development branch. Could you let me know if everything works as expected? Also, the C interface allows `NULL` as an argument for the event and the C++ interface now has the event as an optional argument (defaults to `nullptr`).

**Comment by gpu** [comment]
As far as I tested it, it works as expected:

- In the SGEMM sample, the event is no longer NULL, and waiting does no longer cause an error
- The same applies when everything is routed though https://github.com/gpu/JOCLBlast , in a similar SGEMM sample
- Passing a "null" event to the SGEMM function did not cause a crash

(and, by the way, the declspecs also seem to be all right now).

**Comment by CNugteren** [comment]
Good to hear, thanks for testing!
