### ISSUE TITLE
Work around to avoid padding in Indirect GEMM

### ISSUE THREAD

**Issue by 9prady9** [CNugteren/CLBlast#333]
For certain large sizes, when Indirect GEMM approach is chosen by CLBlast for matmul, the padded size is becoming too huge. This is what I understood from CLBlast source, I may be wrong. The issue is originally reported on the downstream project ArrayFire, Issue https://github.com/arrayfire/arrayfire/issues/2341

I have built CLBlast using VERBOSE mode and the following is the temp size for input matrix size `400 x 1.1e6` on GTX 1060 with 3GB memory.
```
[DEBUG] GEMM_Copy_8_32_4_1_Pad_16_32_1_2_Transpose_8_0_0_4_Padtranspose_1_16_2_Xgemm_0_1_32_2_16_16_64_8_8_64_1_1_0_0_4_4_XgemmDirect_2_16_16_8_8_1_1_1_1_32_GemmRoutine_1664
[DEBUG] Compiling routine 'GEMM-32 (single)'
[DEBUG] Completed compilation in 92.56 ms
temp_size : 985800704
a_no_temp : 0
[DEBUG] Running kernel 'CopyPadMatrix'
CLBlast: OpenCL error: clEnqueueNDRangeKernel: -4
ArrayFire Exception (Internal error:998):
In function opencl::Array<T> opencl::matmul(const opencl::Array<T>&, const opencl::Array<T>&, af_mat_prop, af_mat_prop) [with T = float]
In file src/backend/opencl/blas.cpp:120
CLBlast Error (-4): CL_MEM_OBJECT_ALLOCATION_FAILURE
```
Whats the best way to handle such size matrices ?

**Comment by CNugteren** [comment]
That is a bit of a design issue yes, and is difficult to combat. A few things you could do though:

* [Query the required buffer size](https://github.com/CNugteren/CLBlast/blob/master/include/clblast.h#L691) and pass that to [GEMM](https://github.com/CNugteren/CLBlast/blob/master/include/clblast.h#L525). That way the user controls it and he/she can make sure it is only allocated once.

* Make sure no temporary buffer is required. Thus, make sure the buffer size is already a multiple of the amount of work done per work-group, e.g. 64 or 128 at most depending on the tuned values. Then also make sure they are pre-transposed as needed. The [Query the required buffer size](https://github.com/CNugteren/CLBlast/blob/master/include/clblast.h#L691) and it's implementation can help you figure out if you are there yet.

* Use the [override parameters](https://github.com/CNugteren/CLBlast/blob/master/include/clblast.h#L717) functionality to set the switching point between direct and in-direct kernels much further. Example [here in one of the tests](https://github.com/CNugteren/CLBlast/blob/master/test/routines/level3/xgemm.hpp#L73).

**Comment by 9prady9** [comment]
@CNugteren Thanks for the suggetions. I will look into those and try to find out whats the best approach for us.
