### ISSUE TITLE
ck compiling error

### ISSUE THREAD

**Issue by tpoisonooo** [CNugteren/CLBlast#339]
I use the [third option](https://github.com/CNugteren/CLBlast/blob/master/doc/installation.md) to cross compile android CLBlast and got `stod` and `to_string` compiling error, here is the part:

>In file included from /home/skyrim/CK-TOOLS/lib-clblast-master-llvm-android-ndk-3.8.256229-android21-arm64/src/src/database/database.cpp:16:
In file included from /home/skyrim/CK-TOOLS/lib-clblast-master-llvm-android-ndk-3.8.256229-android21-arm64/src/src/utilities/utilities.hpp:27:
In file included from /home/skyrim/CK-TOOLS/lib-clblast-master-llvm-android-ndk-3.8.256229-android21-arm64/src/src/clpp11.hpp:65:
In file included from /home/skyrim/CK-TOOLS/lib-clblast-master-llvm-android-ndk-3.8.256229-android21-arm64/src/src/cxpp11_common.hpp:22:
/home/skyrim/CK-TOOLS/lib-clblast-master-llvm-android-ndk-3.8.256229-android21-arm64/src/src/android_patch.h:14:17: error:
      redefinition of 'to_string'
    std::string to_string(T value) {
                ^
/home/skyrim/CK-TOOLS/lib-clblast-master-llvm-android-ndk-3.8.256229-android21-arm64/src/src/utilities/android.hpp:28:13: note:
      previous definition is here
std::string to_string(T value) {
            ^
In file included from /home/skyrim/CK-TOOLS/lib-clblast-master-llvm-android-ndk-3.8.256229-android21-arm64/src/src/database/database.cpp:16:
In file included from /home/skyrim/CK-TOOLS/lib-clblast-master-llvm-android-ndk-3.8.256229-android21-arm64/src/src/utilities/utilities.hpp:27:
/home/skyrim/CK-TOOLS/lib-clblast-master-llvm-android-ndk-3.8.256229-android21-arm64/src/src/clpp11.hpp:75:36: error:
      no matching function for call to 'to_string'
                                   std::to_string(static_cast<int>(status))) {
                                   ^~~~~~~~~~~~~~
/home/skyrim/CK-TOOLS/lib-clblast-master-llvm-android-ndk-3.8.256229-android21-arm64/src/src/android_patch.h:14:17: note:
      candidate template ignored: substitution failure [with T = int]
    std::string to_string(T value) {
                ^
In file included from /home/skyrim/CK-TOOLS/lib-clblast-master-llvm-android-ndk-3.8.256229-android21-arm64/src/src/database/database.cpp:16:
In file included from /home/skyrim/CK-TOOLS/lib-clblast-master-llvm-android-ndk-3.8.256229-android21-arm64/src/src/utilities/utilities.hpp:27:
/home/skyrim/CK-TOOLS/lib-clblast-master-llvm-android-ndk-3.8.256229-android21-arm64/src/src/clpp11.hpp:174:59: error:
      no matching function for call to 'to_string'
      throw RuntimeError("Platform: invalid platform ID "+std::to_string(platform_id));
                                                          ^~~~~~~~~~~~~~
/home/skyrim/CK-TOOLS/lib-clblast-master-llvm-android-ndk-3.8.256229-android21-arm64/src/src/android_patch.h:14:17: note:
      candidate template ignored: substitution failure [with T = unsigned long]
    std::string to_string(T value) {
                ^
In file included from /home/skyrim/CK-TOOLS/lib-clblast-master-llvm-android-ndk-3.8.256229-android21-arm64/src/src/database/database.cpp:16:
In file included from /home/skyrim/CK-TOOLS/lib-clblast-master-llvm-android-ndk-3.8.256229-android21-arm64/src/src/utilities/utilities.hpp:27:
/home/skyrim/CK-TOOLS/lib-clblast-master-llvm-android-ndk-3.8.256229-android21-arm64/src/src/clpp11.hpp:240:55: error:
      no matching function for call to 'to_string'
      throw RuntimeError("Device: invalid device ID "+std::to_string(device_id));
                                                      ^~~~~~~~~~~~~~
/home/skyrim/CK-TOOLS/lib-clblast-master-llvm-android-ndk-3.8.256229-android21-arm64/src/src/android_patch.h:14:17: note:
      candidate template ignored: substitution failure [with T = unsigned long]
    std::string to_string(T value) {
                ^
In file included from /home/skyrim/CK-TOOLS/lib-clblast-master-llvm-android-ndk-3.8.256229-android21-arm64/src/src/database/database.cpp:16:
In file included from /home/skyrim/CK-TOOLS/lib-clblast-master-llvm-android-ndk-3.8.256229-android21-arm64/src/src/utilities/utilities.hpp:27:
/home/skyrim/CK-TOOLS/lib-clblast-master-llvm-android-ndk-3.8.256229-android21-arm64/src/src/clpp11.hpp:258:40: error:
      call to 'stod' is ambiguous
    size_t version = (size_t) (100.0 * std::stod(version_string.substr(0, next_whitespace)));
                                       ^~~~~~~~~
/home/skyrim/CK-TOOLS/lib-clblast-master-llvm-android-ndk-3.8.256229-android21-arm64/src/src/utilities/android.hpp:33:15: note:
      candidate function
inline double stod(const std::string& value) {
              ^
/home/skyrim/CK-TOOLS/lib-clblast-master-llvm-android-ndk-3.8.256229-android21-arm64/src/src/android_patch.h:25:19: note:
      candidate function
    inline double stod(string value) {
                  ^
In file included from /home/skyrim/CK-TOOLS/lib-clblast-master-llvm-android-ndk-3.8.256229-android21-arm64/src/src/database/database.cpp:16:
In file included from /home/skyrim/CK-TOOLS/lib-clblast-master-llvm-android-ndk-3.8.256229-android21-arm64/src/src/utilities/utilities.hpp:27:
/home/skyrim/CK-TOOLS/lib-clblast-master-llvm-android-ndk-3.8.256229-android21-arm64/src/src/clpp11.hpp:355:32: error:
      no matching function for call to 'to_string'
    return std::string{"SM"} + std::to_string(GetInfo<cl_uint>(CL_DEVICE_COMPUTE_CAPA...
                               ^~~~~~~~~~~~~~
/home/skyrim/CK-TOOLS/lib-clblast-master-llvm-android-ndk-3.8.256229-android21-arm64/src/src/android_patch.h:14:17: note:
      candidate template ignored: substitution failure [with T = unsigned int]
    std::string to_string(T value) {
                ^
In file included from /home/skyrim/CK-TOOLS/lib-clblast-master-llvm-android-ndk-3.8.256229-android21-arm64/src/src/database/database.cpp:16:
In file included from /home/skyrim/CK-TOOLS/lib-clblast-master-llvm-android-ndk-3.8.256229-android21-arm64/src/src/utilities/utilities.hpp:27:
/home/skyrim/CK-TOOLS/lib-clblast-master-llvm-android-ndk-3.8.256229-android21-arm64/src/src/clpp11.hpp:356:31: error:
      no matching function for call to 'to_string'
           std::string{"."} + std::to_string(GetInfo<cl_uint>(CL_DEVICE_COMPUTE_CAPAB...
                              ^~~~~~~~~~~~~~
/home/skyrim/CK-TOOLS/lib-clblast-master-llvm-android-ndk-3.8.256229-android21-arm64/src/src/android_patch.h:14:17: note:
      candidate template ignored: substitution failure [with T = unsigned int]
    std::string to_string(T value) {
                ^
1 warning and 7 errors generated.
make[2]: *** [CMakeFiles/clblast.dir/src/database/database.cpp.o] Error 1
make[1]: *** [CMakeFiles/clblast.dir/all] Error 2
make: *** [all] Error 2
Error: build failed!
CK error: [package] package installation failed!

**Comment by tpoisonooo** [comment]
And I have tried [alternative option](https://github.com/CNugteren/CLBlast/blob/master/doc/installation.md) with this command
>cmake .. \
 -DCMAKE_SYSTEM_NAME=Android \
 -DCMAKE_SYSTEM_VERSION=19 \             # Set the appropriate Android API level
 -DCMAKE_ANDROID_ARCH_ABI=armeabi-v7a \  # Set the appropriate device architecture (e.g. armeabi-v7a or arm64-v8a)
 -DCMAKE_ANDROID_NDK=$ANDROID_NDK_PATH \ # Assumes $ANDROID_NDK_PATH points to your NDK installation
 -DCMAKE_ANDROID_STL_TYPE=gnustl_static \
 -DOPENCL_ROOT=/path/to/vendor/OpenCL/lib/folder/   # Should contain libOpenCL.so and CL/cl.h

error message:
>Manually-specified variables were not used by this project:
ANDROID_ARCH_ABI
ANDROID_NDK
ANDROID_STL_TYPE

I have tried `CLBlast-v0.10.0` and master branch。

Would you please update the building and installing document ?

**Comment by CNugteren** [comment]
About your first question regarding CK: I'm not a CK expert, but those missing functions [are defined in CLBlast](https://github.com/CNugteren/CLBlast/blob/c2c1e5fa953659a8ccd647be2e98bc8505ac2abf/src/clpp11.hpp#L59) if the proper define is set. So if you can somehow make sure CK understands that we are compiling for Android, that would solve it. Otherwise, perhaps you can ask one of the CK maintainers, e.g. @psyhtest perhaps?

For your second question, I'm not sure what is going on, CMake should pick them up, they are not CLBlast specific. Perhaps your CMake is not the right version, e.g. too old or too new? Or perhaps not the one corresponding with your Android Studio? Not sure why you are seeing this issue, but it is definitely a CMake issue, [see e.g. here](https://cmake.org/cmake/help/v3.4/prop_tgt/ANDROID_STL_TYPE.html).

**Comment by gfursin** [comment]
From the back of my mind, when we created CK wrapping around CLBlast, it didn't have a few C++ functions and we had to add a patch to add those functions. I suspect that the new version now provides these functions. So CK package should be update to remove this patch ...

**Comment by gfursin** [comment]
https://github.com/ctuning/ck-math/blob/master/package/lib-clblast-master-universal/patch.android/patch

**Comment by gfursin** [comment]
@tpoisonooo - for a test, do you think you can remove this patch and try again, please? You can find this package on your machine as follows:
```
$ cd `ck find package:lib-clblast-master-universal`
$ rm -rf patch.android

**Comment by gfursin** [comment]
If it's indeed the problem, I will remove it from the related CLBlast CK packages in the ck-math repos... Thanks!

**Comment by psyhtest** [comment]
@tpoisonooo We haven't updated CK CLBLast packages for a while, so the patch may no longer apply to the master.

However, I've been able to successfully compile CLBlast 1.2.0 with the following commands:
```
$ ck install package:lib-clblast-master-universal-1.2.0 --target_os=android23-arm64
```
both with `llvm-android-ndk-3.8.256229`  and `gcc-android-ndk-4.9.x`.

**Comment by psyhtest** [comment]
In fact, I can see that patching [was disabled indeed](https://github.com/ctuning/ck-math/commit/5a709da94f3f06bb95b2026cae456f84893d74f2#diff-e918e81587d8db382bbae5d63e027a48) for this package...

**Comment by tpoisonooo** [comment]
@gfursin  Thanks a lot, I removed that patch and got `libcblast.a`.

I have tried `ck install package:lib-clblast-master-universal --target_os=android21-arm64`  and `ck install package:lib-clblast-master-universal-1.2.0 --target_os=android23-arm64`, it works well.

**Comment by tpoisonooo** [comment]
@gfursin Great! I have removed that patch then tried 

`ck install package:lib-clblast-master-universal-1.2.0 --target_os=android23-arm64`
`ck install package:lib-clblast-master-universal-1.2.0 --target_os=android21-arm64`

It works well.

But `ck install package:lib-clblast-master-universal --target_os=android21-arm64` could result in link error.

@CNugteren  My cmake version is 2.8.12.2, let me have a try cmake 3.5 then.

**Comment by gfursin** [comment]
Hi again @tpoisonooo  (CC @psyhtest). I spent some time today updating all CK packages for CLBlast and adding version 1.3 & 1.4: http://cKnowledge.org/shared-packages.html
and checked them on Linux and Android. All seems to be working (with GCC on Android).

You can get these versions by "renewing" your ck-math repo instead of updating it (to avoid clashes with your changes):

```
$ ck renew repo:ck-math
```

Then you can have an access to new packages:
```
$ ck install package:lib-clblast-master-universal-1.4.0 --target_os=android23-arm64
```

Hope it's of any help ;) !

**Comment by psyhtest** [comment]
Just a small niggle. Versioned packages shouldn't have the word "master" in their name. I suggest to rename them as e. g. `package:lib-clblast-1.4.0-universal`.
