### ISSUE TITLE
c_stride=0 in CLBlastSgemmStridedBatched() get wrong results?

### ISSUE THREAD

**Issue by TaihuLight** [CNugteren/CLBlast#346]
@CNugteren @vbkaisetsu 
My code is [clblast_sgemmstridedbatched0.c.zip](https://github.com/CNugteren/CLBlast/files/2720129/clblast_sgemmstridedbatched0.c.zip)

The function **CLBlastSgemmStridedBatched()** performs the matrix-matrix multiplication of a batch of matrices, **c_stride** denotes The (fixed) stride between two batches of the C matrix and determines the locations of output matrix C. Thus, this functions perform
```
for(int i=0; i< batch_count; i++){
C + i * c_stride = αlpha* ( A + i * a_stride ) *( B + i * b_stride ) + β* ( C + i * c_stride ) 
} 
```
**(1) Does the function **CLBlastSgemmStridedBatched()**  support **c_stride=0** in CLBlast?  Besides, does it support  **b_stride=0**  and  **b_stride=0** ?**

(2) I set c_stride=0 to denote the routine shown as following, does it implemented with  **CLBlastSgemmStridedBatched()** ?:
```
for(int i=0; i< batch_count; i++){
C  = αlpha *( A + i * a_stride )* ( B + i * b_stride ) + β *( C ) 
} 
```
But it get the wrong results:
```
Completed SGEMM with status 0
2126.000000
2192.000000
2258.000000
... ...
```
And the ideal results should be
```Completed SGEMM with status 0
4241.000000 = 2126 + 2115
4472.000000 = 2192 + 2180
4503.000000 = 2258 + 2245
... ...
```
When c_stride=0, they get the following results:
![selection_012](https://user-images.githubusercontent.com/19910729/50596921-a24e1480-0ee0-11e9-8e69-6a3da954a6fd.png)
By contract, when c_stride=M*N, they get the same results as following:
![selection_014](https://user-images.githubusercontent.com/19910729/50597324-06bda380-0ee2-11e9-80d0-e32c2ae18aff.png)

(3) The C code is as following, how to get the ideal results with **CLBlastSgemmStridedBatched()**   in my code?
[clblast_sgemmstridedbatched0.c.zip](https://github.com/CNugteren/CLBlast/files/2720129/clblast_sgemmstridedbatched0.c.zip)

**Comment by TaihuLight** [comment]
@CNugteren  which result is correct when c_stride=0? The result obtained on FT-2000+ CPU or on Intel GPU?

**Comment by CNugteren** [comment]
Indeed, a stride for `C` of 0 doesn't work, because all the batches in your loop are (potentially) processed at the same time:
```
for(int i=0; i< batch_count; i++){
C  = α *( A + i * a_stride )* ( B + i * b_stride ) + β *( C ) 
} 
```
And since you are reading from `C` and writing to it, that doesn't work. A stride of 0 for `A` or `B` should work.

**Comment by TaihuLight** [comment]
If the stride for ```C``` dosen't work in **CLBlastSgemmStridedBatched()**, it may be better to give the warning or error tip in CLBlast. For instance, the cublas gives error tip **On entry to SGEMM parameter number 15 had an illegal value**.

**Comment by CNugteren** [comment]
You are absolutely right. I've added a check in the latest master, it should now report the `StatusCode::kInvalidDimension` error (-1017).

**Comment by TaihuLight** [comment]
@CNugteren 
However, the stride of 0 for ```C``` in CLBlastSgemmStridedBatched() is useful in the backfoward of convolution layer. It can be implemented with two steps:
(1) use CLBlastSgemmStridedBatched() to compute batched matrices ```C```;
(2) add a new routine  (e.g., named batchedAddMatrix) to compute the sum of each matrix ```C``` in computed batched matrices ```C```.
Thus, the  new routine (e.g., named batchedMatrix) for adding batched matrices to reducing the results of  CLBlastSgemmStridedBatched(). That is, the new routine  is used to compute the sum of batched matrices as following:
```
for(int i=0; i< batch_count; i++){
SUM = SUM + β* ( C + i * c_stride ) 
} 
```
where c_stride is the stride between two batches of the ```C``` matrix, and batched ```C``` matrices is computed with CLBlastSgemmStridedBatched(). 
Therefore, the new routine for adding matrices is similar with the routine ```xAXPYBATCHED: Batched version of AXPY``` for adding vectors.

**Comment by CNugteren** [comment]
That sounds like a feature request for a nww routine. Would you be so kind and copy+paste that into a new issue and then close this?
