### ISSUE TITLE
Ideally, tests should not depend on clBLAS library

### ISSUE THREAD

**Issue by hughperkins** [CNugteren/CLBlast#35]
Ideally, tests should not depend on clBLAS library.

For example, you could either compare with atlas/openblas, or use some simple slow-but-probably-correct cpu code perhaps like:
```
#include <iostream>
#include <sys/types.h>
#include <stdio.h>
#include <string.h>
#include <clBLAS.h>
#include <stdlib.h>
using namespace std;

  cl_int err;
  cl_platform_id platform = 0;
  cl_device_id device = 0;
  cl_context_properties props[3] = { CL_CONTEXT_PLATFORM, 0, 0 };
  cl_context ctx = 0;
  cl_command_queue queue = 0;
  cl_mem bufA, bufB, bufC;
  cl_event event = NULL;
  int ret = 0;

void clgemm(int colmaj, char transAchar, char transBchar, int M, int N, int K, float alpha, float *A, int lda,
     float *B, int ldb, float beta, float *C, int ldc, float *result) {
clblasTranspose transA = transAchar == 'n' ? clblasNoTrans : clblasTrans;
clblasTranspose transB = transBchar == 'n' ? clblasNoTrans : clblasTrans;

size_t off = 0;
size_t offA = 0;
size_t offB = 0;
size_t offC = 0;

clblasOrder order;
if(colmaj == 1 ) {
  order = clblasColumnMajor;
} else {
  order = clblasRowMajor;
}

  bufA = clCreateBuffer(ctx, CL_MEM_READ_ONLY, M * K * sizeof(*A),
                        NULL, &err);
  bufB = clCreateBuffer(ctx, CL_MEM_READ_ONLY, K * N * sizeof(*B),
                        NULL, &err);
  bufC = clCreateBuffer(ctx, CL_MEM_READ_WRITE, M * N * sizeof(*C),
                        NULL, &err);

  err = clEnqueueWriteBuffer(queue, bufA, CL_TRUE, 0,
      M * K * sizeof(*A), A, 0, NULL, NULL);
  err = clEnqueueWriteBuffer(queue, bufB, CL_TRUE, 0,
      K * N * sizeof(*B), B, 0, NULL, NULL);
  err = clEnqueueWriteBuffer(queue, bufC, CL_TRUE, 0,
      M * N * sizeof(*C), C, 0, NULL, NULL);

  err = clblasSgemm(order, transA, transB, M - off, N - off, K - off,
                       alpha, bufA, offA, lda,
                       bufB, offB, ldb, beta,
                       bufC, offC, ldc,
                       1, &queue, 0, NULL, &event);
  if (err != CL_SUCCESS) {
      printf("clblasSgemmEx() failed with %d\n", err);
      ret = 1;
      exit(1);
  }
  else {
      err = clWaitForEvents(1, &event);
      err = clEnqueueReadBuffer(queue, bufC, CL_TRUE, 0,
                                M * N * sizeof(*result),
                                result, 0, NULL, NULL);
  }

  clReleaseMemObject(bufC);
  clReleaseMemObject(bufB);
  clReleaseMemObject(bufA);

}

void copy(float *target, float *source, int numels ) {
  for(int i = 0; i < numels; i++) {
    target[i] = source[i];
  }
}

// assumes row major
void transpose(float *A, int rows, int cols) {
  float *A_ = new float[rows * cols];
  for(int i=0; i < rows; i++ ) {
    for(int j = 0; j< cols; j++) {
      A_[j * rows + i] = A[i * cols + j];
    }
  }
  copy(A, A_, rows * cols);
  delete[] A_;
}

// assumes row major
void mult(float *C, float *A, float *B, int M, int K, int N) {
  for(int m = 0; m < M; m++ ) {
    for(int n = 0; n < N; n++ ) {
      float sum = 0;
      for(int k = 0; k < K; k++ ) {
        sum = sum + A[m * K + k] * B[k * N + n];
      }
      C[m * N + n] = sum;
    }
  }
}

bool test1(int colmaj, int M, int N, int K, int transAint, int transBint) {
  char transa = transAint == 1 ? 't' : 'n';
  char transb = transBint == 1 ? 't' : 'n';
//  cout << "colmaj=" << colmaj << " " << transa << " " << transb << " M=" << M << " K=" << K << " N=" << N << endl;

  float alpha = 1;
  int lda, ldb, ldc;

  if(colmaj == 1) {
    if(transAint == 1) {
       lda = K;
    } else {
       lda = M;
    }
    if(transBint == 1) {
       ldb = N;
    } else {
       ldb = K;
    }
  } else {
    if(transAint == 1) {
       lda = M;    
    } else {
       lda = K;
    }
    if(transBint == 1) {
       ldb = K;    
    } else {
       ldb = N;
    }
  }

  if(colmaj == 1) {
    ldc = M;
  } else {
    ldc = N;
  }

  float beta = 0;
  // assume these are row major, untransposed
  float *A = new float[M * K];
  float *B = new float[K * N];
  float *C = new float[M * N];
  for(int i = 0; i < M * K; i++) {
     A[i] = rand() / (float)RAND_MAX - 0.5f;
  }
  for(int i = 0; i < N * K; i++) {
    B[i] = rand() / (float)RAND_MAX - 0.5f;
  }
  for(int i = 0; i < M * N; i++) {
    C[i] = 0.0f;
  }

//  cout << "op(A):" << endl;
//    for(int m=0; m < M; m++) {
//      for(int k = 0; k < K; k++) {
//        cout << A[m * K + k] << " ";
//      }
//      cout << endl;
//    }

//  cout << "op(B):" << endl;
//    for(int k = 0; k < K; k++) {
//      for(int n=0; n < N; n++) {
//        cout << B[k * N + n] << " ";
//      }
//      cout << endl;
//    }

   float *Aforblas = new float[M*K];
   float *Bforblas = new float[K * N];
   float *Cforblas = new float[M*N];
   copy(Aforblas, A, M*K);
   copy(Bforblas, B, N*K);

  float *Cours = new float[M * N];

  float *Aour = new float[M * K];
  float *Bour = new float[K * N];
  copy(Aour, A, M * K);
  copy(Bour, B, N * K);
  bool flipAforblas = !(colmaj == 1) != !(transAint == 1);
  bool flipBforblas = !(colmaj == 1) != !(transBint == 1);
  if(flipAforblas) {
    transpose(Aforblas, M, K);
   }
  if(flipBforblas) {
    transpose(Bforblas, K, N);
   }
  mult(Cours, A, B, M, K, N);

//  cout<< "result from CPU: " << endl;
//  for(int m = 0; m < M; m++) {
//    for(int n = 0; n < N; n++) {
//      int i = m + n * M;
//      cout << Cours[i] << " ";
//    }
//    cout << endl;
//  }

  float *clout = new float[M * N];
  clgemm(colmaj, transa, transb, M, N, K, alpha, Aforblas, lda,
     Bforblas, ldb, beta, C, ldc, clout);
  if(colmaj == 1 ) {
    transpose(clout, N, M);
  }
  bool ok = true;
  for(int m = 0; m < M; m++) {
    for(int n = 0; n < N; n++) {
      int i = m + n * M;
//      cout << "  " << i << " " << Cours[i] << " " << clout[i] << endl;
      float diff = clout[i] - Cours[i];
      diff = diff < 0 ? - diff : diff;
      if(diff > 0.0001) {
//         cout << "ERROR " << M << " " << N << " " << K << " " << transa << " " << transb << endl;
         ok = false;
//         exit(1);
      }
    }
  }
  if(!ok) {
   cout << "ERROR colmaj=" << colmaj << " M=" << M << " N=" << N << " K=" << K << " transa=" << transa << " transb=" << transb << endl;
  }
  delete[] A;
  delete[] B;
  delete[] C;
  delete[] Cours;
  delete[] clout;
  return ok;
}

int main(int argc, char *argv[]) {
  clewInit();

  err = clGetPlatformIDs(1, &platform, NULL);
  if (err != CL_SUCCESS) {
      printf( "clGetPlatformIDs() failed with %d\n", err );
      return 1;
  }
  cout << "got platforms" << endl;

  err = clGetDeviceIDs(platform, CL_DEVICE_TYPE_GPU, 1, &device, NULL);
  if (err != CL_SUCCESS) {
      printf( "clGetDeviceIDs() failed with %d\n", err );
      return 1;
  }

  props[1] = (cl_context_properties)platform;
  ctx = clCreateContext(props, 1, &device, NULL, NULL, &err);
  if (err != CL_SUCCESS) {
      printf( "clCreateContext() failed with %d\n", err );
      return 1;
  }

  queue = clCreateCommandQueue(ctx, device, 0, &err);
  if (err != CL_SUCCESS) {
      printf( "clCreateCommandQueue() failed with %d\n", err );
      clReleaseContext(ctx);
      return 1;
  }

  err = clblasSetup();
  if (err != CL_SUCCESS) {
      printf("clblasSetup() failed with %d\n", err);
      clReleaseCommandQueue(queue);
      clReleaseContext(ctx);
      return 1;
  }

  test1(1, 1, 7, 1, 0, 0);
  test1(1, 1, 7, 1, 1, 1);
//  for(int colmaj = 0; colmaj <= 1; colmaj++ ) {
  int colmaj = 1; {
    for(int m=1; m <= 16; m++) {
      for(int n=1; n <= 16; n++) {
        for(int k=1; k <= 16; k++) {
          for(int transA =0; transA <= 1; transA++) {
  //        int transA = 1; {
            for(int transB =0; transB <= 1; transB++) {
//            int transB = 0; {
  //            test1();
              test1(colmaj, m, n, k, transA, transB);
            }
          }
        }
      }
    }
  }
  // check:
  // colmaj transa transb res
  // 0 0 0 ok
  // 0 1 0 ok
  // 0 0 1 FAIL 7 1 1 n t
  // 0 1 1 ok
  // 1 0 0 ok
  // 1 1 0 FAIL 1 7 1 t n
  // 1 0 1 ok
  // 1 1 1 ok

  /* Finalize work with clblas. */
  clblasTeardown();

  /* Release OpenCL working objects. */
  clReleaseCommandQueue(queue);
  clReleaseContext(ctx);

  return 0;
}
```
(I wrote this for clblas, which shows clblas is broken in version 2.4 unfortunately, which is why I'm sort of hunting for a new blas solution for opencl :-P )

**Comment by hughperkins** [comment]
(Ps I dont need any of the following:
- Support all routines supported by clBLAS
- Add half-precision routines (e.g. HGEMM)
- Test in multi-threaded environments

I only need gemm, and gemv, I think.  Dont need multi-threading.  Do need demonstrable correctness.  Do need some control over synch, but depends what you mean really, and what you offer in terms of synching currently?
)

**Comment by CNugteren** [comment]
I'll first comment on your first post:

I agree, the 'dependency' on clBLAS is not so nice, especially on platforms on which clBLAS is poorly supported (e.g. ARM Mali). It's on my list to implement testing against CPU BLAS libraries, this will probably go into the next release. I don't think it's a good idea to re-implement BLAS just for testing, because that can give errors as well and is just a lot of extra effort and code. But I still want to keep clBLAS in (if it is present on the system), because this allows a nice head-to-head performance comparison.

**Comment by CNugteren** [comment]
Then a comment on your second post (which is a separate issue?):

Multi-threading support is already tested and included in the latest development version, it will be included in the next release. The other points might not be needed by you, but that doesn't mean no-one wants them? :-)

About synchronisation: currently a `clWaitForEvents` is included within the library. That means that the CLBlast calls are completed when they return. This is not desired in many cases, as users might want to overlap GPU/CPU code or GPU kernels with memory copies. Therefore, control needs to be given back to the user. This is on the TODO list.

**Comment by hughperkins** [comment]
**Re: Correctness checking**

> But I still want to keep clBLAS in (if it is present on the system

I think it would be good to separate correctness tests from performance comparisons.

One of the major downsides of clBLAS is that it is really painful to build, not very easy to maintain across platforms.  If I have to build it anyway, in order to establish the correctness of clBLAST on each platform, then ... well then I've already got clBLAS building and working, and could just use clBLAS right? :-)

Note that clBLAS is *not* systematically correct, see the bug in 2.4, that my script at https://github.com/CNugteren/CLBlast/pull/38#issuecomment-203688530 detects

As far as using eg atlas sgemm as your point of comparison for correctness, I experimented with using both calls to atlas vs writing my own code.  Of course, if you want to benchmark performance, you wouldnt write your own naive code to do so, but writing a matrix multiplication in c is terribly easy, just a few minutes work, and a few more minutes fo rhandling transpose and col vs row major transpose.  I tried comparing clblas with openblsa, but then noticed that openblas doesnt hvae a 'colmajor vs rowmajor' parameter, so I'd need to handle transpose myself.  Finally, I just did all the matrix multiplication myself, and it worked very well.

**Comment by hughperkins** [comment]
**Re: events**

Ah, yes, you should not be doing an implicit sync, client should handle deciding when to synch.  So, your upcoming changes on this point sound good.

**Comment by hughperkins** [comment]
**Re: multithreading**

Yes, multithreading would be good to have :-)

**Comment by CNugteren** [comment]
Indeed, writing GEMM yourself might be doable and not to tricky. However, there are many routines, with many parameters, so I will post-pone that for now. What about this:

* If clBLAS is installed, it can be used for testing (enable/disable) and for performance comparison (enable/disable).
* If a CPU BLAS library is installed, it can be used for testing (enable/disable) and for performance comparison (enable/disable).

In the future I'll add a third option (which can be disabled and enabled), which is custom written code. But I'll use the existing testing framework for that. And this will be something for after the first 1.0.0 release, it is not too urgent as soon as regular CPU BLAS is supported for testing.

**Comment by hughperkins** [comment]
Well, if cpu blas tests are available and working, then that is sufficient.  No need for two sets of cpu tests.  I suspect you are underestimating the difficulty of calling into cpu blas :-)  but I might be wrong :-)

**Comment by CNugteren** [comment]
I have just merged the `cpu_blas` branch into `development`. It now also supports a CPU BLAS library for correctness as well as performance comparisons. I have tested it on OS X and Linux with a couple of BLAS libraries.

Could you test it as well on your system? I am not sure it auto-detects all BLAS libraries yet.

**Comment by hughperkins** [comment]
> That said, clBLAS is still the primary reference to test against, since it returns error codes.

Question: why do you need the error code?  Do you mean, you're not comparing the results returned by the two libraries? Or ... ?

**Comment by CNugteren** [comment]
Testing a library is not only testing for positive behaviour, you also need to test for invalid behaviour. So what I test for example is whether an invalid combination of arguments is properly caught. Both clBLAS and CLBlast return error codes, so I can just compare them. The CPU BLAS library I tested just completely stops and prints a message to the screen, so that is not so helpful to test against.

**Comment by hughperkins** [comment]
I get one failure, on NVIDIA 940M, for xgemm.  I'll log an issue for it.

**Comment by hughperkins** [comment]
(Oh, its not for SGEMM or DGEMM actually, it' sfor CGEMM.  The SGEMM and DGEMM tests pass ok, on 940M)

**Comment by hughperkins** [comment]
Ok.  So there are tests that dont need clblas now.  But ... if you look at my test above (and in my pull request), it rigorously tries every combination up to size 16x16.  It catches some really bad errors in clblas 2.4 for example, which apparently got through their original tests at the time.  They only take ~a few minutes to run, and it's just a few for loops, so might as well add them in? (after 16, presumably the same edge cases come up time and again, so less likely to hit new issues, though might want to sample perhaps?)

**Comment by hughperkins** [comment]
Oh... `-full_test` :-) running...

**Comment by hughperkins** [comment]
Hmmmm, I got a failure :-P  on SGEMM.  I assume it's just a precision thing?  I'll log an issue anyway.

**Comment by hughperkins** [comment]
Closing, since there are tests that dont rely on clblas now.  Thank you Cedric

**Comment by CNugteren** [comment]
Thanks for testing. Yeah, I've also seen occasional small errors. This is a precision thing, related to the order in which computations are performed. I'll comment in more details in the other issue.

**Comment by CNugteren** [comment]
Also, in case you do want to test all sizes up to 16 by 16 (which will be quite a lot actually), you can just expand upon the current sizes to be tested in `test/correctness/testblas.h` around line 50:
```const std::vector<size_t> kMatrixDims = { 7, 64 };```

**Comment by hughperkins** [comment]
Well, I shall probably just run my existing test script ;-)  But just seems like, might as well add that into the library?  But I'm fine with keeping it in my own fork for now.

> (which will be quite a lot actually),

From memory its about 16384 tests.  Runs in ~few minutes.
