### ISSUE TITLE
Question about concurrent CLBlast processes

### ISSUE THREAD

**Issue by Michtuny** [CNugteren/CLBlast#352]
Dear all,
I am currently working with CLBlast on an NVIDIA GPU.

I observed that when I execute 2 different processes concurrently (specifically tuning processes e.g. clblast_tuner_xgemm and clblast_tuner_xdot) the kernel times of each tuning process remains the same with its time when running on the GPU alone. Additionally, I used nvidia-smi to monitor the used resources (It seems to work even for opencl processes as well) and I observed that the full used resources for the both processes is almost the addition of the used resources for each process separately.

For those reasons, and eventhough I believe that different applications in OpenCL are scheduled (the kernels) with time slicing I can understand that:

1)either the nvidia-smi resources monitor does not monitor correct results for some reason and the kernels are too fast to "meet each other" because they have finished on the GPU or
2)from the software scope CLBlast has achieved the concurrent multiapplication (spatial GPU sharing).

I am not that experienced with OpenCL but to my knowledge, Opencl can only allow concurrent multiapplication on the GPU just from the same process (using different command queues for each kernel).

Could you please explain why this happen to me and how CLBlast manage concurrent multi kernels from different processes?

Thank you in advance

**Comment by CNugteren** [comment]
First of all sorry for my late reply (i forgot about your question).

So you see this behaviour when running the CLBlast tuners, right? What if I told you that typically most of the time spend in the tuners is not actually on the GPU? Most time is spend on kernel compilation on the CPU, plus also some CPU-GPU memory copies and comparison of results for correctness.

A better test would be to run twice the CLBlast client ([see here how to compile them](https://github.com/CNugteren/CLBlast/blob/master/doc/benchmarking.md#compiling-the-performance-tests-clients)) with a sufficiently large problem size, e.g.:
```
./clblast_client_xgemm -m 2048 -n 2048 -k 2048 -cblas 0 -clblas 0
```
Probably you won't see the same results anymore, the total run-time will be roughly doubled.

**Comment by CNugteren** [comment]
Closing this as this isn't a real CLBlast issue I believe and hopefully the question was answered :-)
