### ISSUE TITLE
Batch kernels not being tuned

### ISSUE THREAD

**Issue by JishinMaster** [CNugteren/CLBlast#361]
Hi,

I have used this page https://github.com/CNugteren/CLBlast/blob/master/doc/tuning.md to tune clblast for my devices (AMD and Nvidia alike).
I observed some low performances with the AMD device (RoCM 2.5) when using the CgemmStridedBatch routine. 
I activated the "AMD_OCL_BUILD_OPTIONS_APPEND=-save-temps-all" to dump the kernels used by clblast during execution.

It defines "ROUTINE_GEMMSTRIDEDBATCH" and calls TransposePadMatrixStridedBatched, CopyPadMatrixStridedBatched, XgemmStridedBatched, XgemmDirectStridedBatchedNN.

I saw no mention of those in the json files.

Are those routines tuned?
If not, what are the changes required to tune those functions?

Thank you in advance.

**Comment by CNugteren** [comment]
Those kernels you mention (e.g. `XgemmStridedBatched`) basically use the same code as the regular kernels, and they share the tuning parameters. So tuning for the regular kernels also tunes these actually, however the typical sizes (m, n, k) might be different and the batching behaviour might influence it a bit as well, so it might be sub-optimal.

About the speed on your AMD device, it might be related to #350 (although I'm not sure what your device is).

**Comment by CNugteren** [comment]
Closing this, see the message above.
