### ISSUE TITLE
assert parameter_name == parameter_names[parameter_index],  AssertionError: KWG == GEMMK index 0 

### ISSUE THREAD

**Issue by paolodalberto** [CNugteren/CLBlast#362]
adding in the data base xgemm_json

**Comment by paolodalberto** [comment]
./clblast_tuner_xgemm --precision 16 --device 2 --platform 0
python ../scripts/database/database.py . ..

['GEMMK', 'KREG', 'KWG', 'KWI', 'MDIMA', 'MDIMC', 'MWG', 'NDIMB', 'NDIMC', 'NWG', 'SA', 'SB', 'STRM', 'STRN', 'VWM', 'VWN']
{u'MDIMC': 8, u'MDIMA': 32, u'KWG': 16, u'KWI': 2, u'NDIMC': 32, u'NDIMB': 16, u'VWM': 4, u'VWN': 1, u'NWG': 128, u'MWG': 128, u'STRN': 1, u'STRM': 1, u'SB': 1, u'SA': 1}
Traceback (most recent call last):
  File "../scripts/database/database.py", line 185, in <module>
    main(sys.argv[1:])
  File "../scripts/database/database.py", line 179, in main
    clblast.print_cpp_database(database_best_results, cpp_database_path)
  File "/home/paolo/fusion/paolo/Desktop/MM/CLBlast/scripts/database/database/clblast.py", line 235, in print_cpp_database
    assert parameter_name == parameter_names[parameter_index], "%s == %s index %s " % (parameter_name, parameter_names[parameter_index], parameter_index)
AssertionError: KWG == GEMMK index 0 

[clblast_xgemm_11_16.json.txt](https://github.com/CNugteren/CLBlast/files/3380322/clblast_xgemm_11_16.json.txt)
[clblast_xgemm_2_16.json.txt](https://github.com/CNugteren/CLBlast/files/3380323/clblast_xgemm_2_16.json.txt)
[clblast_xgemm_1_16.json.txt](https://github.com/CNugteren/CLBlast/files/3380324/clblast_xgemm_1_16.json.txt)

I pull the new code and I am trying to rebuild the gemmx library for a fiji and polaris ProDuo. The tuning was successful for 3 of the 4 parts. Then I tried to save the results in the DB. 

let me know how I can help any further

**Comment by paolodalberto** [comment]
thank you

**Comment by CNugteren** [comment]
I dont have access to my computer at the moment, so i cant help you debug. Have you isolated which of the JSON files causes this issue? Perhaps you can try to recreate that one. Otherwise you'll have to omit those breaking it for the time being until we debug the issue. I cant help you further at the moment unfortunately.

**Comment by paolodalberto** [comment]
I think was a problem of a stale database.json
closing this
