### ISSUE TITLE
Repeated calls to cblas_xgemm results in OpenCL error: clCreateCommandQueue: -30

### ISSUE THREAD

**Issue by stevepur** [CNugteren/CLBlast#363]
I modified sgemm_netlib.c so that it repeatedly calls cblas_sgemm in a loop, and after several hundred calls I get 
```
...
iteration 669
iteration 670
iteration 671
iteration 672
libc++abi.dylib: terminating with uncaught exception of type clblast::CLCudaAPIError: OpenCL error: clCreateCommandQueue: -30
Abort trap: 6
```
The first time this happened after the 681st call, and in all the subsequent tests it happens after the 672nd call.

This is on mac os X 10.13.6 with an AMD Radeon RX 580, called with CLBLAST_DEVICE=1.  From monitoring iStat Menus it is clear that the computation is happening on the Radeon and there is no sign of a memory leak .  The error does not happen (in 2000 calls) if the code is called with CLBLAST_DEVICE = 0 (CPU).  I discovered this issue calling cblas_zgemm, so it seems to be common to the cblas_xgemm family.  The code is attached.

Am I doing something wrong, or is this a bug?
[sgemm_netlib.c.zip](https://github.com/CNugteren/CLBlast/files/3390698/sgemm_netlib.c.zip)

**Comment by stevepur** [comment]
If I change the loop in my sgemm_netlib.c to, say, 500 calls so sgemm_netlib completes successfully, and then call sgemm_netlib many times from a bash script, I do not see this error after thousands of calls to cblas_sgemm.  So a workaround could be to somehow do whatever happens when sgemm_netlib exits and restarts, but I don't see how to do that from within sgemm_netlib.c.

**Comment by stevepur** [comment]
I discovered that I resolve this problem by adding #define NETLIB_PERSISTENT_OPENCL to clblast_netlib_c.cpp.  This makes the context static so it is persistent, which prevents the crash below.  I didn't understand the comment suggesting this until after I did a lot of digging.  I'm now successfully using zgemm on my AMD GPU in my application :)

When digging in to understand the problem, I discovered that the crash was due to line 102 in Routine::InitProgram in routine.cpp, where the program is stored in the program cache.  My understanding of the problem is this: because previously context was not persistent, it was different with every call to cblas_sgemm (I verified this is the case).  But context is part of the key that Routine::InitProgram uses to detect when the program is already in the program cache.  So Routine::InitProgram decides it is a new program and adds it to the cache.  I suppose that after a while the cache gets too big and bad things happen.

When context is persistent I expect that  Routine::InitProgram can detect that it is already in the program cache (though I did not check this), so the cache does not fill up.  

I'm really happy now: I'll leave to Cedric to decide if the non-graceful way the library crashes with misleading error messages when context is not persistent amounts to a bug.

**Comment by CNugteren** [comment]
Thanks for reporting (and solving). I'll have a look soon when im back from holidays.

**Comment by CNugteren** [comment]
Sorry that you had to debug this yourself. Indeed, I think your description is correct. I guess you've found the earlier related issue (https://github.com/CNugteren/CLBlast/issues/307)?

How would you propose to make this a more descriptive error message though?

**Comment by stevepur** [comment]
> I guess you've found the earlier related issue (#307)?
No, I didn't see that, but it's nice to see the history behind this.

> How would you propose to make this a more descriptive error message though?
That's not at all obvious, because the error message seems to happen far from the actual cause of the error.  According to [https://www.khronos.org/registry/OpenCL/sdk/1.0/docs/man/xhtml/clCreateCommandQueue.html](url) OpenCL error: clCreateCommandQueue: -30 (CL_INVALID_VALUE) means that values specified in properties are not valid.  But properties does not change from call to call.  I spent a fair amount of time looking in the wrong place because of this.  All I can conclude is that when the cache gets filled up unpredictable things happen and errors get thrown later.

Can you make the cache smart enough to throw an error when it is about to fill up?
