### ISSUE TITLE
Cannot resolve symbol

### ISSUE THREAD

**Issue by kar-dim** [CNugteren/CLBlast#367]
Hello,

I am windows user. I am trying to use the pre-built binaries for the 1.5 version.
I pointer the Visual Studio linker to the lib folder, added the "clblast.lib" as an additional library dependency, copied the "clblast.dll" in the output directory, and finally I included the "include" directory on the "Additional Include Directories" on visual studio.

There is one unresolved symbol though, this is what I am getting.
Is there something more that I need to do? Thanks

error LNK2001: unresolved external symbol "enum clblast::StatusCode __cdecl clblast::Gemm<int>(enum clblast::Layout,enum clblast::Transpose,enum clblast::Transpose,unsigned __int64,unsigned __int64,unsigned __int64,int,struct _cl_mem * const,unsigned __int64,unsigned __int64,struct _cl_mem * const,unsigned __int64,unsigned __int64,int,struct _cl_mem *,unsigned __int64,unsigned __int64,struct _cl_command_queue * *,struct _cl_event * *,struct _cl_mem *)" (??$Gemm@H@clblast@@YA?AW4StatusCode@0@W4Layout@0@W4Transpose@0@1_K22HQEAU_cl_mem@@22322HPEAU4@22PEAPEAU_cl_command_queue@@PEAPEAU_cl_event@@4@Z)

**Comment by CNugteren** [comment]
That unresolved symbol is a call to the GEMM routine, which is perhaps the only thing you are using, or why do you say 'one unresolved symbol'? Does the rest work? Do you get a different error message if you don't link to CLBlast? Perhaps it is a 32 vs 64-bit issue?

**Comment by kar-dim** [comment]
Hmm, I switched to the C API because the error did not make sense! I probably messed up somewhere, can I close the issue?
