### ISSUE TITLE
Problem during compliling for Android

### ISSUE THREAD

**Issue by luoyin500** [CNugteren/CLBlast#369]
I tried to complile it for Android (Mali GPU)
the command line is as you gave:

mkdir build
cd build
cmake .. -DCMAKE_SYSTEM_NAME=Android -DCMAKE_SYSTEM_VERSION=19 -DCMAKE_ANDROID_ARCH_ABI=armeabi-v7a -DCMAKE_ANDROID_NDK=$ANDROID_NDK_PATH -DCMAKE_ANDROID_STL_TYPE=gnustl_static -DOPENCL_ROOT=D:\libs\opencllib
pause

the structure of the path -DOPENCL_ROOT is
/lib/libOpenCL.so
/include/CL/cl.h

But error appeared:

D:\libs\CLBlast-master\CLBlast-master\build>cmake .. -DCMAKE_SYSTEM_NAME=Android -DCMAKE_SYSTEM_VERSION=19 -DCMAKE_ANDROID_ARCH_ABI=armeabi-v7a -DCMAKE_ANDROID_NDK=$ANDROID_NDK_PATH -DCMAKE_ANDROID_STL_TYPE=gnustl_static -DOPENCL_ROOT=D:\libs\opencllib
CMake Error at CMakeLists.txt:22 (project):
  CMAKE_SYSTEM_NAME is 'Android' but 'NVIDIA Nsight Tegra Visual Studio
  Edition' is not installed.

-- Configuring incomplete, errors occurred!
See also "D:/libs/CLBlast-master/CLBlast-master/build/CMakeFiles/CMakeOutput.log".

**Comment by CNugteren** [comment]
A quick search shows that this is not related to CLBlast, but is an issue with generating VS studio files. Here's a suggestion to solve it which I found at https://aws.amazon.com/blogs/developer/setting-up-an-android-application-with-aws-sdk-for-c/:
```
On Windows, you might see the error message: “CMAKE_SYSTEM_NAME is ‘Android’ but ‘NVIDIA Nsight Tegra Visual Studio Edition’ is not installed.” In that case, install Ninja and change the generator from Visual Studio to Ninja by passing 
```
If that doesn't help, I suggest to search the internet further. I'm closing this as I believe it is unrelated to CLBlast.
