### ISSUE TITLE
cross-compile error?

### ISSUE THREAD

**Issue by lhxy1991** [CNugteren/CLBlast#371]
Hi, i use cmake to compile clblast with android:
cmake .. -DCAMEK_SYSTEM_NAME=Android -DCMAKE_SYSTEM_VERSION=19 -DCMAKE_ANDROID_ARCH_ABI=armeabi-v7a -DCMAKE_ANDROID_NDK=/opt/SDK/ndk-bundle -DCMAKE_ANDROID_STL_TYPE=gnustl_static -DOPENCL_ROOT=/home/xxx/opencl/

And,this is a waring :
   Manually-specified variables were not used by the project:
  CMAKE_SYSTEM_NAME
CMAKE_ANDROID_ARCH_ABI
CMAKE_ANDROID_NDK

And my cmake's version is 3.5.1  ,NDK is r14b,.
How can i compile a successful clblast to use for android ndk?

**Comment by lhxy1991** [comment]
And I use Ninja to cross-compile it. I also meet some error:
../src/cache.hpp:62:16: error: 'mutex' in namespace 'std' does not name a type
   mutable std::mutex cache_mutex_;

**Comment by CNugteren** [comment]
So you are following the instructions [here](https://github.com/CNugteren/CLBlast/blob/master/doc/installation.md#android-compilation-from-source)? According to that variables like `CMAKE_ANDROID_ARCH_ABI` should be set. And according to the [CMake docs](https://cmake.org/cmake/help/latest/variable/CMAKE_ANDROID_ARCH_ABI.html) this is a valid variable name, so there seems to be something wrong with your CMake. I would debug that first.

**Comment by lhxy1991** [comment]
Hi,i do it follw thr instructions https://github.com/CNugteren/CLBlast/blob/master/doc/installation.md#android-compilation-from-source
And my cmake's version is 3.5.1,more then 2.8. And three itens had set,but they had not be used.

**Comment by CNugteren** [comment]
Closing this issue, most likely something unrelated to CLBlast is going wrong here. Please re-open if this is still an issue.
