### ISSUE TITLE
Question for use case. 

### ISSUE THREAD

**Issue by karasjoh000** [CNugteren/CLBlast#373]
Hi, 
I want to use CLBlast for a econometrics lib, would this library work for any general GPU like AMD, intel, and nvidia? What I am trying to accomplish is to have lin alg ops run on a GPU for the econometrics operations.

**Comment by CNugteren** [comment]
Yes, I believe it can fit your use-case. It will run basic linear algebra operations on any GPU, but keep in mind that data-transfer between CPU and GPU can sometimes also start to play a role. If you want operations beyond those that CLBlast provides and do more advanced linear algebra, you can also consider [ArrayFire](https://github.com/arrayfire/arrayfire), which actually uses CLBlast as a back-end for certain operations.

**Comment by karasjoh000** [comment]
Ok, makes sense. 

"data-transfer between CPU and GPU can sometimes also start to play a role."

Do you know any papers that talk about scheduling tasks between GPU and CPU based on job size achieving optimum performance?

**Comment by CNugteren** [comment]
I guess there are a few, but not sure if a paper is the best place to look, but rather look for some OpenCL tutorials? Whether this is an issue or not depends on your hardware and on your problem, e.g. if you want to do a 1024x1024x1024 GEMM, you are probably fine, but if you do level 1 or level 2 BLAS operations or smaller level 3 BLAS ops, then you might have issues. But then again, if you can do multiple things on your data before transferring back you won't suffer from this anymore of course :-)
