### ISSUE TITLE
Uncaught exception in tuner

### ISSUE THREAD

**Issue by jamesjer** [CNugteren/CLBlast#374]
Original bug report: https://bugzilla.redhat.com/show_bug.cgi?id=1801313
A Fedora user ran `clblast_tuner_xgemm` with 0 GPUs available.  When `clblast::Platform::NumDevices` called `clblast::CLCudaAPIError::Check`, the `Check` routine threw `CLCudaAPIError`, but nothing catches that exception, resulting in the default C++ abort due to an uncaught exception.  It would be better to catch that exception and tell the user that tuning 0 devices is not a useful thing to do (or simply that tuning failed).

**Comment by CNugteren** [comment]
Thanks for reporting. To be honest I don't treat the tuners as the good as the library itself, but nevertheless probably good to fix. I'll have a look soon when I have time.

**Comment by CNugteren** [comment]
I made a PR, catching all relevant exceptions in a same way as done in other parts of the library and printing an error message instead to string, returning some non-zero exit code:
https://github.com/CNugteren/CLBlast/pull/376
Would this solve the issue?

**Comment by jamesjer** [comment]
Yes, that looks like a good solution to me.

**Comment by CNugteren** [comment]
Thanks. Code is merged in, and a new release (1.5.1) is made.
