### ISSUE TITLE
Cannot update tuning database

### ISSUE THREAD

**Issue by MigMuc** [CNugteren/CLBlast#379]
Upon performing the tuning, the database cannot be updated. The python script exits with the following error: 
```
$ python ../scripts/database/database.py . ..
[database] Loading database from '../scripts/database/database.json'
[database] Processing './clblast_copy_32.json' with 96 new items
Traceback (most recent call last):
  File "../scripts/database/database.py", line 185, in <module>
    main(sys.argv[1:])
  File "../scripts/database/database.py", line 140, in main
    remove_mismatched_arguments(database)
  File "../scripts/database/database.py", line 37, in remove_mismatched_arguments
    group_by_arguments = db.group_by(kernel_group, clblast.ARGUMENT_ATTRIBUTES)
  File "/home/mig/Downloads/CLBlast-1.5.0/scripts/database/database/db.py", line 72, in group_by
    database.sort(key=itemgetter(*attributes))
TypeError: itemgetter expected 1 argument, got 0
```

**Comment by CNugteren** [comment]
Could you share the `clblast_copy_32.json` file you are loading as well? Then I can try to reproduce.

**Comment by MigMuc** [comment]
The problem is not specific to that file, it happens with other tuning files as well.
[clblast_copy_32.json.zip](https://github.com/CNugteren/CLBlast/files/4333519/clblast_copy_32.json.zip)

**Comment by CNugteren** [comment]
I tried to reproduce but I couldn't, it works with your file. Perhaps your base database is outdated or wrong? Could you remove (or move to keep a backup) your `scripts/database/database.json` database? By doing that, it will download a fresh copy from https://github.com/CNugteren/CLBlast-database automatically.

**Comment by MigMuc** [comment]
I deleted the `scripts/database/database-json` file and started the script again and got the same error again. The python version is
```    database.sort(key=itemgetter(*attributes))
TypeError: itemgetter expected 1 argument, got 0
[mig@pc build]$ python
Python 3.8.2 (default, Feb 26 2020, 22:21:03) 
[GCC 9.2.1 20200130] on linux```

**Comment by CNugteren** [comment]
I've just tested with Python 3.7 and no issues there. Could you test with another Python version if you have it installed?

I've also added a debug print statement, and this failing function is called many times. I'm curious to see where it fails for you. You can apply this patch to get a bit more info:
```
--- a/scripts/database/database/db.py
+++ b/scripts/database/database/db.py
@@ -69,6 +69,7 @@ def group_by(database, attributes):
     """Returns an list with the name of the group and the corresponding entries in the database"""
     assert len(database) > 0
     attributes = [a for a in attributes if a in database[0]]
+    print(attributes)
     database.sort(key=itemgetter(*attributes))
     result = []
     for key, data in itertools.groupby(database, key=itemgetter(*attributes)):
```

You can also run the script itself with `--verbose` for more output, but I think it already crashes before it reaches such a point. Also make sure you are on the latest master of CLBlast.

**Comment by MigMuc** [comment]
The problem does not ocur with the newest version 1.5.1. We can close the issue. Thank you.
