### ISSUE TITLE
Tuning `gemm_direct` for custom size on NVIDIA V100

### ISSUE THREAD

**Issue by richard-wwu** [CNugteren/CLBlast#381]
I am trying to tune CLBlast's `gemm_direct` routine for the input size `M=10, N=500, K=64` using the included tuning program. I call the tuner like so:

`./clblast_tuner_xgemm_direct -platform 1 -device 0 -m 10 -n 500 -k 64 -alpha 1 -beta 0 -fraction 1`

This works without a problem on Intel CPU, but on NVIDIA V100 all configurations are skipped with `error -54`.

Is there a way to fix this? Many thanks in advance!

**Comment by CNugteren** [comment]
Not sure why this happens. `CL_INVALID_WORK_GROUP_SIZE` hints at too many threads I believe. Could you try to pinpoint the issue, e.g. try first with the default values of m/n/k, and then see when this occurs, perhaps only when m is not a multiple of 32 for example (just saying something).

**Comment by richard-wwu** [comment]
Thanks for your reply. I tried different input sizes:
`M=16,N=512,K=64` works,
`M=10,N=512,K=64` works,
`M=16,N=500,K=64` does not work.
What I think is strange is that it works on CPU just fine, but fails on GPU.

**Comment by CNugteren** [comment]
I could reproduce the issue on my system, and I've fixed something in the tuners, and now it works again. Could you also test on your V100 system?

See the https://github.com/CNugteren/CLBlast/pull/388 PR (`CLBlast-381-gemm-direct-tuner-failure` branch).

**Comment by richard-wwu** [comment]
It works, many thanks for your help!
