### ISSUE TITLE
Tuning eventually stops working

### ISSUE THREAD

**Issue by trondbn** [CNugteren/CLBlast#382]
When running the tuning routine with a significant number (several hundred, but it varies) of configurations, it eventually stops working and spits out something along the lines of `compilation error: -30 | <-- skipping`. At this point the tuning process slows to a crawl.

The source of the problem actually seems to be this line:
https://github.com/CNugteren/CLBlast/blob/78300ccbeacdfe9688f04639b2e15fb2f24e2a16/src/tuning/tuning.cpp#L254

The error seems to stem from `clCreateCommandQueue` in the Queue constructor, though the error code -30: CL_INVALID_VALUE, which is supposed to indicate that the queue properties are invalid, does not really make sense. It might be some sort of bug affecting a small subset of OpenCL implementations (I have a Macbook pro with Macos Catalina (10.15.4) and I am trying to tune for AMD Radeon 555X 4GB). (Maybe the command queues are not properly disposed of between iterations, for whatever reason.)

Moving the creation of the queue outside of the loop over configurations and reusing it for each iteration seems to avoid the problem, without any obvious ill effects.

**Comment by CNugteren** [comment]
OK, thanks for reporting. Not sure how common the issue is indeed, but your suggestion for a solution seems reasonable anyway. I'll work on this in the coming week when I have time.

**Comment by CNugteren** [comment]
I've made a PR with the fix, will merge in soon.
