### ISSUE TITLE
Get version at run time

### ISSUE THREAD

**Issue by bxk-sonavex** [CNugteren/CLBlast#385]
Hi there, thanks for making this wonderful package!  As far as I can see, the version can only be seen on the downloaded file name but not anywhere else in a separate "version" file, a macro in a header, or a "version" function.  This renders difficulties in tracking and knowing which version is being used.  You know, the file/folder name is fairly easy to be messed up and it's impossible when directly using the dll/lib file.

Could you kindly consider adding a way to get the version in run-time? Thanks in advance!

**Comment by CNugteren** [comment]
Would something like this satisfy your needs?
https://github.com/CNugteren/CLBlast/pull/389

**Comment by bxk-sonavex** [comment]
Looks great.  Thanks!

**Comment by CNugteren** [comment]
Merged in. Version can be queried with defines CLBLAST_VERSION_MAJOR/MINOR/PATCH.
