### ISSUE TITLE
Failed to build CLBlast for Android 10

### ISSUE THREAD

**Issue by dmytro1977** [CNugteren/CLBlast#393]
Gentlemen,

I`ve tried to build the library for newer Android 10 and .... failed. (Aarch64 architecture) I know that it was compiled OK 3 years ago but now Android NDK was moved to clang.

Some details:
The very minor problem is that src/utilities/android.hpp is not needed any more.
But another problem is that e.g. Android NDK 20b moved to LLVM infrastructure and gcc libraries to link with are missing.
I found some older libraries for gcc (libcutils.so, libc++.so) but it has not helped me - gcc toolchain is not supported.

Could you gently suggest me of you have a receipt how to build it for newer Androids?

**Comment by CNugteren** [comment]
Personally I haven't tried with newer Android versions, but on a normal x86 machine it builds fine with Clang, so I guess that itself shouldn't be a problem.

Could you tell me which of the 3 build options from [here](https://github.com/CNugteren/CLBlast/blob/master/doc/installation.md#android-compilation-from-source) you are using? And if using CMake, share you CMake command?

**Comment by dmytro1977** [comment]
Thank you for answer

We decided to build it from scratch (as we do 3 years ago :) )

cmake is called as follows

export ANDROID_NDK=/root/Android/Sdk/ndk/android-ndk-r20b
export ANDROID_SDK=/root/Android/Sdk/
/root/Android/Sdk/cmake/3.10.2.4988404/bin/cmake -DCMAKE_SYSTEM_NAME=Android -DCMAKE_TOOLCHAIN_FILE=${ANDROID_NDK}/build/cmake/android.toolchain.cmake -DCMAKE_ANDROID_NDK=${ANDROID_NDK} -DANDROID_TOOLCHAIN=clang -DANDROID_SDK_TARGET=21 -DANDROID_ABI=arm64-v8a -DCMAKE_SYSTEM_VERSION=21 -DCMAKE_ANDROID_STL_TYPE="c++_shared" -DOPENCL_INCLUDE_DIRS=/home/osboxes/git/blast/OpenCL-Headers -DOPENCL_ROOT=/home/osboxes/git/blast/OpenCL-Headers -DANDROID_STL="c++_shared" -DOPENCL_LIBRARIES=/home/osboxes/git/blast/OpenCL-Headers/CL/libOpenCL.so ..

I beleive the problem is raised by pre-compiled OpenCL library. I beleive it is compiled by gcc. So it depends on one library set, but Android-built object files on another.
I wonder if it is possible not to use pre-compiler libOpenCL.so binaries? So that application can load opencl library in runtime, on device. I really did not dive deep into your build system, maybe you can suggest something.

**Comment by dmytro1977** [comment]
Actually, was able to build the library. Soon will add details.

**Comment by CNugteren** [comment]
I'm closing this since I believe it was solved. Would still be great if you can summarize what the issue was and how you solved it.
