### ISSUE TITLE
How to mention Opencl Verison during compile time

### ISSUE THREAD

**Issue by Chidhambararajan** [CNugteren/CLBlast#394]
I am trying to complie CLBlast on an ARM soc and I am stuck with this 

/usr/include/CL/cl_version.h:34:104: note: #pragma message: cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 220 (OpenCL 2.2)
It has Opencl1.2 support 

How should I mention my opencl version during compile time

Thanks in Advance

**Comment by CNugteren** [comment]
Hmm, that is weird, because it is defined in CLBlast: [here](https://github.com/CNugteren/CLBlast/blob/41f344d1a6f2d149bba02a6615292e99b50f4856/src/clpp11.hpp#L50) as:
```
#define CL_TARGET_OPENCL_VERSION 110
```
And this is before include the OpenCL headers.

What in particular are you compiling, the library itself? Or do you see this error when you are trying to build one of the executables (tuners, sampels, tests)?

**Comment by Chidhambararajan** [comment]
I am compiling the whole library from source as per the installation instructions in README

**Comment by Chidhambararajan** [comment]
Sorry , the issue was with a different library , CLBlast Compiled fine

**Comment by StuartIanNaylor** [comment]
I am getting the same but likely my lack of knowledge
```
In file included from /usr/include/CL/cl.h:20,
                 from /usr/include/CL/opencl.h:24,
                 from /home/rock/nvme/CLBlast/include/clblast_c.h:22,
                 from /home/rock/nvme/CLBlast/samples/haxpy.c:24:
/usr/include/CL/cl_version.h:22:9: note: '#pragma message: cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 300 (OpenCL 3.0)'
   22 | #pragma message("cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 300 (OpenCL 3.0)")
      |         ^~~~~~~
[ 80%] Linking C executable clblast_sample_haxpy_c
/usr/bin/ld: CMakeFiles/clblast_sample_haxpy_c.dir/samples/haxpy.c.o: in function `main':
haxpy.c:(.text.startup+0x128): undefined reference to `HalfToFloat'
/usr/bin/ld: haxpy.c:(.text.startup+0x138): undefined reference to `HalfToFloat'
/usr/bin/ld: haxpy.c:(.text.startup+0x144): undefined reference to `HalfToFloat'
/usr/bin/ld: haxpy.c:(.text.startup+0x310): undefined reference to `HalfToFloat'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/clblast_sample_haxpy_c.dir/build.make:105: clblast_sample_haxpy_c] Error 1
make[1]: *** [CMakeFiles/Makefile2:473: CMakeFiles/clblast_sample_haxpy_c.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
```
