### ISSUE TITLE
BLAS/CBLAS replacement using symlinking

### ISSUE THREAD

**Issue by epsilon-0** [CNugteren/CLBlast#401]
I've been trying to understand how BLAS/CBLAS works and was wondering how much of a drop in replacement this is.

I saw the previous issues where someone had symlinked `libcblas.so.3` to `libclblast.so` and it seemed to work (bar the weird lapack errors).

My question was, can I similarly symink it to `libcblas.so.3`? So that both blas and cblas are provided by CLBlast?

**Comment by CNugteren** [comment]
CLBlast doesn't implement all methods in BLAS so it might not work as a 100% drop-in. Also, it is really not recommended to be used like that for speed reasons, only in specific use-cases (e.g. only large enough level-3 operations like matrix-multiplication). For a bit more info, see here: https://github.com/CNugteren/CLBlast/blob/master/doc/bindings.md#plain-c-netlib-blas-api

I'm not sure how to answer your question though. You say someone did it and it worked? Not sure about the difference between cblas and blas.

**Comment by epsilon-0** [comment]
I was referring to https://github.com/CNugteren/CLBlast/issues/326 and https://github.com/CNugteren/CLBlast/issues/94

**Comment by epsilon-0** [comment]
Thats a bit unfortunate but no worries.
Thanks for informing.
