### ISSUE TITLE
Titan V tuning results..

### ISSUE THREAD

**Issue by oscarbg** [CNugteren/CLBlast#404]
Hi,
hope you can add for others to enjoy..
I just run all clblast_tuner_* executables from default build and attach all the json files, using latest 455.32 drivers:
[tuningtitanv.zip](https://github.com/CNugteren/CLBlast/files/5434479/tuningtitanv.zip)

**Comment by oscarbg** [comment]
seems I was too fast and didn't read the tuning guide so these are only single precision results.. more to follow..

**Comment by CNugteren** [comment]
Thanks for sharing the tuning results. When they are complete, please share them in this other thread #1. Thanks!
