### ISSUE TITLE
the fastest gemm not using local groups?

### ISSUE THREAD

**Issue by iperov** [CNugteren/CLBlast#406]
I am creating ML lib from scratch using pure python with opencl ctypes interface.
Currently I am using GEMM11 from CNugteren/myGEMM
CLBlast source code is hard to investigate and port the code.
Can you please tell me, do you have better version of GEMM than GEMM11 which does not use local groups in the code?

**Comment by CNugteren** [comment]
What do you mean with "local groups"? OpenCL workgroups? I don't think you can 'not use them', right? Or do you mean local memory perhaps? If that is the case then the answer is yes: the tuning parameters `SA` and `SB` control the use of that. And yes, the kernels in CLBlast are more optimized than those in the tutorial.

If you just want a good kernel for a specific configuration, you could first run the `clblast_tuner_xgemm` tuner, see what parameters you get, and then prune the CLBlast code till you have a small readable kernel without the things you don't need. For the GEMM kernel that makes assumptions about matrices being a certain size and so on (similar to the myGEMM tutorial), you can take these files as your kernel and concatenate them in one big file and prune what you don't need (given your tuning parameters):
https://github.com/CNugteren/CLBlast/blob/master/src/kernels/common.opencl
https://github.com/CNugteren/CLBlast/blob/master/src/kernels/level3/level3.opencl
https://github.com/CNugteren/CLBlast/blob/master/src/kernels/level3/xgemm_part1.opencl
https://github.com/CNugteren/CLBlast/blob/master/src/kernels/level3/xgemm_part2.opencl
https://github.com/CNugteren/CLBlast/blob/master/src/kernels/level3/xgemm_part3.opencl
https://github.com/CNugteren/CLBlast/blob/master/src/kernels/level3/xgemm_part4.opencl
The entry point is in the last file, specifically [here](https://github.com/CNugteren/CLBlast/blob/master/src/kernels/level3/xgemm_part4.opencl#L99).

**Comment by iperov** [comment]
can you please check out my matmul 
https://github.com/iperov/litenn/blob/master/litenn/core/op/matmul.py
and make it faster without using local mem fence?

**Comment by CNugteren** [comment]
Sorry, I don't have time to go through and optimize your code. You can do what I suggested above, or look at my [GEMM tutorial](https://cnugteren.github.io/tutorial/pages/page1.html), or read through the [CLBlast paper](https://arxiv.org/pdf/1705.05249.pdf).
