### ISSUE TITLE
Tuner failing on xdot and xaxpy

### ISSUE THREAD

**Issue by talarcon** [CNugteren/CLBlast#418]
Hi, I've been trying to run the tuner on my gpu (RTX 2070) but it's seems that this two processes have something wrong with the settings. The error is 

Debug Assertion Failed!
Program: CLBlast\build-ninja\clblast_tuner_xdot.exe
File: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\vector
Line: 1508
Expression: vector subscript out of range 

It's in file src/tuning/tuning.cpp:286, vector's size (local and global) is one.

**Comment by talarcon** [comment]
If something more is needed just let me know.
btw thanks for this awesome library.

**Comment by CNugteren** [comment]
Thank you for opening this issue. I had a quick look at the code and indeed it seems this is a bug in the tuner: the code assumes there are at least 2 dimensions in the local/global size, but in this case there is only one. I'll make a fix this weekend.

**Comment by CNugteren** [comment]
I have just merged a fix, could you check again if it works with the latest `master`?

**Comment by talarcon** [comment]
Yes. it's working flawless, thanks!
