### ISSUE TITLE
Tuning to 2nd (non-default) device

### ISSUE THREAD

**Issue by blueberry** [CNugteren/CLBlast#42]
I have 3 GPUS:
1. (default) AMD Radeon R9 270X (Pitcairn)
2. AMD Radeon R9 290X (Hawaii)
3. AMD Radeon R9 290X (Hawaii)

When I start tuning, it automatically uses the default card. I would like to choose one of two Hawaii chips which are more powerful, and which are more important to me. How to do that?

**Comment by CNugteren** [comment]
When the tuner starts, it outputs the 'help' message which shows the chosen (or default) settings, which should also show you what options there are. The command line options *-device* and *-platform* are the ones you are looking for I believe.
