### ISSUE TITLE
is there any "General" General Matrix Multiplication ?

### ISSUE THREAD

**Issue by iperov** [CNugteren/CLBlast#426]
tuned GeMMs are not really general anymore.
Tuned gemms put you before the fact, you either tune them for all devices, or get terrible performance on untuned devices.

I need opencl matmul code that is really generic for any device and provides decent speed, even x4 slower than cublas.
is that possible?

**Comment by CNugteren** [comment]
There is, sort of. CLBlast stores all tuning parameters of all devices (not just the best) in a database. From that information it comes a default for unseen devices of a specific series, vendor, or even for unseen vendors. This last set can be seen as a general set of parameters, and can be found for GEMM [here](https://github.com/CNugteren/CLBlast/blob/master/src/database/kernels/xgemm/xgemm_32.hpp#L193).

The question is of course then how this 'default' is computed. CLBlast uses [this function](https://github.com/CNugteren/CLBlast/blob/4500a03440e2cc54998c0edab366babf5e504d67/scripts/database/database/defaults.py#L169) to compute that, which tries to find a best set that also works on all devices it has seen. Most likely there are better ways to compute this default depending on what you want to achieve.

Not sure if this answers your question entirely, but it should be a starting point for a discussion.
