### ISSUE TITLE
Update cmake OpenCL module's ENV variable

### ISSUE THREAD

**Issue by danyougle** [CNugteren/CLBlast#429]
Hello, I'm glad to have conquered small problems and achieved a compilation on windows 11 with MSVC and android. There's a small diffuculty after AMD's update of OCL SDK lite, that the ENV isn't called OPENCL_ROOT but OCL_ROOT. Cmake developers got the notice and modified the definition of CL finding module. custom CL.cmake line 27, and cmake stock module line 87

reference here:

https://gitlab.kitware.com/cmake/cmake/-/merge_requests/1562

so it's also nice to change accordingly. One alternative is, discard the project custom FindOpenCL.cmake and call the stock module of cmake, but you'll need to raise the version requirement then.

What is your preference?

**Comment by CNugteren** [comment]
I would say the easiest is to add a single new line to the FindOpenCL in this repository, right? So add a new line `  $ENV{OCL_ROOT}` just after
https://github.com/CNugteren/CLBlast/blob/master/cmake/Modules/FindOpenCL.cmake#L27. If you are willing to make that PR that would be great :+1:

**Comment by danyougle** [comment]
> I would say the easiest is to add a single new line to the FindOpenCL in this repository, right? So add a new line ` $ENV{OCL_ROOT}` just after https://github.com/CNugteren/CLBlast/blob/master/cmake/Modules/FindOpenCL.cmake#L27. If you are willing to make that PR that would be great 👍

Good, and if I understand PR correctly, I made an edit on the mentioned line and made a pull request per click. now it's on the "open pull requests" tab. Hope it works fine. Thanks for the hint.

**Comment by CNugteren** [comment]
Resolved in https://github.com/CNugteren/CLBlast/pull/430
