### ISSUE TITLE
Calling CLBlast functions and choosing non-default device

### ISSUE THREAD

**Issue by blueberry** [CNugteren/CLBlast#43]
I am trying to use CLBlast from Clojure through JOCLBlast. Quite exotic setup. Now, the problem that I have is that I have a Clojure BLAS library that already does lots of opencl stuff (that I would like to reuse) AND it is OpenCL 2.0 only. This is important because of my 3 GPUs, the 1st (default) is OpenCL 1.2 and 2nd and 3rd are OpenCL 2.0. This led me to (maybe) discover an issue with CLBlast:

I create a queue for the 2nd GPU, and I am trying to call a CLBlast method with that queue. I get the error 2048, which indicated that kernel failed to enqueue. I suspect that this is because CLBlast tries to use a program that was compiled for the 1st GPU, so the queue that I supplied is invalid in that context.

Now, is there a way to choose the GPU (context, device) that CLBlast should use, or it defaults to the 1st one? I can't see methods related to setup in the `clblast_c.h` or `clblast.h`. Is it important at all? I am not sure about the inner workings of CLBlast, but it is the only thing that I could think of...

EDIT: I know that there is an option to choose the device in the tuning phase during the build. I need to choose device(s) in the client program, once libclblas has been built and is used as a provided binary.

**Comment by CNugteren** [comment]
CLBlast determines the OpenCL device and context from the queue supplied to it. It will compile the kernel on-the-fly specific for that device: there is no set-up phase of CLBlast. However, there is a caching mechanism which will store the compiled kernel in case the same routine is called later on.

Perhaps something goes wrong with the caching? I checked just now and caching is done per kernel per OpenCL device (based on its 'name'). To check whether this is a caching issue: could you verify whether it actually works the first time? And are you sure this is a multi-device related issue - perhaps something else is wrong?

**Comment by blueberry** [comment]
I am not sure that this is multi-device issue, since I use CLBlast via JOCLBlast, so I have just tried to actually use the library and am still investigating the API. As I already have lots of (tested) code that handles buffers and devices, I suspected that the error was caused by the command queue discrepancy. I'll try to use CLBlas from the 1st device tomorrow (it requires a bit more low-level code) to see whether that works, and will report the results here.

BTW, does that mean that CLBlast will calls several info functions each time each BLAS function is invoked? How much overhead is there for BLAS calls in the loop, for non-huge buffers? Is there something to gain if caching is done per queue?

**Comment by blueberry** [comment]
Dear Cedric,

After restarting the whole REPL and JVM, which reloads libclblast, I can confirm that all GPUs work well, so the problem that I had was on the side of my code.

I'll open another issue regards caching.

Thank you again for the great library and quick responses.
