### ISSUE TITLE
Cannot run on Windows with Nvidia GPUs

### ISSUE THREAD

**Issue by HerpDerpongton** [CNugteren/CLBlast#433]
I am trying to run the example [samples/sgemm.cpp](https://github.com/CNugteren/CLBlast/blob/master/samples/sgemm.cpp) on 
Windows 10 with a Nvidia graphics card. I have obtained the [cl.hpp](https://www.khronos.org/registry/OpenCL/api/2.1/cl.hpp). The makefile is simply as follows:
    
    a.exe: sgemm.cpp
        g++ sgemm.cpp -lopencl -lclblast -O0 -g -DCL_TARGET_OPENCL_VERSION=300

I have the Nvidia CUDA toolkit v11.6 installed and the include directory is on the environment variable `CPATH` so that it is found by `g++`. Furthermore, the compiler is part of a Mingw-w64 installation on which `clblast` is installed. 

The problem is that the compilation seems to succeed, but as soon as I try executing the `a.exe` it crashes without any error message. Similarly, attaching `gdb` does not help either, because the program exits immediatedly and `gdb` prints

> During startup the program exited with code 0xc0000135.

**Comment by CNugteren** [comment]
Are you able to run any other OpenCL programs? Did you manage to run something like `clinfo`? Or one of the OpenCL examples from the NVIDIA SDK?

**Comment by HerpDerpongton** [comment]
I have been able to run the [x64 "OpenCL Multi Threads" example](https://developer.nvidia.com/opencl) executable. I cannot compile the code because some header <exception.h> is missing and I cannot find it anywhere.

`clinfo` does not seem to be on the PATH. Do you know where it should be?

**Comment by CNugteren** [comment]
If your SDK doesn't provide a `clinfo` or similar you can also try to compile one from source, e.g. [this one on Github](https://github.com/Oblomov/clinfo). That should give you a lot of debug information and tell you whether your OpenCL installation is fine. If that is the case, then we can continue to see if it is a CLBlast issue.

**Comment by HerpDerpongton** [comment]
I had to remove the `-Werror and -pedantic` flags from the makefile of the `clinfo` you linked to, but afterwards the compilation was successful (but with warnings). An excerpt of the output:

> Number of platforms                               2
   Platform Name                                   NVIDIA CUDA
   Platform Vendor                                 NVIDIA Corporation
  Platform Version                                OpenCL 3.0 CUDA 11.6.99
  Platform Profile                                FULL_PROFILE
...
  Platform Name                                   Intel(R) OpenCL HD Graphics
  Platform Vendor                                 Intel(R) Corporation
  Platform Version                                OpenCL 3.0 
  Platform Profile                                FULL_PROFILE
...
  Platform Name                                   NVIDIA CUDA
Number of devices                                 1
  Device Name                                     NVIDIA GeForce MX450
  Device Vendor                                   NVIDIA Corporation
  Device Vendor ID                                0x10de
  Device Version                                  OpenCL 3.0 CUDA
...
  Platform Name                                   Intel(R) OpenCL HD Graphics
Number of devices                                 1
  Device Name                                     Intel(R) UHD Graphics
  Device Vendor                                   Intel(R) Corporation
  Device Vendor ID                                0x8086
  Device Version                                  OpenCL 3.0 NEO

**Comment by CNugteren** [comment]
Thanks for running `clinfo`, that looks good. So platform 0 and device 0 should be your NVIDIA GPU I guess.

Note that above I said that some builds are failing, this is not true however, they were a year old. The latest builds are running just fine on NVIDIA GPUs, see the badges on top of the [README here](https://github.com/CNugteren/CLBlast#clblast-the-tuned-opencl-blas-library).

So what else can be wrong then? Perhaps you can also try to compile the CLBlast [tests](https://github.com/CNugteren/CLBlast/blob/master/doc/testing.md) or [benchmark clients](https://github.com/CNugteren/CLBlast/blob/master/doc/benchmarking.md) just for the sake of seeing whether nothing works or the issue just lies with the example GEMM code?

One other thing, what happens if you don't compile with `DCL_TARGET_OPENCL_VERSION=300` or set it to 2.0 or even 1.1?

**Comment by HerpDerpongton** [comment]
The problem was that I could not actually build from source because of several other problems which seem to be related to cmake and make. I can give you a more detailed explanation if necessary. Either way, I cannot build the examples as described in the installation guide. Is it possible to build just a single example?

**Comment by HerpDerpongton** [comment]
Regarding the opencl target version, this does not seem to affect the problem.

**Comment by CNugteren** [comment]
> The problem was that I could not actually build from source

Hmm, so the CLBlast library you got was just downloaded from the pre-built CLBlast releases? The Windows ones are built with Microsoft's Visual Studio, while you are running with Mingw. Now I do not know too much about Windows, but it might well be that those are not compatible with each other and might well be the cause of the problem. I would suggest trying to build the whole library from source if you can resolve the issues with CMake and make.

**Comment by HerpDerpongton** [comment]
I am creating the build directory, cd to that directory and run `cmake -G "MinGW Makefiles" ..`. Then, I run `make`. But instead of "make making something" I am greeted with "Microsoft Windiws [Version ...] ...". That is, this has opened another shell window inside the shell window for some reason.

**Comment by HerpDerpongton** [comment]
This time, the problem was that the `libclblast.dll` could not be found by the executable. If I copy it next to it it finally works. However, I doubt that this was the problem before because the dll could be found on path. `ldd` confirmed that. To verify that I copied the packaged dll next to the executable. Then it fails again. Overall, I think you were right that this is a compatibility issue between the compilers. 
I am wondering however, if the binaries provided for mingw should be build with Visual Studio...

**Comment by CNugteren** [comment]
> Overall, I think you were right that this is a compatibility issue between the compilers.

OK, so that closes this issue, right? I don't think there is something in CLBlast that we can do about this, but rather something in your compiler/linker settings.

>  I am wondering however, if the binaries provided for mingw should be build with Visual Studio...

What do you mean with this?

**Comment by HerpDerpongton** [comment]
> > I am wondering however, if the binaries provided for mingw should be build with Visual Studio...

> What do you mean with this?

I was wondering why the Mingw package comes with the libraries built with the visual studio compiler because clearly, the resulting binary is incompatible with the g++ compiler.

Either way, the issue is closed now.
