### ISSUE TITLE
Windows test builds failing

### ISSUE THREAD

**Issue by CNugteren** [CNugteren/CLBlast#435]
Just now I updated the list of badges for ArrayFire test machines on which CLBlast is automatically tested. However, I noticed that both of the Windows builds fail because they can't find a normal CPU BLAS library for reference. The issue is a bit weird, because the CLBlast CMake code does find something, but it states `-- Found CBLAS: None  `, indicating something is wrong. This results in failure as the `cblas.h` header can't be found anymore, e.g. [here](https://ci.arrayfire.org:8010/#/builders/48/builds/8).

@umar456 , any idea what might be going on on those machines? Or is there perhaps something wrong [here](https://github.com/CNugteren/CLBlast/blob/master/cmake/Modules/FindCBLAS.cmake)?

**Comment by umar456** [comment]
Looks like its searching for MKL_ROOT, but MKL setup_vars.sh creates an MKLROOT environment variable. Let me take a look on the system and send you a fix.

Have you looked at the default CMake's FindBLAS.cmake script. Any reason you went with this one?

**Comment by CNugteren** [comment]
> Have you looked at the default CMake's FindBLAS.cmake script. Any reason you went with this one?

That's 6 years ago or so, I don't remember...

> Looks like its searching for MKL_ROOT, but MKL setup_vars.sh creates an MKLROOT environment variable. Let me take a look on the system and send you a fix.

Thanks for looking into this. Alternatively I can also change my FindBLAS script to search for `MKLROOT` as well.

**Comment by CNugteren** [comment]
Builds are passing since #437 was merged, thanks for that fix @umar456. E.g.:
https://ci.arrayfire.org:8010/#/builders/48

Closing this issue.
