### ISSUE TITLE
Adreno 650 device crashed

### ISSUE THREAD

**Issue by Saikatsaha1996** [CNugteren/CLBlast#439]
When i run 
`./clblast_tune_xgemm`

Device screen fully white and device crashed..

**Comment by Saikatsaha1996** [comment]
with checkout `adreno_tryout`
Build error
![Screenshot_2022-06-10-22-17-13-955_com termux](https://user-images.githubusercontent.com/72664192/173113625-da459a27-438f-4207-9e4c-b2af6c1c4b3d.jpg)

**Comment by Saikatsaha1996** [comment]
@CNugteren i don't know why `Adreno` GPU performance too much bad.. actually i am not developer so i cannot calculate kernel optimization maths that's why I sending the link...

`Arm-Mali` GPU working perfectly even i have to device
## 1) Adreno 650 (flagship) 
When i run `./clblast_test_xgemm` adreno device screen white && device crashed ..

## 2) ARM-Mali G52-MC2 (low-end)
When i run `./clblast_test_xgemm` in `ARM-Mali` GPU taken time but working..

I want your knowledge can you please share about Adreno ?

https://developer.qualcomm.com/blog/opencl-optimization-accelerating-epsilon-filter-adreno-gpu

**Comment by Saikatsaha1996** [comment]
I followed Qualcomm Adreno GPUs #228 
But when i run `./clblast_test_xgemm`
`clblast_test_xgemm not found`

I enable in cmake option
`cmake .. -DTUNERS=ON -DSAMPLES=ON -DTESTS=ON -DCLIENTS=ON`

How can I solve it?

**Comment by CNugteren** [comment]
Hmm. Let's see. About the compilation error you get, I think you should remove the function `stod` here: https://github.com/CNugteren/CLBlast/blob/master/src/utilities/android.hpp#L33 (3 lines of code). It was added there because compilers on Android didn't have it implemented, but apparently yours has it.

The clients and tests are indeed not available on Android, this is because they require reference BLAS implementations which are often not available. I believe this is the main reason, but it has been a while. In any case it is hard-coded in the CMakeLists file. You could try to remove the checks (around [this line](https://github.com/CNugteren/CLBlast/blob/master/CMakeLists.txt#L180)) and see what it does, but I can't guarantee anything.

**Comment by Saikatsaha1996** [comment]
> Hmm. Let's see. About the compilation error you get, I think you should remove the function `stod` here: https://github.com/CNugteren/CLBlast/blob/master/src/utilities/android.hpp#L33 (3 lines of code). It was added there because compilers on Android didn't have it implemented, but apparently yours has it.
> 
> The clients and tests are indeed not available on Android, this is because they require reference BLAS implementations which are often not available. I believe this is the main reason, but it has been a while. In any case it is hard-coded in the CMakeLists file. You could try to remove the checks (around [this line](https://github.com/CNugteren/CLBlast/blob/master/CMakeLists.txt#L180)) and see what it does, but I can't guarantee anything.

Really very performance on every adreno device..
Device screen full white, device crashed, rebooting, touch not working.. horrible performance on every adreno GPU..

Mali low-gpu also working but adreno not..

**Comment by Saikatsaha1996** [comment]
> Hmm. Let's see. About the compilation error you get, I think you should remove the function `stod` here: https://github.com/CNugteren/CLBlast/blob/master/src/utilities/android.hpp#L33 (3 lines of code). It was added there because compilers on Android didn't have it implemented, but apparently yours has it.
> 
> The clients and tests are indeed not available on Android, this is because they require reference BLAS implementations which are often not available. I believe this is the main reason, but it has been a while. In any case it is hard-coded in the CMakeLists file. You could try to remove the checks (around [this line](https://github.com/CNugteren/CLBlast/blob/master/CMakeLists.txt#L180)) and see what it does, but I can't guarantee anything.

Sir i want to ask you a noob questions can you able to reply?

Help wanted really!
