### ISSUE TITLE
Context, programs, etc. initialization and cleanup

### ISSUE THREAD

**Issue by blueberry** [CNugteren/CLBlast#44]
I am building a Clojure (JVM) library that uses CLBlast through JOCLBlast. The calling of CLBlast functions works without the need for setup and initialization.

That is great in many cases, especially during development. But, in other cases, there are many context and queue pointers that get created and released, particularly in a long-lived server application.

Now, CLBlast maintains its own cache under the hood, which holds pointers to all resources for all command queues that have been used since the start of the application. In applications that create and destroy queues often, CLBlast would collect a lot of garbage, and thus leak video memory.

Is there a way to handle this in the current CLBlast, and if not, is there a hope in waiting for the addition of initialization/cleanup function to CLBlast (I use it through plain C)? Unfortenately, my C-fu, and especially C++-fu, is not strong enough to implement it myself and contribute in that way.

**Comment by CNugteren** [comment]
OK, I guess that makes sense - I could implement something like a `resetCache` or `clearCache` function?

CLBlast keeps a cache storing all previously compiled kernels per OpenCL device. If there are many devices on a system and many different kernels are executed, this could lead to storing tens (but not much more I guess) compiled kernels. If this really is an issue I will implement a clear-cache function, which should be quite trivial to write.

**Comment by blueberry** [comment]
If you are sure that a kernel for one physical device won't be stored twice or otherwise messed up, then I guess that it would not be an issue.

Just one clarification: CLBlast stores previously compiled *kernels* or *programs* in the cache? I guess (and hope :) ) it is *programs*...

On the other hand, maybe the error that I had with command queues earlier is related to this cache. `clearCache` might be a good option to call just in case. 

How do you handle programs that are built for multiple devices? That is also part of the OpenCL api, although I am not sure how often it is used.

**Comment by CNugteren** [comment]
The cache stores binaries, which contain compiled kernels, but I guess in OpenCL terminology this is what is called a `program`. Anyway, I'll implement a `clearCache()` function soon in case anybody ever needs it. 

I'll also consider implementing a `preCompileAllForDevice(deviceName)` function to pre-compile all CLBlast kernels for a particular device and thus populate the cache.

About your question: CLBlast stores the OpenCL device name along with the binary. So if the binary is suitable for other devices with a different name then it will be recompiled by CLBlast. But that doesn't seem to be a common use case, and even if it is, the performance impact should be minor.

**Comment by blueberry** [comment]
Thank you :)

**Comment by CNugteren** [comment]
There are now cache clean-up functions: `clblast::ClearCompiledProgramCache()` (C++) and `CLBlastClearCompiledProgramCache()` (C).

**Comment by CNugteren** [comment]
There are now also functions to pre-compile all kernels (all precisions, all routines) for a specific device: `clblast::FillCache(const cl_device device_id)` (C++) and `CLBlastFillCache(const cl_device device_id)` (C).

**Comment by blueberry** [comment]
Yes, if the cache is per-context, then you can store the final version of programs and the execution overhead is negligible. That's what I've been doing in neanderthal.

**Comment by CNugteren** [comment]
I've added a per-context program cache next to the per-device binary cache. If a matching program cannot be found, the binary cache will be searched. If it also doesn't contain the specific kernel, it will be compiled from source and both the binary and the program will be added to the cache.

Since the `ClearCache` and `FillCache` functions are now available, I guess I can close this issue.

**Comment by blueberry** [comment]
Are you sure that that solves the problem? The problem with the old cache precisely was caused by a program that was found in the per-device cache, but was invalid with supplied context. In your description, it looks that the problem will still be the same, since the program is going to be found in step 2, but it will be invalid in a new context (that uses the same device as the old context).
