### ISSUE TITLE
Request: A new minor release?

### ISSUE THREAD

**Issue by gspr** [CNugteren/CLBlast#441]
There seems to have been a lot of small bugfixes and tuning updates since 1.5.2 was released more than a year and a half ago. Would it be possible to make a minor 1.5.3 release to reflect that? (I understand that you don't have a lot of time to put into CLBlast development these days, but hopefully a bug fix release isn't too much.)

My motivation comes from wearing my Debian hat: It would be nice if Debian 12 could ship with a version of CLBlast that contains the last years' worth of tuning updates and bug fixes. Debian 12 goes into freeze in mid-February 2023, after which I'll not be able to upload an updated CLBlast package. So any bugfix release before February would be most welcome.

**Comment by CNugteren** [comment]
Thanks for reminding me. A while ago I thought about making a new release but apparently I never did. I'll make sure this is done within the coming two weeks.

**Comment by CNugteren** [comment]
This is now done, version 1.5.3 is released: https://github.com/CNugteren/CLBlast/releases/tag/1.5.3 :partying_face:
