### ISSUE TITLE
ARM MALI G-610 MC6 GPU crashed with FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7bf2bacf48) Aborted

### ISSUE THREAD

**Issue by Saikatsaha1996** [CNugteren/CLBlast#450]
### GPU ARM MALI G-610 MC6

`clblast_tuner_xgemm test crash (aborted)`
![Screenshot_2022-12-13-02-40-19-687_com termux](https://user-images.githubusercontent.com/72664192/207155229-ca04f493-e36f-4968-b206-ed13ba0bebd1.jpg)
![Screenshot_2022-12-13-02-39-57-687_com termux](https://user-images.githubusercontent.com/72664192/207155241-2ead062d-cf07-4af0-b384-8de7668a6d60.jpg)
![Screenshot_2022-12-13-02-39-51-836_com termux](https://user-images.githubusercontent.com/72664192/207155244-8e43ada0-e0ca-4785-a569-aecc7eca9767.jpg)

**Comment by Saikatsaha1996** [comment]
![IMG_20221213_031016](https://user-images.githubusercontent.com/72664192/207160745-cf9dd3ba-c922-4659-a621-aeff3a95645b.jpg)

**Comment by CNugteren** [comment]
It seems you have two issues:
1. The tuner crashes on device. In this case I would try reducing the set of parameters tested greatly through changing [these lines](https://github.com/CNugteren/CLBlast/blob/master/src/tuning/kernels/xgemm.hpp#L79-L158). That way you can find out which parameter (combinations) crash on your device, and you can exclude them from the tuning procedure. It is likely to be the larger values that make it crash, try excluding those first. Or try to find out by looking at the last successful printed line.
2. The sample programs crash. However, they do complete the CLBlast call successfully it seems, so this is perhaps not related to CLBlast? Does this also happen with other OpenCL programs? And before we can say anything further, try localizing the line in which it crashes first.

Hope this helps.

**Comment by Saikatsaha1996** [comment]
> It seems you have two issues:
> 
> 1. The tuner crashes on device. In this case I would try reducing the set of parameters tested greatly through changing [these lines](https://github.com/CNugteren/CLBlast/blob/master/src/tuning/kernels/xgemm.hpp#L79-L158). That way you can find out which parameter (combinations) crash on your device, and you can exclude them from the tuning procedure. It is likely to be the larger values that make it crash, try excluding those first. Or try to find out by looking at the last successful printed line.
> 2. The sample programs crash. However, they do complete the CLBlast call successfully it seems, so this is perhaps not related to CLBlast? Does this also happen with other OpenCL programs? And before we can say anything further, try localizing the line in which it crashes first.
> 
> Hope this helps.

Not responding!

![Screenshot_2022-12-19-16-47-07-599_com termux](https://user-images.githubusercontent.com/72664192/208414613-d89e32a9-9126-495c-94b4-7fa372fb037b.jpg)

**Comment by CNugteren** [comment]
> Not responding!

What do you mean?

> How much time it will take for make alltuners ?

That entirely depends on the speed of your device, so I can't say. You can remove some parameters if you want to make it run quicker. See my previous post for explanations on how to do that.

**Comment by Saikatsaha1996** [comment]
> > Not responding!
> 
> What do you mean?
> 
> > How much time it will take for make alltuners ?
> 
> That entirely depends on the speed of your device, so I can't say. You can remove some parameters if you want to make it run quicker. See my previous post for explanations on how to do that.

Still now freezing.. Not completed..

**Comment by alexfarseer** [comment]
I was having this same issue. I put it into `gdb` backtrace and this is what I got:

```
(gdb) bt                                             #0  0x0000007fefbcc1f4 in abort ()                      from /apex/com.android.runtime/lib64/bionic/libc.so
#1  0x0000007fefbce080 in __fortify_fatal(char const*, ...) ()                                               from /apex/com.android.runtime/lib64/bionic/libc.so
#2  0x0000007fefc3c610 in HandleUsingDestroyedMutex(pthread_mutex_t*, char const*) ()                        from /apex/com.android.runtime/lib64/bionic/libc.so
#3  0x0000007fefc3c4a4 in pthread_mutex_lock ()         from /apex/com.android.runtime/lib64/bionic/libc.so
#4  0x0000007ddfafdffc in std::__1::mutex::lock() ()    from /system/lib64/libc++.so                      #5  0x0000007d5b7c83dc in clcc::CompilerContext::delete_program(clcc::ProgramContext&) ()
   from /data/data/com.termux/files/usr/opt/vendor/lib/libOpenCL.so
#6  0x0000007d5b758084 in mcl_gpu_program::~mcl_gpu_program() ()
   from /data/data/com.termux/files/usr/opt/vendor/lib/libOpenCL.so
#7  0x0000007d5b76cf7c in mcl_program::~mcl_program() ()                                                     from /data/data/com.termux/files/usr/opt/vendor/lib/libOpenCL.so
#8  0x0000007d5b7445f4 in mcl_mem::deleter() const   --Type <RET> for more, q to quit, c to continue without paging--                                              ()
   from /data/data/com.termux/files/usr/opt/vendor/lib/libOpenCL.so                                       #9  0x0000007d5b74bcec in clReleaseProgram ()
   from /data/data/com.termux/files/usr/opt/vendor/lib/libOpenCL.so                                       #10 0x0000007ff6a6225c in clReleaseProgram ()
   from /data/data/com.termux/files/usr/lib/libOpenCL.so
#11 0x0000007ff28d3d30 in clblast::Program::~Program() ()
   from /data/data/com.termux/files/usr/stow/clblast-1.5.3/lib/libclblast.so.1.5.3
#12 0x0000007ff28e5518 in clblast::Cache<std::__ndk1::tuple<_cl_context*, _cl_device_id*, clblast::Precision, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > >, std::__ndk1::shared_ptr<clblast::Program> >::~Cache() ()    from /data/data/com.termux/files/usr/stow/clblast-1.5.3/lib/libclblast.so.1.5.3
#13 0x0000007fefc3ef7c in __cxa_finalize ()
   from /apex/com.android.runtime/lib64/bionic/libc.so                                                    #14 0x0000007fefc3139c in exit ()                       from /apex/com.android.runtime/lib64/bionic/libc.so                                                    #15 0x0000007fefbc4608 in __libc_init ()                from /apex/com.android.runtime/lib64/bionic/libc.so
```

So I removed the `clReleaseProgram` line from `clpp11.hpp`. And the problem went away. This is the code I removed:

```
~Program() {
  #ifndef _MSC_VER // causes an access violation under Windows when the driver is already unloaded
    if (program_) { CheckErrorDtor(clReleaseProgram(program_)); }
  #endif
}
```

**Comment by Saikatsaha1996** [comment]
> I was having this same issue. I put it into `gdb` backtrace and this is what I got:
> 
> ```
> (gdb) bt                                             #0  0x0000007fefbcc1f4 in abort ()                      from /apex/com.android.runtime/lib64/bionic/libc.so
> #1  0x0000007fefbce080 in __fortify_fatal(char const*, ...) ()                                               from /apex/com.android.runtime/lib64/bionic/libc.so
> #2  0x0000007fefc3c610 in HandleUsingDestroyedMutex(pthread_mutex_t*, char const*) ()                        from /apex/com.android.runtime/lib64/bionic/libc.so
> #3  0x0000007fefc3c4a4 in pthread_mutex_lock ()         from /apex/com.android.runtime/lib64/bionic/libc.so
> #4  0x0000007ddfafdffc in std::__1::mutex::lock() ()    from /system/lib64/libc++.so
> #5  0x0000007d5b7c83dc in clcc::CompilerContext::delete_program(clcc::ProgramContext&) ()
>    from /data/data/com.termux/files/usr/opt/vendor/lib/libOpenCL.so
> #6  0x0000007d5b758084 in mcl_gpu_program::~mcl_gpu_program() ()
>    from /data/data/com.termux/files/usr/opt/vendor/lib/libOpenCL.so
> #7  0x0000007d5b76cf7c in mcl_program::~mcl_program() ()                                                     from /data/data/com.termux/files/usr/opt/vendor/lib/libOpenCL.so
> #8  0x0000007d5b7445f4 in mcl_mem::deleter() const   --Type <RET> for more, q to quit, c to continue without paging--                                              ()
>    from /data/data/com.termux/files/usr/opt/vendor/lib/libOpenCL.so
> #9  0x0000007d5b74bcec in clReleaseProgram ()
>    from /data/data/com.termux/files/usr/opt/vendor/lib/libOpenCL.so
> #10 0x0000007ff6a6225c in clReleaseProgram ()
>    from /data/data/com.termux/files/usr/lib/libOpenCL.so
> #11 0x0000007ff28d3d30 in clblast::Program::~Program() ()
>    from /data/data/com.termux/files/usr/stow/clblast-1.5.3/lib/libclblast.so.1.5.3
> #12 0x0000007ff28e5518 in clblast::Cache<std::__ndk1::tuple<_cl_context*, _cl_device_id*, clblast::Precision, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > >, std::__ndk1::shared_ptr<clblast::Program> >::~Cache() ()    from /data/data/com.termux/files/usr/stow/clblast-1.5.3/lib/libclblast.so.1.5.3
> #13 0x0000007fefc3ef7c in __cxa_finalize ()
>    from /apex/com.android.runtime/lib64/bionic/libc.so
> #14 0x0000007fefc3139c in exit ()                       from /apex/com.android.runtime/lib64/bionic/libc.so
> #15 0x0000007fefbc4608 in __libc_init ()                from /apex/com.android.runtime/lib64/bionic/libc.so
> ```
> 
> So I removed the `clReleaseProgram` line from `clpp11.hpp` and the problem went away. This is the code I removed:
> 
> ```
> ~Program() {
>   #ifndef _MSC_VER // causes an access violation under Windows when the driver is already unloaded
>     if (program_) { CheckErrorDtor(clReleaseProgram(program_)); }
>   #endif
> }
> ```

Thank you it's working..

**Comment by CNugteren** [comment]
@alexfarseer, thanks for debugging it and posting the solution. I've now applied your suggestion here as well: https://github.com/CNugteren/CLBlast/pull/462
