### ISSUE TITLE
Some constants are different than in cblas

### ISSUE THREAD

**Issue by blueberry** [CNugteren/CLBlast#46]
This might not surface in CLBlast directly, since Layout, Transpose, etc. are enums, but will bite users that use CLBlas from some other language/environment.

In cblas, row_major is 101, column_major 102.
in CLBlast, these are enums, but as numbers, I believe kRowMajor is 0, while kColMajor is 1 (at least they are when CLBlast is used from Java as an external library).

Is this intentional, and if not, would the right solution be to define Layout, Transpose, etc. to use the same  constrants as cblas standard?

**Comment by CNugteren** [comment]
I am aware of the difference (I needed a function to convert them to cblas format), but I haven't thought of simply unifying them. I think it is indeed a good idea to adopt this convention as well in CLBlast.

You can expect this change in the next release.

**Comment by CNugteren** [comment]
The enum constants are now exactly the same as in cblas. The changes are now in the `development` branch and will  be included in the next release:
```
enum class Layout { kRowMajor = 101, kColMajor = 102 };
enum class Transpose { kNo = 111, kYes = 112, kConjugate = 113 };
enum class Triangle { kUpper = 121, kLower = 122 };
enum class Diagonal { kNonUnit = 131, kUnit = 132 };
enum class Side { kLeft = 141, kRight = 142 };
```
