### ISSUE TITLE
ArrayFire test builds are failing

### ISSUE THREAD

**Issue by CNugteren** [CNugteren/CLBlast#463]
Somewhere between 4 months ago and one month ago something changed on the ArrayFire CI that caused all builds to be failing. Example device history: https://ci.arrayfire.org:8010/#/builders/clblast-linux-nvidia-t4 and example failed job: https://ci.arrayfire.org:8010/#/builders/39/builds/64

The error message is:
```
ninja: error: '/opt/intel/mkl/lib/intel64/libmkl_rt.so', needed by 'clblast_test_diagnostics', missing and no known rule to make it
```
This is caused by the way CMake is invoked:
```
cmake -G Ninja -DCMAKE_INSTALL_PREFIX:STRING=package -DCMAKE_BUILD_TYPE:STRING=Release -DBUILD_SHARED_LIBS:BOOL=ON -DCLIENTS:BOOL=OFF -DSAMPLES:BOOL=ON -DTESTS:BOOL=ON -DCBLAS_INCLUDE_DIRS:PATH=/opt/intel/mkl/include -DCBLAS_LIBRARIES:FILEPATH=/opt/intel/mkl/lib/intel64/libmkl_rt.so ..
```
Perhaps MKL is no longer installed, or it is in a different location?

Could someone from ArrayFire perhaps have a look? @umar456 or @9prady9? Many thanks :pray:

**Comment by CNugteren** [comment]
The Windows builds now compile fine, but then all tests segfault. E.g.:
https://ci.arrayfire.org:8010/#/builders/48/builds/29/steps/5/logs/stdio

Any idea what might be going on there?

**Comment by umar456** [comment]
I was able to solve the segfaults in the r9 machine(its actually a Vega GPU but I need to rename the job). I still have to figure out the issue with the other build. I will look at it again soon.

**Comment by umar456** [comment]
Fixed the last windows builder. I am not sure why CMake was selecting the GNU version of the Intel LLVM compiler. I forced the selection of the Microsoft compiler for that build

**Comment by CNugteren** [comment]
Great, everything works again. And again, thanks for allowing CLBlast to use your infrastructure, it is a great help! :pray: 

![arrayfire](https://github.com/CNugteren/CLBlast/assets/1162108/ea042bcf-500b-4749-a8b2-ab891d7b7cab)
