### ISSUE TITLE
Error during tuning for AMD R9 290X

### ISSUE THREAD

**Issue by blueberry** [CNugteren/CLBlast#48]
My card 0 (default) is AMD R9 270X. I tuned that without problems.

Card 1 is AMD R9 290X. I set DEFAULT_DEVICE to 1, and tune the card using the same steps as for 270X. Everything goes fine until Xgemm tuners. They fail without much information (I include what I see in console below). An interesting thing is that in multiple runs they never fail at the same step. Here it is at step 20, but other times were 76 or some other number. It never reaches the end. I also tried with  device 2 (my third card, also 290X) and I also get an error. Another curious fact is that 290X is OpenCL 2.0 capable while 270X is 1.2, so the card with less hardware features passes while the better card fails. Also sgemm WORKS when compiled and used through JOCLBlast and Neanderthal...

```bash
* Options given/available:
    -platform 0 [=default]
    -device 1 
    -precision 32 (single) [=default]
    -m 1024 [=default]
    -n 1024 [=default]
    -k 1024 [=default]
    -alpha 2.000000 [=default]
    -beta 2.000000 [=default]
    -fraction 2048.000000 [=default]


[==========] Initializing on platform 0 device 1
[==========] Device name: 'Hawaii' (OpenCL 2.0 AMD-APP (1912.5))

[----------] Testing reference Xgemm
[ RUN      ] Running Xgemm
[       OK ] Completed Xgemm (25 ms) - 1 out of 1

[----------] Testing kernel Xgemm
[ RUN      ] Running Xgemm
[       OK ] Completed Xgemm (3 ms) - 1 out of 110
[ RUN      ] Running Xgemm
[       OK ] Completed Xgemm (2 ms) - 2 out of 110
[ RUN      ] Running Xgemm
[       OK ] Completed Xgemm (3 ms) - 3 out of 110
[ RUN      ] Running Xgemm
[       OK ] Completed Xgemm (1 ms) - 4 out of 110
[ RUN      ] Running Xgemm
[       OK ] Completed Xgemm (3 ms) - 5 out of 110
[ RUN      ] Running Xgemm
[       OK ] Completed Xgemm (1 ms) - 6 out of 110
[ RUN      ] Running Xgemm
[       OK ] Completed Xgemm (2 ms) - 7 out of 110
[ RUN      ] Running Xgemm
[       OK ] Completed Xgemm (1 ms) - 8 out of 110
[ RUN      ] Running Xgemm
[       OK ] Completed Xgemm (3 ms) - 9 out of 110
[ RUN      ] Running Xgemm
[       OK ] Completed Xgemm (1 ms) - 10 out of 110
[ RUN      ] Running Xgemm
[       OK ] Completed Xgemm (3 ms) - 11 out of 110
[ RUN      ] Running Xgemm
[       OK ] Completed Xgemm (2 ms) - 12 out of 110
[ RUN      ] Running Xgemm
[       OK ] Completed Xgemm (1 ms) - 13 out of 110
[ RUN      ] Running Xgemm
[       OK ] Completed Xgemm (2 ms) - 14 out of 110
[ RUN      ] Running Xgemm
[       OK ] Completed Xgemm (2 ms) - 15 out of 110
[ RUN      ] Running Xgemm
[       OK ] Completed Xgemm (102 ms) - 16 out of 110
[ RUN      ] Running Xgemm
[       OK ] Completed Xgemm (2 ms) - 17 out of 110
[ RUN      ] Running Xgemm
[       OK ] Completed Xgemm (3 ms) - 18 out of 110
[ RUN      ] Running Xgemm
[       OK ] Completed Xgemm (2 ms) - 19 out of 110
[ RUN      ] Running Xgemm
[       OK ] Completed Xgemm (1 ms) - 20 out of 110
CMakeFiles/alltuners.dir/build.make:57: recipe for target 'CMakeFiles/alltuners' failed
make[3]: *** [CMakeFiles/alltuners] Segmentation fault (core dumped)
CMakeFiles/Makefile2:223: recipe for target 'CMakeFiles/alltuners.dir/all' failed
make[2]: *** [CMakeFiles/alltuners.dir/all] Error 2
CMakeFiles/Makefile2:230: recipe for target 'CMakeFiles/alltuners.dir/rule' failed
make[1]: *** [CMakeFiles/alltuners.dir/rule] Error 2
Makefile:214: recipe for target 'alltuners' failed
make: *** [alltuners] Error 2
```

**Comment by CNugteren** [comment]
I suspect that this might be a crash in AMD's OpenCL compiler driver. Or perhaps in the kernel itself, although I have seen many kernel-crashes properly caught and reported by the CLTune tuner.

The reason that this happens at different instances is that CLTune only tests a random subset of all possible configurations, in your case only 110 out of ~225K. Apparently some configurations make either the compiler or the kernel crash. And apparently the default values for this device  (`include/internal/database/xgemm.h`) work well.

How I would debug this myself:
Open `tuning/xgemm.cc` and remove (or perhaps just keep?) some of the more extreme tuning parameter values, as found between lines 63 and 76. The meaning of these values can be found at the top of the kernel file itself in `src/kernels/level3/xgemm_part1.opencl`. For example, you could first go for a much smaller subset and see if it works:
```
    tuner.AddParameter(id, "MWG", {16, 32});
    tuner.AddParameter(id, "NWG", {16, 32});
    tuner.AddParameter(id, "KWG", {16, 32});
    tuner.AddParameter(id, "MDIMC", {8, 16, 32});
    tuner.AddParameter(id, "NDIMC", {8, 16, 32});
    tuner.AddParameter(id, "MDIMA", {8, 16, 32});
    tuner.AddParameter(id, "NDIMB", {8, 16, 32});
    tuner.AddParameter(id, "KWI", {2});
    tuner.AddParameter(id, "VWM", {1, 2});
    tuner.AddParameter(id, "VWN", {1, 2});
    tuner.AddParameter(id, "STRM", {0, 1});
    tuner.AddParameter(id, "STRN", {0, 1});
    tuner.AddParameter(id, "SA", {0, 1});
    tuner.AddParameter(id, "SB", {0, 1});
```
The most extreme parameters are also less likely to yield good results anyway. Note the randomness though: one successful run doesn't mean that you found the cause for the crash; only those actually tested parameter combinations can then be marked as working.

You can also test with a larger or smaller fraction (through e.g. `./clblast_tuner_xgemm -fraction 500`) to test more or less in one run.

**Comment by blueberry** [comment]
I managed to complete xgemm tuning with -fraction 4096 for all precisions. All other tuners were completed without problems. Will post the results in the appropriate issue.
