### ISSUE TITLE
GemmStridedBatched results question

### ISSUE THREAD

**Issue by FloreaMario** [CNugteren/CLBlast#489]
When running clblast’s GemmStridedBatched routine and comparing the results to the cblas_cgemm_batch_strided routine’s results on the same set of input matrices, equal results are obtained.

However, from a mathematical perspective, the results do not seem correct, and I am wondering if you can share any information on the way these results are calculated in clblast’s routine.

Attached below is a screenshot of the input matrices, as well as OUT Matrix C (result corresponds to clblast’s routine) and OUT Matrix cblas_C (results correspond to cblas’s routine).

OUT Matrix C and OUT Matrix cblas_C  are both initialized with the following values:

(3.0, 3.0) (3.1, 3.1) (3.2, 3.2)
<img width="257" alt="MicrosoftTeams-image (21)" src="https://github.com/CNugteren/CLBlast/assets/11064133/6b4ff9c1-0df6-4b1c-b1db-243f5b34bd09">

**Comment by CNugteren** [comment]
Couls you provide a bit more informstion, such as a small snippet similar to the CLBlast samples code examples (or better perhaps: modify one of them to reproduce your quesion). At the very least the whole call to the function would be helpful, perhaps you passed in the wrong arguments or forgot to wait for the call to finish?

**Comment by FloreaMario** [comment]
[cgemm_strided_batched.zip](https://github.com/CNugteren/CLBlast/files/11797705/cgemm_strided_batched.zip)

Attached a test file that reproduces the situation described above. Let me know if I can provide any extra information.

**Comment by CNugteren** [comment]
Thanks for your example code. I could compile and run it. I did notice a few weird things do:
1. Many integer parameters are set as float, e.g. `float m = 1.0;`. I would suggest that you change all those that are (and should be, see the API!) integers to integers.
2. You are setting a single complex value like so: `std::complex<float> host_a(1.0, 1.0);`. However, your code assumes you have two batches, so what you'll need is an `std::vector` (or some other container) with multiple of those, so more something like: `std::array<std::complex<float>, 2> host_a = {{1.0, 1.0}, {1.0, 1.0}}`. I believe this is the core of your problem: you are using a strided version of the CLBlast routine with 2 batches, but you are supplying just a single input.

**Comment by FloreaMario** [comment]
Thanks for the answer. I've made the updates:
[cgemm_strided_batched2.zip](https://github.com/CNugteren/CLBlast/files/11866299/cgemm_strided_batched2.zip)

For  batch count = 2 and
host_a = {{1.0, 1.0}, {1.0, 1.0}, {1.0, 1.0}}
host_b = {{2.0, 2.0}, {2.0, 2.0}, {2.0, 2.0}}
host_c = {{3.0, 3.0}, {3.0, 3.0}, {3.0, 3.0}}, 

I get:
{{-4.0, 10}, {-4.0, 10}, {3.0, 3.0}}

Which doesn't make any sense to me.

**Comment by CNugteren** [comment]
I managed to reproduce your results, thanks for the example program. I can't see any obvious mistakes in your code. However I think the results are correct by the definition of how complex values are multiplied. First of all, your last value is still the original {3.0, 3.0} because you set a batch size of 2. Second, let's talk about the two {-4.0, 10} values.

In CLBlast complex multiplication is defined [here](https://github.com/CNugteren/CLBlast/blob/master/src/kernels/common.opencl#L199) as:
```c++
  #define MulReal(a,b) a.x*b.x - a.y*b.y
  #define MulImag(a,b) a.x*b.y + a.y*b.x
  #define Multiply(c,a,b) c.x = MulReal(a,b); c.y = MulImag(a,b)
```
If we write a * b out for your 1x1 matrices, we get:
```
a* b = {
 1*2 - 1*2 = 0,
 1*2 + 1*2 = 4
}
```
This is indeed not {-4, 10}. However we still need to multiply by alpha:
```
alpha * (a* b) = {
 1*0 - 1*4 = -4,
 1*4 + 1*0 = 4
}
```
And then add the beta * C term:
```
alpha * (a* b) + beta * C= {
 -4 + (1*3 - 1*3) = -4,
 4 + (1*3 + 1*3) = 10
}
```
And there is your final answer.
