### ISSUE TITLE
i(a)max buffer element size dependent on buffer (float/double) type size

### ISSUE THREAD

**Issue by blueberry** [CNugteren/CLBlast#49]
iXamax requires a imax_buffer argument for receiving the result. the result is an  `(u)int`?

https://github.com/CNugteren/CLBlast/blob/development/src/routines/level1/xamax.cc#L53
shows that the buffer is tested by `TestVectorDot`, whose size is either 4 bytes (float) or 8 bytes (double).
Howewer, iamax buffer should not be dependent on whether the X buffer is float or double, since the index is always int. 
This is not a major issue, since simply providing 8 bytes instead of 4 in iDamax works ok, but might be a source of confusion if not well documented.

**Comment by CNugteren** [comment]
You are right, it is supposed to be an `unsigned int`. This is now fixed in the latest development branch.
