### ISSUE TITLE
TestVectorX and relatives in routines.cc ask are broken for subvectors and submatrices

### ISSUE THREAD

**Issue by blueberry** [CNugteren/CLBlast#50]
This can be seen in xgemv.cc. Let's say I have a 2x3 general matrix of floats. It's size is 6*4 = 24 bytes.
Suppose I take the second row of that matrix. It is a vector of dimension 3 with `x_offset=1` and `x_inc=2`. Note that the buffer size for that vector is also 24 bytes, since it is actually the buffer of the matrix.
Now, if I try to use that vector in `sgemv`, it will reach `TestVectorX`, https://github.com/blueberry/CLBlast/blob/development/src/routine.cc#L215.

That line will demand of the `required_size` to be `(n*inc+offset)*data_size`, which is `(3*2+1)*4 = 7*4 = 28`. And then, the routine would fail with kInsufficientMemoryX.

Actually, the real formula should be `((n-1)*inc + 1 + offset)*data_size`, since everything after the last element is not needed by the routines that use the vector.

The same problem is present in TestVectorY, TestMatrixA, TestMatrixB, TestMatrixC and (probably) TestMatrixAP (i didn't use the last one and did not have an opportunity to test it).

the TestMatrixXXX `required_size` should be:
`(ld*(two-1) + one + offset)*data_size`

I would have created a pull request, but I have a strange issue with seeing the changes I make in routines.cc in the built library: I change src/routines.cc, go to build, make clean, make, sudo make install, then go to JOCLBlast and recompile and reinstall it. I still get error -1008, even if I comment out the only call to it... If I intentionally introduce a syntax error in some CLBlast file, the compilation fails, so the build definitely sees the changes. Maybe I am not linking properly to the updated code from Java, but I cannot find where is the problem.

Anyway, I hope you can reproduce this subtle bug and fix it in upstream, so I can do a full rebuild, since it is practically a few minor typo fixes.

**Comment by blueberry** [comment]
Quick update: After the system restart, the updated library is seen in my project. The rest of the post stays.

**Comment by CNugteren** [comment]
You are right, thanks! And I believe the one for the packed matrix is still correct, you cannot have submatrices there I believe. I changed the matrix and vector test functions.

I've made the change in commit `a8f1092` of the `development` branch. A PR would have been nice as well, since that way your contributions are officially credited.

**Comment by blueberry** [comment]
Thanks. Being able to use this incredibly useful and elegant free library is more than enough credit :)
