### ISSUE TITLE
Cuda execution failed，when running clblast_sample_sgemm_cuda, "CUDA NVRTC error: nvrtcCompileProgram: NVRTC_ERROR_INVALID_OPTION"

### ISSUE THREAD

**Issue by luoyin500** [CNugteren/CLBlast#500]
**env:**
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0

**cmake command:**
cmake .. -DCUDA=ON -DOPENCL=OFF -DCMAKE_INSTALL_PREFIX=/home/clblast-linux -LA -DSAMPLES=ON -DTESTS=ON -DCUBLAS=ON

**Testing result:**
/home/CLBlast/build-linux# ./clblast_sample_sgemm_cuda
CLBlast: CUDA NVRTC error: nvrtcCompileProgram: NVRTC_ERROR_INVALID_OPTION
Completed SGEMM in 10.221 ms with status -2040

**Comment by CNugteren** [comment]
Thanks for reporting. Unfortunately I don't have quick access to a machine with an NVIDIA GPU, so I can't test it or reproduce the issue myself. It looks like it is called with invalid options. The list of valid options can be found here (for the latest NVRTC): https://docs.nvidia.com/cuda/nvrtc/index.html#group__options

Perhaps you are compiling for an older GPU with a too new NVRTC (i.e. CUDA compiler driver)? Any device below `compute_50` isn't supported apparently by the latest version. So perhaps you can try to downgrade? In any case, what GPU are you testing on?

If you are willing to do some debugging yourself, perhaps you can apply the following patch and then re-compile and re-run? That should give you more information about which options are actually passed. You can then check in the docs which of those options are invalid.
```patch
diff --git a/src/cupp11.hpp b/src/cupp11.hpp
index edcdc12..5fe491e 100644
--- a/src/cupp11.hpp
+++ b/src/cupp11.hpp
@@ -417,6 +417,7 @@ public:
     auto raw_options = std::vector<const char*>();
     for (const auto &option: options) {
       raw_options.push_back(option.c_str());
+      printf("Option passed to nvrtcCompileProgram: %s\n", option.c_str());
     }
     auto status = nvrtcCompileProgram(*program_, raw_options.size(), raw_options.data());
     CLCudaAPINVRTCError::Check(status, "nvrtcCompileProgram");
```

**Comment by luoyin500** [comment]
Thanks, your suggestion is direct, I'll read it in detail.
