### ISSUE TITLE
[implement details] usm beheavior

### ISSUE THREAD

**Issue by congzhangzh** [CNugteren/CLBlast#501]
Hi Folks,

Will CLBlast use OpenCL USM memory when working with Intel iGPU and/or Intel CPU OpenCL runtime.

I try to make llama.cpp works with CLBlast, which seems to work, but I want to know:

1. CLBlast on cpu will beat MKL? seems not, and because of an unneeded memory copy? and use USM memory will fix it?
2. CLBlast on iGPU beat MKL? seems not, because iGPU is weaker than CPU and even has more process units? or just because of an unneeded memory copy? 

Tks,
Cong

**Comment by CNugteren** [comment]
It is up to the user to provide the memory buffers to the CLBlast API. Thus, whether USM is used or not is up to the user. Same for the question about the unneeded memory copy: that is not inside CLBlast, it is up to the user to handle the OpenCL buffers.

Regarding your questions, I would say:

Q: CLBlast on cpu will beat MKL?
A: No, I think that in most cases MKL will be faster. There could be cases where CLBlast is faster on a CPU though, but that has to be tested and depends on the system and matrix sizes.

Q: CLBlast on iGPU beat MKL?
That depends on how fast your iGPU is compared to your CPU. Should be a simple matter of testing.

Note that CLBlast includes a 'client' (use CMake with `-DCLIENTS=ON`) which can be used to benchmark, and even can automatically compare to MKL or another BLAS library.

I hope this answers your questions.
