### ISSUE TITLE
Accept NULL for event or document otherwise

### ISSUE THREAD

**Issue by psyhtest** [CNugteren/CLBlast#52]
Similar to clBLAS, CLBlast accepts two pointer arguments:
```
cl_command_queue* queue, cl_event* event)
```
However, clBLAS accepts `NULL` for the `event` argument (e.g. see this [code](https://github.com/BVLC/caffe/blob/opencl/src/caffe/greentea/greentea_math_functions.cpp) in the OpenCL branch of Caffe):
```
 &queue, 0, NULL, NULL));
```

This should either be accepted for compatibility with clBLAS or documented.

**Comment by blueberry** [comment]
CLBlasts also accepts NULL since a month ago. It's still in the development branch:
https://github.com/CNugteren/CLBlast/issues/32

**Comment by CNugteren** [comment]
Indeed, it is already supported. Version 0.7.0 - the next release - will be out in a week or so.

That said, you are right that these things should be documented. I'll also work on a proper API documentation.

**Comment by psyhtest** [comment]
@blueberry, @CNugteren Thanks! I'll close this ticket, and will be on a lookout for the next release.
