### ISSUE TITLE
Routines to simply transpose a matrix 

### ISSUE THREAD

**Issue by diverger** [CNugteren/CLBlast#548]
Hi,

Are there a simply routine to transpose a matrix? In CUDA, I use 'cublasSgeam' to do this. But it seems there is not equivalent in clBlast. Any suggestion?

**Comment by CNugteren** [comment]
Yes, there is the `Omatcopy`/`CLBlastSomatcopy` function, see here:
https://github.com/CNugteren/CLBlast/blob/master/doc/api.md#xomatcopy-scaling-and-out-place-transposecopy-non-blas-function
