### ISSUE TITLE
CLBlast development fails for xGEMM with "Matrix A's OpenCL buffer is too small" on Mali

### ISSUE THREAD

**Issue by psyhtest** [CNugteren/CLBlast#55]
I'm testing my [CLBlast integration](https://github.com/dividiti/caffe/tree/CLBlast.support) with the OpenCL branch of Caffe. I am observing multiple failures when using the CLBlast development branch on at least two Mali-T628 based platforms (Odroid XU3 with driver v4.0; Chromebook 2 with driver v6.0). 

I don't understand the error "Matrix A's OpenCL buffer is too small", since the same program works fine with CLBlast built from the 0.6.0. release.

@CNugteren 
To reproduce, please log into dividiti's Odroid XU3 and run e.g.:
```
$ LD_LIBRARY_PATH=/data/install/lib-clblast-dev/lib:/data/install/lib-openblas-v0.2.18/lib:$LD_LIBRARY_PATH \
/data/caffe-dvdt-clblast#55/build/test/test_all.testbin \
--gtest_filter=NetTest/3.TestBackwardWithAccuracyLayer

Setting to use device 0
Note: Google Test filter = NetTest/3.TestBackwardWithAccuracyLayer
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from NetTest/3, where TypeParam = caffe::GPUDevice<double>
[ RUN      ] NetTest/3.TestBackwardWithAccuracyLayer
F0505 22:12:46.621851 16035 greentea_math_functions.cpp:275] Check failed: static_cast<int>(status) == static_cast<int>(clblast::StatusCode::kSuccess) (-1011 vs. 0) GREENTEA ERROR: CLBlast error
*** Check failure stack trace: ***
    @ 0xb6ee3060  (unknown)
    @ 0xb6ee2f5c  (unknown)
    @ 0xb6ee2b78  (unknown)
    @ 0xb6ee4f98  (unknown)
    @ 0xb55d4630  caffe::greentea_gpu_gemm<>()
    @ 0xb562d30c  caffe::InnerProductLayer<>::Forward_gpu()
    @ 0xb5500e84  caffe::Net<>::ForwardFromTo()
    @ 0xb55010c8  caffe::Net<>::Forward()
    @   0x302c34  caffe::NetTest_TestBackwardWithAccuracyLayer_Test<>::TestBody_Impl()
    @   0x3e98dc  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @   0x3e4cfa  testing::Test::Run()
    @   0x3e4d8a  testing::TestInfo::Run()
    @   0x3e4e62  testing::TestCase::Run()
    @   0x3e5060  testing::internal::UnitTestImpl::RunAllTests()
    @   0x3e525c  testing::UnitTest::Run()
    @    0xe2f5c  main
    @ 0xb525e632  (unknown)
Aborted
```
Exactly the same command referring to the 0.6.0 release works absolutely fine: 
```
$ LD_LIBRARY_PATH=/data/install/lib-clblast-0.6.0/lib:/data/install/lib-openblas-v0.2.18/lib:$LD_LIBRARY_PATH \
/data/caffe-dvdt-clblast#55/build/test/test_all.testbin \
--gtest_filter=NetTest/3.TestBackwardWithAccuracyLayer

Setting to use device 0
Note: Google Test filter = NetTest/3.TestBackwardWithAccuracyLayer
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from NetTest/3, where TypeParam = caffe::GPUDevice<double>
[ RUN      ] NetTest/3.TestBackwardWithAccuracyLayer
[       OK ] NetTest/3.TestBackwardWithAccuracyLayer (2447 ms)
[----------] 1 test from NetTest/3 (2447 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (2448 ms total)
[  PASSED  ] 1 test.
```

**Comment by CNugteren** [comment]
What comes to mind is a fix for issue #50 that was applied in commit `a8f1092` of the `development` branch. This is the only thing that changed with respect to checking for proper buffer sizes in GEMM. Perhaps you can try and undo that particular one-line change (at least for matrix A) and see if that somehow fixes it?

**Comment by blueberry** [comment]
Please note that the check for https://github.com/CNugteren/CLBlast/issues/50 is more relaxed than the original check, as it requires A to have less bytes than in the original check.

**Comment by CNugteren** [comment]
Yes, that's indeed the case. But nothing else changed, so? But indeed, when you do the math you can see that we decreased the requirement by `ld` and added `one`, so we actually decreased the requirement given that `ld >= one`:
```
   if (ld < one) { return StatusCode::kInvalidLeadDimA; }
   try {
-    auto required_size = (ld*two + offset)*data_size;
+    auto required_size = (ld*(two-1) + one + offset)*data_size;
     auto buffer_size = buffer.GetSize();
     if (buffer_size < required_size) { return StatusCode::kInsufficientMemoryA; }
```

**Comment by blueberry** [comment]
But, shouldn't ld  always be equals or greater than one by definition? id ld<one, such matrix is broken?

**Comment by CNugteren** [comment]
Indeed, that's what `if (ld < one) { return StatusCode::kInvalidLeadDimA; }` is for. I am not disagreeing with you, I am just pointing out the only change that is related to throwing error -1011 (`kInsufficientMemoryA`).

@psyhtest No error -1011 in the included CLBlast tests, right? Just in your own tests?

**Comment by psyhtest** [comment]
@CNugteren Yes, only in Caffe tests.

Here's what a bit of old good printf magic:
```
     auto buffer_size = buffer.GetSize();
+#if 1
+#include <stdio.h>
+    printf("ld          == %d\n", ld);
+    printf("one         == %d\n", one);
+    printf("two         == %d\n", two);
+    printf("offset      == %d\n", offset);
+    printf("data_size   == %d\n", data_size);
+    printf("buffer_size == %d\n", buffer_size);
+    printf("{ required_size = (ld*two + offset)*data_size; } ==  %d\n", (ld*two + offset)*data_size);
+    printf("{ required_size = (ld*(two-1) + one + offset)*data_size; } == %d\n", (ld*(two-1) + one + offset)*data_size);
+#endif
```
tells me.

When using the development branch:
```
$ LD_LIBRARY_PATH=/data/install/lib-clblast-dvdt/lib:/data/install/lib-openblas-v0.2.18/lib:$LD_LIBRARY_PATH \
/data/caffe-dvdt-clblast#55/build/test/test_all.testbin \
--gtest_filter=NetTest/3.TestBackwardWithAccuracyLayer

Setting to use device 0
Note: Google Test filter = NetTest/3.TestBackwardWithAccuracyLayer
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from NetTest/3, where TypeParam = caffe::GPUDevice<double>
[ RUN      ] NetTest/3.TestBackwardWithAccuracyLayer
ld          == 24
one         == 5
two         == 24
offset      == 0
data_size   == 8
buffer_size == 960
{ required_size = (ld*two + offset)*data_size; } ==  4608
{ required_size = (ld*(two-1) + one + offset)*data_size; } == 4456
```

When using the 0.6.0 release:
```
LD_LIBRARY_PATH=/data/install/lib-clblast-0.6.0/lib:/data/install/lib-openblas-v0.2.18/lib:$LD_LIBRARY_PATH \
/data/caffe-dvdt-clblast#55/build/test/test_all.testbin \
--gtest_filter=NetTest/3.TestBackwardWithAccuracyLayer

Setting to use device 0
Note: Google Test filter = NetTest/3.TestBackwardWithAccuracyLayer
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from NetTest/3, where TypeParam = caffe::GPUDevice<double>
[ RUN      ] NetTest/3.TestBackwardWithAccuracyLayer
ld          == 24
one         == 24
two         == 5
offset      == 0
data_size   == 8
buffer_size == 960
{ required_size = (ld*two + offset)*data_size; } ==  960
{ required_size = (ld*(two-1) + one + offset)*data_size; } == 960
```

**Comment by blueberry** [comment]
one and two get swapped somewhere. Maybe there were some changes in the order of parameters between 0.6.0 and development in the meantime?

**Comment by psyhtest** [comment]
> But indeed, when you do the math you can see that we decreased the requirement by `ld` and added `one`, so we actually decreased the requirement given that `ld >= one`

I must admit I am confused. Given this, the new `required_size` is no greater than (` <=`) the old `required_size`. (They are exactly equal when `ld == one`.)

Before doing the `printf`s, I thought this was the problem: assuming `buffer_size` did not change, a decrease in `required_size` could stop the test working.

**Comment by blueberry** [comment]
@psyhtest but, as you can see from the println  output, the problem is that one and two were switched somewhere before that.

**Comment by psyhtest** [comment]
@blueberry Yeah, that's indeed what causes the failure here. But had not they been switched before this function and `ld` was  greater than `one` (e.g. 25 > 24), I would have expected to see the following output:
```
ld          == 25
one         == 24
two         == 5
offset      == 0
data_size   == 8
buffer_size == 960 ??
{ required_size = (ld*two + offset)*data_size; } == 1000
{ required_size = (ld*(two-1) + one + offset)*data_size; } == 992
```
But I guess `buffer_size` would have also increased then to 1000, so my assumption was incorrect and hence my worry unfounded :).

I think this all proves that the change for #50 has nothing to do with this issue.

**Comment by CNugteren** [comment]
Since the CLBlast tests still work fine, I guess we should look for the issue in how you are calling the GEMM routine. Are you using the C or C++ interface? Perhaps you are not using the enum's themselves, but rather the raw integer values?

One thing that did change in the `development` branch is the mapping of enum values to integers in commit `3555cd043654ec24ff325bd6205281af790e50d2`. See the top of `clblast.h` for the new values. This could explain the problem, because transposing (or not) and col/row-major would swap the values for `one` and `two`: they don't correspond 1-to-1 to values of `m`, `n`, and `k`.

**Comment by psyhtest** [comment]
D'oh. I was using the `enum`'s but I wasn't rebuilding the Caffe library to test with the development version of CLBlast. Therefore, Caffe used the integer values it got from the 0.6.0 version of the header, and then passed them to the development version of CLBlast. I'm testing this now but I'm pretty sure that's it.

**Comment by CNugteren** [comment]
@psyhtest I believe this issue is solved, right? Let me know if this is not the case, we'll re-open it.
