### ISSUE TITLE
Press a key to 'abort' and 'continue' to next in tuning

### ISSUE THREAD

**Issue by diverger** [CNugteren/CLBlast#555]
Hi,

I always frustrated that the tuning never completed on my platform. I know there must be some methods to make it done, by some coding work. Is it possible to add a mechanism to let the user to abort the current test and continue to next one? Then the tuning can jump the invalid configurations and won't stuck there forever. 

Thanks.

**Comment by CNugteren** [comment]
I don't think this is easily possible. I guess what you are looking for is a separate process or something that keeps a counter and than after X seconds (or user input) kills the GPU execution in such a way that the main program can still continue? Sounds too complicated to me - better to fix the issue in either the GPU driver or CLBlast tuning itself I would say.
