### ISSUE TITLE
Windows binaries of PHP extensions

### ISSUE THREAD

**Issue by GajowyJ** [CNugteren/CLBlast#564]
Hi!
I'm using opencl, openblas and clblast tools with success to speed up my scientific calculation on matrices in PHP 8.1. Now I want to migrate to version 8.3 (VS16 x64 Thread Safe). I'm using Windows10 (64-bit).
I need following files compatible with PHP 8.3:
php_rindow_clblast.dll
php_rindow_openblas.dll
php_rindow_opencl.dll

Could you please advice, where the files can be found (if any binary exists)?

**Comment by CNugteren** [comment]
There is no relation between CLBlast and PHP, so those files do not exist. You can use the regular `clblast.dll`.
