### ISSUE TITLE
How to cite clblast?

### ISSUE THREAD

**Issue by hughperkins** [CNugteren/CLBlast#62]
Hi,

Writing a paper on cltorch, which I'll just put on arxiv most likely.  Question: how to cite clblast?

**Comment by hughperkins** [comment]
PS Wow, you have a lot of publicatoins http://www.cedricnugteren.nl/publications.php

**Comment by hughperkins** [comment]
(Aside from citing clblast itself, Is it fair to say that clblast is also using cltune, http://www.cedricnugteren.nl/downloads/Nugteren2015a.pdf ? )

**Comment by CNugteren** [comment]
Indeed, at this point there is no scientific publication related to CLBlast. Perhaps you can just use `https://github.com/CNugteren/CLBlast` instead for now?

And yes, it is using CLTune, so you can also cite the paper you link to:

> Cedric Nugteren and Valeriu Codreanu. CLTune: A Generic Auto-Tuner for OpenCL Kernels. In: MCSoC: 9th International Symposium on Embedded Multicore/Many-core Systems-on-Chip. IEEE, 2015.

**Comment by hughperkins** [comment]
Cool.  Thanks! :-)
