### ISSUE TITLE
Missing add_test() in CMakeLists.txt

### ISSUE THREAD

**Issue by OursDesCavernes** [CNugteren/CLBlast#63]
Hello,

I'm writing a Gentoo package for CLBlast:
[sci-libs/clblast](https://github.com/OursDesCavernes/cavernlay/tree/master/sci-libs/clblast)

The Gentoo package manager (Portage) can perform unit tests automatically after build and before installation if they are declared properly in CMakeLists.txt.

You have done this for CLTune using add_test().

I'll create a pull request if I get this working.

**Comment by CNugteren** [comment]
You are right, that is missing, `make test` also doesn't work. I fixed this in the latest version of the `development` branch.

Actually, it will then run all tests (although not with `-full-test` option), so this might take quite a bit of time. I am not sure if this is what you want. Also, I don't think my tests report back in the way CMake expects, so I am not sure if actual wrong results will be spotted - but crashes will be. I'll have to investigate this in more detail, perhaps I can also make some kind of 'smoke' test instead?

**Comment by CNugteren** [comment]
I have just updated the test binaries to output a return value (0: success, 1: failure) based on the number of errors encountered, allowing it to work with CMake/CTest and thus with `make test`. I'll also look into creating a smoke test to reduce testing time.

**Comment by OursDesCavernes** [comment]
Full test by default is fine. We only enable tests when qualifying a new environment or a new version, not for an everyday stable build.

**Comment by CNugteren** [comment]
OK! Then I'll close this issue: the CTest integration is now done properly.
