### ISSUE TITLE
Provide (128m+1) graph in eps format?

### ISSUE THREAD

**Issue by hughperkins** [CNugteren/CLBlast#64]
Hi Cedric,

Dont suppose... possible to provide the graph of (128m+1) (for integer m) from https://github.com/CNugteren/CLBlast/blob/master/doc/performance/Radeon_HD7950/SGEMM.pdf  in eps format?

**Comment by hughperkins** [comment]
(or the results file used to generate it, would be better actually, and probably easier for you?)

**Comment by CNugteren** [comment]
I don't have access to the HD7950 machine right now, so I cannot reproduce the graph. But since the PDF is vector graphics anyway it should be possible to convert & crop it the way you want? See for example: http://tex.stackexchange.com/questions/20883/how-to-convert-pdf-to-eps

**Comment by hughperkins** [comment]
Hmmm, I'm really lazy, and just zoomed, and took a screenshot, for now :-D
