### ISSUE TITLE
When run clblast in arm(android), I got a error. 

### ISSUE THREAD

**Issue by zazd** [CNugteren/CLBlast#68]
I can run clblast in PC(linux), but the same code in arm(android), it failed. I cross compile clblast and push it to android. However, When the program run in gemm in clblast.cc
in about clblast.cc 1495:  auto queue_cpp = Queue(*queue); 
it failed.  But when I print the value of queue:0xb79ee300, it seems that the cl_command_queue* queue is not a nullptr.

so, would you help me to find the reason?

Thank you!

**Comment by CNugteren** [comment]
Are you able to run any other OpenCL programs successfully on your Android device in the same way? What device are you using? And which OpenCL libraries? And are you testing one of the included sample programs, one of the tests, or ...?

**Comment by zazd** [comment]
I use rk3288 with gpu mali764. The test program opencl-Z can be run in the device. I am also do some simple tests like addition and multiplication using opencl, and it can run.  The opencl library is provided by Mali in rk3288 name libGLES_mali.so.

**Comment by CNugteren** [comment]
OK, thanks for the info. And what program fails, the included tests? Can you give me the output of `make test` (note: first configure the tests, see README)

**Comment by zazd** [comment]
Sorry, I am run the program in android, so it is trouble to run the test in android. So I just write some code  using the api your provide, such as gemm, gemv....  However, the program in linux can use the gemm and other function in api. But the same codes in android, it failed. For example, in api gemm(), the android can not use it, and I find the program to be Interruptions in the line : auto queue_cpp = Queue(queue) in the function gemm() and other functions which have the same line.

**Comment by zazd** [comment]
I will get a development board of rk3288 after a while, at that time, I will run the tests.

**Comment by CNugteren** [comment]
OK, I understand that it might be tricky to run the included tests on Android. But perhaps you can copy paste the code of one of the included samples and call that function from within your Android app? That way we can make sure that the issue is with CLBlast. Because now it could also be that your OpenCL queue passed to CLBlast is not valid for example?

**Comment by zazd** [comment]
Sorry for replying so late. Your suggestion is good for me. However I have no time to do it now. I will test it when I have free time. At that time, I will show you the information. Thank you.

**Comment by zazd** [comment]
It seems that I make some error of the cross compile of CLBlast. When I cross compile of CLBlast successfully, the problem disappeared.
