### ISSUE TITLE
Severe SGEMM performance regression 0.7.1 -> 0.8.x/master

### ISSUE THREAD

**Issue by gcp** [CNugteren/CLBlast#73]
I'm seeing my entire application drop about 45% in performance when updating from 0.7.1 to the master branch. It's doing more than just sgemm, so the sgemm regression itself must be disastrous. This is on a R9 390.

On an Intel HD 530, the difference is even more than 50%.

Typical SGEMM kernel configurations:

M = 96
N = 361
K = 550

M = 128
N = 361
K = 1152

M = 128
N = 361
K = 864

**Comment by CNugteren** [comment]
Both devices you mentioned are not in the list of pre-tuned devices, so it will use the default for AMD/GPU and Intel/GPU respectively. These defaults can change as new tuner data is added for other devices, possibly causing performance degradation.

I suggest to first tune CLBlast for these devices. Also, the numbers you are mentioning are relative. Perhaps the 0.7.1 performance was horrible as well. Do you have any GFLOPS numbers?

I see that in an other issue you mention that you can't link the tuners on Windows, so I'll look into that issue first.

**Comment by gcp** [comment]
The R9 390 is a Hawaii, which has tuning. I'll check if the code correctly detects that these devices match up.

I added clBLAS support yesterday, and the entire program becomes twice as fast even compared to 0.7.1, so clearly there's still room for improvement even there.

**Comment by gcp** [comment]
At least the code in master correctly detects the device as a Hawii, and I verified that Hawaii parameters (at least for Xgemm) haven't changed.

**Comment by blueberry** [comment]
@gcp When I was tuning hawaii, I got a pretty high speed; if it became twice as fast, it would put it above the theoretical limits of the hardware (if I remember well, I got more than 3.5 TFLOPS from a 5.4 TFLOPS R9 290X)

Maybe you should try to re-tune it yourself and see whether something improves.

**Comment by gcp** [comment]
Thanks, that's useful info. I'm not sure the tuning is at fault, as described above the parameters are picked up correctly and haven't changed between versions.

I can reproduce the slowdown with sgemm.cpp:

  const size_t m = 128;
  const size_t n = 361;
  const size_t k = 1152;

1000 iterations of the sgemm call take 1000 ms on 0.7.1, but 1300ms on master, so a 30% regression. Some other sizes must be even worse to explain the app slowdown.

Given that I can now compare to clBLAS, I'll do consecutive calls of both kernels in my app and see exactly which cases have big differences.

**Comment by gcp** [comment]
Testing harness: https://pastebin.mozilla.org/8880977

Note that
- clBLAS goes first, so caching is in the benefit of clBlast
- Results are reported if clBlast is less than half the speed of clBLAS

Results:
https://pastebin.mozilla.org/8880978

At a guess, clBlast is losing heavily on setup overhead here.

**Comment by CNugteren** [comment]
As blueberry says, it can still be due to sub-optimal tuning values. Although it is tuned for Hawaii, it might be that not all Hawaii devices behave the same. But I don't hope that's the case.

Could you perhaps run the included SGEMM client? See the README under performance testing to see how to compile it. It can (if installed) automatically test against clBLAS as well. If you could reproduce your tests and results there? That way we'll also have GFLOPS numbers next to the execution times.

**Comment by gcp** [comment]
1) If it correctly picks the Hawaii parameters, and they haven't changed, then I don't see how tuning can explain the regression part.

I tried to some to get the tuners to link under Windows, but no luck, and I don't really understand why it's failing.

2) Compiling the client worked. Result for xgemm:

$ ./clblast_client_xgemm.exe -device 0

* Options given/available:
    -m 512 [=default]
    -n 512 [=default]
    -k 512 [=default]
    -layout 101 (row-major) [=default]
    -transA 111 (regular) [=default]
    -transB 111 (regular) [=default]
    -lda 512 [=default]
    -ldb 512 [=default]
    -ldc 512 [=default]
    -offa 0 [=default]
    -offb 0 [=default]
    -offc 0 [=default]
    -alpha 2.000000 [=default]
    -beta 2.000000 [=default]
    -platform 0 [=default]
    -device 0 [=default]
    -precision 32 (single) [=default]
    -clblas 1 [=default]
    -step 1 [=default]
    -num_steps 0 [=default]
    -runs 10 [=default]
    -h [false]
    -q [false]
    -no_abbrv [false]

                                                                                                                                             | <--       CLBlast       --> | <--       clBLAS        --> |
        m;        n;        k;   layout;   transA;   transB;      lda;      ldb;      ldc;     offa;     offb;     offc;    alpha;     beta;     ms_1; GFLOPS_1;    GBs_1;     ms_2; GFLOPS_2;    GBs_2
      512;      512;      512;      101;      111;      111;      512;      512;      512;        0;        0;        0; 2.000000; 2.000000;     4.41;     60.9;      1.0;     0.19;   1386.9;     21.7


60 GFLOPS vs 1400 GFLOPS.

The results becomes more reasonable for bigger sizes, but still suck:

        m;        n;        k;   layout;   transA;   transB;      lda;      ldb;      ldc;     offa;     offb;     offc;    alpha;     beta;     ms_1; GFLOPS_1;    GBs_1;     ms_2; GFLOPS_2;    GBs_2
       1K;       1K;       1K;      101;      111;      111;       1K;       1K;       1K;        0;        0;        0; 2.000000; 2.000000;     5.17;    415.3;      3.2;     1.16;   1855.7;     14.5

**Comment by CNugteren** [comment]
> 1) If it correctly picks the Hawaii parameters, and they haven't changed, then I don't see how tuning can explain the regression part.

Indeed, that doesn't explain the performance difference between the different versions. But what I meant was that those parameters might be sub-optimal anyway. But let's not look into that yet.

> I tried to get the tuners to link under Windows, but no luck, and I don't really understand why it's failing.

I think the issue might be that Visual Studio requires you to export symbols explicitly from a DLL. The tuners use some common helper functions from CLBlast, but they are (obviously) not explicitly exposed in the DLL to the user. I've fixed this in the latest version of the development branch, the tuners should now link properly on MSVC.

> 2) Compiling the client worked. Result for xgemm:

Thanks for running the included client. That way I know the tests are done fair - in any case in the same way as I normally test for performance with CLBlast. The formatting in your post is a big lost though, but I see indeed that it is significantly slower for various sizes. This is with the latest version? How are these numbers with 0.7.1, do they then match the clBLAS reference?

I don't have access to a Hawaii device myself at the point unfortunately. I suggest for now that you - if you can - run the tuners on your device and see what kind of numbers they report. Perhaps the GEMM kernel itself is fast but the supporting transpose kernels are slow? Or perhaps this device is significantly different from the other Hawaii device - but that would be bad news.

**Comment by blueberry** [comment]
I have just tried the 0.8.0 version, and the performance for the 8192x8192 kernel is the same as before on my Hawaii (R9 290X).

**Comment by gcp** [comment]
@blueberry what platform and drivers are you using? I guess there might be a difference between the radeon or amdgpu stack with clover/libclc (instead of AMD-Pro) and the AMD proprietary Windows driver.

I can't test >1k with the 32-bit exe, but can you check the performance for smaller kernels like 1k (the default?)?

**Comment by blueberry** [comment]
I am using Arch linux 64bit with the proprietary Catalyst drivers.

I am using CLBlast from Clojure, not even directly from C. 1024x1024 takes 1.42 ms (I don't have earlier numbers). 8192x8192 takes 293 ms.

**Comment by blueberry** [comment]
@gcp When measuring, also make sure to call the routine before measuring, because CLBlast does the compilation during the first call and later caches the kerenels.

**Comment by gcp** [comment]
Yeah, I took that into account, the benches I did (aside from the built-in client) were after many warmup runs.

**Comment by gcp** [comment]
That warmup might be an issue with the built-in client, though:

'''
$ ./clblast_client_xgemm.exe -m 1024 -n 1024 -k 1024 -platform 0 -device 0

* Options given/available:
    -m 1024
    -n 1024
    -k 1024
    -layout 101 (row-major) [=default]
    -transA 111 (regular) [=default]
    -transB 111 (regular) [=default]
    -lda 1024 [=default]
    -ldb 1024 [=default]
    -ldc 1024 [=default]
    -offa 0 [=default]
    -offb 0 [=default]
    -offc 0 [=default]
    -alpha 2.000000 [=default]
    -beta 2.000000 [=default]
    -platform 0 [=default]
    -device 0 [=default]
    -precision 32 (single) [=default]
    -clblas 1 [=default]
    -step 1 [=default]
    -num_steps 0 [=default]
    -runs 10 [=default]
    -h [false]
    -q [false]
    -no_abbrv [false]

                                                                                                                                             | <--       CLBlast       --> | <--       clBLAS        --> |
        m;        n;        k;   layout;   transA;   transB;      lda;      ldb;      ldc;     offa;     offb;     offc;    alpha;     beta;     ms_1; GFLOPS_1;    GBs_1;     ms_2; GFLOPS_2;    GBs_2
       1K;       1K;       1K;      101;      111;      111;       1K;       1K;       1K;        0;        0;        0; 2.000000; 2.000000;     5.48;    391.7;      3.1;     1.38;   1560.8;     12.2
'''

'''
$ ./clblast_client_xgemm.exe -m 1024 -n 1024 -k 1024 -platform 0 -device 0 -runs 1000

* Options given/available:
    -m 1024
    -n 1024
    -k 1024
    -layout 101 (row-major) [=default]
    -transA 111 (regular) [=default]
    -transB 111 (regular) [=default]
    -lda 1024 [=default]
    -ldb 1024 [=default]
    -ldc 1024 [=default]
    -offa 0 [=default]
    -offb 0 [=default]
    -offc 0 [=default]
    -alpha 2.000000 [=default]
    -beta 2.000000 [=default]
    -platform 0 [=default]
    -device 0 [=default]
    -precision 32 (single) [=default]
    -clblas 1 [=default]
    -step 1 [=default]
    -num_steps 0 [=default]
    -runs 1000
    -h [false]
    -q [false]
    -no_abbrv [false]

                                                                                                                                             | <--       CLBlast       --> | <--       clBLAS        --> |
        m;        n;        k;   layout;   transA;   transB;      lda;      ldb;      ldc;     offa;     offb;     offc;    alpha;     beta;     ms_1; GFLOPS_1;    GBs_1;     ms_2; GFLOPS_2;    GBs_2
       1K;       1K;       1K;      101;      111;      111;       1K;       1K;       1K;        0;        0;        0; 2.000000; 2.000000;     1.33;   1617.9;     12.6;     1.03;   2083.3;     16.3
'''

At least for this size, performance is comparable to clBLAS and comparable to your numbers.

**Comment by gcp** [comment]
For the somewhat less convenient sizes I'm using, clBLAS is 3-4x as fast:

```
$ ./clblast_client_xgemm.exe -m 128 -n 361 -k 1152 -platform 0 -device 0 -runs 5000

* Options given/available:
    -m 128
    -n 361
    -k 1152
    -layout 101 (row-major) [=default]
    -transA 111 (regular) [=default]
    -transB 111 (regular) [=default]
    -lda 1152 [=default]
    -ldb 361 [=default]
    -ldc 361 [=default]
    -offa 0 [=default]
    -offb 0 [=default]
    -offc 0 [=default]
    -alpha 2.000000 [=default]
    -beta 2.000000 [=default]
    -platform 0 [=default]
    -device 0 [=default]
    -precision 32 (single) [=default]
    -clblas 1 [=default]
    -step 1 [=default]
    -num_steps 0 [=default]
    -runs 5000
    -h [false]
    -q [false]
    -no_abbrv [false]

                                                                                                                                             | <--       CLBlast       --> | <--       clBLAS        --> |
        m;        n;        k;   layout;   transA;   transB;      lda;      ldb;      ldc;     offa;     offb;     offc;    alpha;     beta;     ms_1; GFLOPS_1;    GBs_1;     ms_2; GFLOPS_2;    GBs_2
      128;      361;     1152;      101;      111;      111;     1152;      361;      361;        0;        0;        0; 2.000000; 2.000000;     0.86;    124.4;      3.1;     0.27;    388.6;      9.6
```

**Comment by gcp** [comment]
After tuning (and a manual fixup, because the database script lost the "const Database::DatabaseEntry Database::XgemmHalf" entry):

```
$ ./clblast_client_xgemm.exe -m 1024 -n 1024 -k 1024 -platform 0 -device 0 -runs 1000

* Options given/available:
    -m 1024
    -n 1024
    -k 1024
    -layout 101 (row-major) [=default]
    -transA 111 (regular) [=default]
    -transB 111 (regular) [=default]
    -lda 1024 [=default]
    -ldb 1024 [=default]
    -ldc 1024 [=default]
    -offa 0 [=default]
    -offb 0 [=default]
    -offc 0 [=default]
    -alpha 2.000000 [=default]
    -beta 2.000000 [=default]
    -platform 0 [=default]
    -device 0 [=default]
    -precision 32 (single) [=default]
    -clblas 1 [=default]
    -step 1 [=default]
    -num_steps 0 [=default]
    -runs 1000
    -h [false]
    -q [false]
    -no_abbrv [false]

                                                                                                                                             | <--       CLBlast       --> | <--       clBLAS        --> |
        m;        n;        k;   layout;   transA;   transB;      lda;      ldb;      ldc;     offa;     offb;     offc;    alpha;     beta;     ms_1; GFLOPS_1;    GBs_1;     ms_2; GFLOPS_2;    GBs_2
       1K;       1K;       1K;      101;      111;      111;       1K;       1K;       1K;        0;        0;        0; 2.000000; 2.000000;     1.12;   1917.7;     15.0;     1.08;   1993.6;     15.6
```

```
$ ./clblast_client_xgemm.exe -m 128 -n 361 -k 1152 -platform 0 -device 0 -runs 1000

* Options given/available:
    -m 128
    -n 361
    -k 1152
    -layout 101 (row-major) [=default]
    -transA 111 (regular) [=default]
    -transB 111 (regular) [=default]
    -lda 1152 [=default]
    -ldb 361 [=default]
    -ldc 361 [=default]
    -offa 0 [=default]
    -offb 0 [=default]
    -offc 0 [=default]
    -alpha 2.000000 [=default]
    -beta 2.000000 [=default]
    -platform 0 [=default]
    -device 0 [=default]
    -precision 32 (single) [=default]
    -clblas 1 [=default]
    -step 1 [=default]
    -num_steps 0 [=default]
    -runs 1000
    -h [false]
    -q [false]
    -no_abbrv [false]

                                                                                                                                             | <--       CLBlast       --> | <--       clBLAS        --> |
        m;        n;        k;   layout;   transA;   transB;      lda;      ldb;      ldc;     offa;     offb;     offc;    alpha;     beta;     ms_1; GFLOPS_1;    GBs_1;     ms_2; GFLOPS_2;    GBs_2
      128;      361;     1152;      101;      111;      111;     1152;      361;      361;        0;        0;        0; 2.000000; 2.000000;     0.97;    109.5;      2.7;     0.27;    390.9;      9.6
```

I'll try backup up the 0.7.1 now, but from the looks of it, the problem is the non-square, non-power of 2 size of the matrix, where clBLAS generates a much better kernel.

Fwiw, running the tuner with this custom size fails with an L2 norm error.

**Comment by CNugteren** [comment]
Thanks for all the testing and info! Below are some remarks.

> and a manual fixup, because the database script lost the "const Database::DatabaseEntry Database::XgemmHalf" entry

Yeah, sorry, that's still an issue with the database right now, there are simply no results yet for 16-bit GEMM.

> That warmup might be an issue with the built-in client, though

Well, is that an 'issue'? It is a fair measurement this way, right? If you indeed want to neglect the compilation then you can run 100 runs or so. Anyway, for a decent compiler and a significant matrix size this compilation time shouldn't be too much of an issue I guess? Perhaps I can add an option to the client to enable/disable a warm-up.

> Fwiw, running the tuner with this custom size fails with an L2 norm error.

Yeah, it might be that the GEMM tuner requires some specific input dimensions. I'll check that on my system later.

> I'll try backing up to 0.7.1 now, but from the looks of it, the problem is the non-square, non-power of 2 size of the matrix, where clBLAS generates a much better kernel.

Did you do all the tuners, or just the GEMM tuners? Because I have a feeling that it might be the pre and post-processing kernels that limit your performance. I saw some issues with some of the transpose kernels on AMD hardware before. Even if they are tuned they might be very slow.

I'll add a sort of debug/verbose mode to CLBlast which will tell you which kernel is running and how long each of them took. Then we can see easily where the problem lies. Another way to test this is to go for column-major instead or play with the transpose options of the input matrices. There are 8 combinations in total, some will run no or different pre and post processing kernels. Although I think with these irregular sizes it still requires some form of pre and post processing.

**Comment by gcp** [comment]
>Well, is that an 'issue'? It is a fair measurement this way, right?

Yes, but the GFLOPS numbers I posted ended up being influenced by the OpenCL compilation time, which was not the idea :-)

>Did you do all the tuners, or just the GEMM tuners?

I ran all of them.

>I saw some issues with some of the transpose kernels on AMD hardware before. Even if they are tuned they might be very slow.

I will check with XCode tonight, but this is the NVIDIA GTX 750, which also shows a factor 2 loss:
```
./clblast_client_xgemm -m 128 -n 361 -k 1152 -runs 2000

* Options given/available:
    -m 128 
    -n 361 
    -k 1152 
    -layout 101 (row-major) [=default]
    -transA 111 (regular) [=default]
    -transB 111 (regular) [=default]
    -lda 1152 [=default]
    -ldb 361 [=default]
    -ldc 361 [=default]
    -offa 0 [=default]
    -offb 0 [=default]
    -offc 0 [=default]
    -alpha 2.000000 [=default]
    -beta 2.000000 [=default]
    -platform 0 [=default]
    -device 0 [=default]
    -precision 32 (single) [=default]
    -clblas 1 [=default]
    -cblas 1 [=default]
    -step 1 [=default]
    -num_steps 0 [=default]
    -runs 2000 
    -h [false]
    -q [false]
    -no_abbrv [false]

                                                                                                                                             | <--       CLBlast       --> | <--       clBLAS        --> | <--      CPU BLAS       --> |
        m;        n;        k;   layout;   transA;   transB;      lda;      ldb;      ldc;     offa;     offb;     offc;    alpha;     beta;     ms_1; GFLOPS_1;    GBs_1;     ms_2; GFLOPS_2;    GBs_2;     ms_3; GFLOPS_3;    GBs_3
      128;      361;     1152;      101;      111;      111;     1152;      361;      361;        0;        0;        0; 2.000000; 2.000000;     1.16;     91.9;      2.3;     0.57;    186.6;      4.6;     2.69;     39.6;      1.0
```

Granted, I can find sizes for which clBLAS completely tanks, too:
-m 128 -n 361 -k 550 

Overall, clBLAS seems to handle small matrices a lot better. Try square ones like m,n,k=512,256,128

**Comment by blueberry** [comment]
The small matrices issue might be due to doing more than one position in one work item. It is a good idea for big matrix sizes, but when the matrix is small, then most of the items are idling while a few of them compute 4, 8, 16 entries each.

The best solution would be to use different settings for different matrix sizes, but I am not sure how difficult that would be to do in the present architecture.

**Comment by CNugteren** [comment]
Especially for small matrices (`m` and `n`) and on AMD hardware there is room for improvements. Theoretically we could just tune for smaller sizes and hopefully that will fix it. However, then large sizes might be slow. And what about rectangular sizes? Or large values of `k`? Indeed, as blueberry remarks this is not easy to integrate in the current tuning architecture, this is still something on the long-term to-do list. I'll elaborate on this a bit more later.

For now I added two of the features I promised above: an option to the client (`-warm_up` on command-line) to do a first non-timed warm-up run, and a verbose mode (`-DVERBOSE=ON` to CMake) to retrieve some additional performance debugging information from the library.

Here is an example run with both features enabled:

```
./clblast_client_xgemm -device 2 -runs 1 -warm_up
        m;        n;        k;   layout;   transA;   transB;      lda;      ldb;      ldc;     offa;     offb;     offc;    alpha;     beta;     ms_1; GFLOPS_1;    GBs_1;     ms_2; GFLOPS_2;    GBs_2;     ms_3; GFLOPS_3;    GBs_3
[DEBUG] Compiling routine 'GEMM-32 (single)' for device 'AMD Radeon R9 M370X Compute Engine'
[DEBUG] Completed compilation in 2.24 ms
[DEBUG] Running kernel 'TransposeMatrixFast'
[DEBUG] Completed kernel in 0.53 ms
[DEBUG] Running kernel 'TransposeMatrixFast'
[DEBUG] Completed kernel in 0.35 ms
[DEBUG] Running kernel 'Xgemm'
[DEBUG] Completed kernel in 2.00 ms
[DEBUG] Running kernel 'TransposeMatrixFast'
[DEBUG] Completed kernel in 0.31 ms
[DEBUG] Running kernel 'TransposeMatrixFast'
[DEBUG] Completed kernel in 0.38 ms
[DEBUG] Running kernel 'TransposeMatrixFast'
[DEBUG] Completed kernel in 0.32 ms
[DEBUG] Running kernel 'Xgemm'
[DEBUG] Completed kernel in 2.01 ms
[DEBUG] Running kernel 'TransposeMatrixFast'
[DEBUG] Completed kernel in 0.58 ms
      512;      512;      512;      101;      111;      111;      512;      512;      512;        0;        0;        0; 2.000000; 2.000000;     5.56;     48.2;      0.8;     1.90;    141.2;      2.2;     4.45;     60.3;      0.9
```

So here you can see indeed on AMD hardware that the compilation is rather slow - but not taken into account anymore in the timing. Still, the timing (5.56ms) is way slower than clBLAS (1.90ms). However, the actual GEMM kernel finishes in 2.01ms, so that's roughly on par. It's the extra pre and post-processing kernels and some other un-timed overhead that causes this effect. For larger sizes this is less noticeable, but it is indeed an issue here like you point out.

Without the transposes it is already much better, but there is still overhead:
```
./clblast_client_xgemm -device 2 -runs 1 -warm_up -layout 102 -transB 112
        m;        n;        k;   layout;   transA;   transB;      lda;      ldb;      ldc;     offa;     offb;     offc;    alpha;     beta;     ms_1; GFLOPS_1;    GBs_1;     ms_2; GFLOPS_2;    GBs_2;     ms_3; GFLOPS_3;    GBs_3
[DEBUG] Compiling routine 'GEMM-32 (single)' for device 'AMD Radeon R9 M370X Compute Engine'
[DEBUG] Completed compilation in 2.41 ms
[DEBUG] Running kernel 'Xgemm'
[DEBUG] Completed kernel in 1.98 ms
[DEBUG] Running kernel 'Xgemm'
[DEBUG] Completed kernel in 2.02 ms
      512;      512;      512;      102;      111;      112;      512;      512;      512;        0;        0;        0; 2.000000; 2.000000;     2.96;     90.6;      1.4;     1.80;    149.4;      2.3;     4.67;     57.5;      0.9
```

I'll look into this further when I have some more time.

**Comment by gcp** [comment]
I can't really bisect the regression I originally filed this bug for, because 0.7.1 segfaults on Linux, and various things only got fixed for Windows in master/development.

I now tried to help myself by changing the default sizes to 512 (instead of 1024), and retuning, to see if the resulting kernels are better for the sizes that are relevant to me.

There's some issues with the database.py script for this. If you have local data, and data in the DB, that looks the same, it won't do anything (I think regenerating with preferring local data would be more correct). 

If worked around that by changing the script to not load the database and concatenate. This worked, but the C++ code it produced contained only a SGEMM tuning for single precision, despite me having run a full tuning (minus last gemv due to CUDA compiler bug). Notably, the pad/transpose kernel tuning was missing.

Rerunning the benchmark with just the GEMM kernel retuned produced identical results, which perhaps confirms that the sgemm itself may not be the issue.

**Comment by CNugteren** [comment]
I just finished some more experiments. Before actually optimising the GEMM kernel for small matrices there seem to be two other sources of overhead (at least on my laptop AMD GPU):

1. The pre and post-processing kernels for copying and transposing. This is especially an issue on devices with low memory bandwidth such as GPUs without dedicated memory. These kernels are needed in case the matrices need to be transposed, but also in case the matrices don't satisfy the requirements that this GEMM kernel: it only works with sizes multiples of one of the tuning parameters (e.g. 16 or 32).
2. Copying of the alpha and beta parameters to the device. This might be the source of the performance regression originally pointed out in this issue, because it was introduced in CLBlast 0.8.0 as part of half-precision support. Before these scalar constants where passed as kernel arguments, but that is not support for `cl_half` half-precision values as far as I understood. That's why they are now passed as arrays of size 1. Although the arrays are minuscule, there is still quite some overhead with the host-device mem-copies apparently. I could of course revert back to the way it was before in case half-precision is not enabled, but that would complicate things slightly - it is much nicer to have one consistent way of passing arguments for all scenarios.

For point 2 I'll investigate how much code changes are needed to get it back to 0.7.x behaviour again for non half-precision. For point 1 I'll investigate creating a special GEMM 'direct' kernel which doesn't need any pre & post processing and is thus more fitted for smaller matrices. What do you think?

**Comment by blueberry** [comment]
Maybe it would be better to pass those scalar argumets as kernel arguments in all cases, and in case of cl_half to use scalar floats and cast them to halfs inside the kernel.

**Comment by CNugteren** [comment]
Yes, perhaps that is a good idea. Can you do the conversion in a cheap way on the GPU? I know that you can do it when loading data, but that's not what we'll do here. In both cases I think the code changes will be quite minor.

Making a separate direct GEMM will take some more time I guess, but it might be worthwhile for small sizes.

**Comment by gcp** [comment]
There's a good speedup from this on my NVIDIA GTX 750, will verify on my Windows machine whether that brings parity with 0.7.1.

clBLAS is still (much) faster for small sizes even on NVIDIA. "Unfortunately" CLBlast is much faster on Intel's, I guess due to the use of vectors, so my choice of libraries is still complicated ;-)

**Comment by gcp** [comment]
>Could you verify if this fixes the performance regression?

For 128,361,1152 (most important size for me) performance increased from ~100 GFLOPS to ~180 GFLOPS. That's a better improvement than the 30% slowdown I observed, so this can be considered fixed.

I'll file a separate issue for performance parity.
