### ISSUE TITLE
clBlast without sudo

### ISSUE THREAD

**Issue by JanAbbing** [CNugteren/CLBlast#78]
Hello,

I am trying to use clBlast on an external PC where I don't have sudo rights. The normal "make build" worked perfectly to 100%. Now I can't do the "sudo make install" because of no sudo rights.

I tried to manipulate the cmake_install.cmake, so that it won't copy the files to /usr/... but instead in a local folder. When I now try to compile the sample for sgemm.c with manuelly linking to the libclblast.so with "-L .../libclblast.so" and with the include path "-I .../include" (the "..." is a placeholder for the original path to each directorys) it can't find the CLBlastSgemm.  

The error message is:

/tmp/tmpxft_000016cb_00000000-16_Test.o: In function `clBlast(float const*, float const*, float*)':
tmpxft_000016cb_00000000-3_Test.cudafe1.cpp:(.text+0x347): undefined reference to `CLBlastSgemm'
collect2: error: ld returned 1 exit status

As you can see it is a linker error which I can't get rid off. Can you help me or isn't it possible to install clBlast without sudo rights?

greetings,

Jan

**Comment by JanAbbing** [comment]
I figured out my mistake myself

**Comment by CNugteren** [comment]
For future reference, you can instruct CMake to install in a folder of your choice in which you do have rights, e.g. as follows:
```
cmake -DCMAKE_INSTALL_PREFIX=/path/to/install/directory ..
```
