### ISSUE TITLE
Compiler segfaults when compiling the clients

### ISSUE THREAD

**Issue by JanAbbing** [CNugteren/CLBlast#79]
Hello,

I want to test the performance for the CLBlastSgemm. For that I cloned the repo and created the build dir. After that I called: "cmake -DCMAKE_INSTALL_PREFIX=path/to//build/ -DCLIENTS=ON .." in the build dir to enable the perfomance tests. When I now want to do make install, I get the following output:

cmake -DCMAKE_INSTALL_PREFIX=/CLBlast/build/ -DCLIENTS=ON ..
-- Could NOT find 'clBLAS.h', install clBLAS or set CLBLAS_ROOT
-- Could NOT find clBLAS library, install it or set CLBLAS_ROOT
-- Could NOT find clBLAS (missing:  CLBLAS_INCLUDE_DIRS CLBLAS_LIBRARIES)
-- Could NOT find 'cblas.h', install a CPU Netlib BLAS or set CBLAS_ROOT
-- Could NOT find a CPU Netlib BLAS library, install it or set CBLAS_ROOT
-- Could NOT find CBLAS (missing:  CBLAS_INCLUDE_DIRS CBLAS_LIBRARIES)
-- Could NOT find clBLAS nor a CPU BLAS, head-to-head performance comparison not supported in the clients
-- Configuring done
-- Generating done
-- Build files have been written to:/CLBlast/build
make install
Scanning dependencies of target clblast
[  1%] Building CXX object CMakeFiles/clblast.dir/src/database/database.cpp.o
[  2%] Building CXX object CMakeFiles/clblast.dir/src/routines/common.cpp.o
[  3%] Building CXX object CMakeFiles/clblast.dir/src/cache.cpp.o
[  4%] Building CXX object CMakeFiles/clblast.dir/src/clblast.cpp.o
[  5%] Building CXX object CMakeFiles/clblast.dir/src/clblast_c.cpp.o
[  6%] Building CXX object CMakeFiles/clblast.dir/src/routine.cpp.o
[  7%] Building CXX object CMakeFiles/clblast.dir/src/utilities.cpp.o
[  8%] Building CXX object CMakeFiles/clblast.dir/src/routines/level1/xswap.cpp.o
[ 10%] Building CXX object CMakeFiles/clblast.dir/src/routines/level1/xscal.cpp.o
[ 11%] Building CXX object CMakeFiles/clblast.dir/src/routines/level1/xcopy.cpp.o
[ 12%] Building CXX object CMakeFiles/clblast.dir/src/routines/level1/xaxpy.cpp.o
[ 13%] Building CXX object CMakeFiles/clblast.dir/src/routines/level1/xdot.cpp.o
[ 14%] Building CXX object CMakeFiles/clblast.dir/src/routines/level1/xdotu.cpp.o
[ 15%] Building CXX object CMakeFiles/clblast.dir/src/routines/level1/xdotc.cpp.o
[ 16%] Building CXX object CMakeFiles/clblast.dir/src/routines/level1/xnrm2.cpp.o
[ 17%] Building CXX object CMakeFiles/clblast.dir/src/routines/level1/xasum.cpp.o
[ 18%] Building CXX object CMakeFiles/clblast.dir/src/routines/level1/xamax.cpp.o
[ 20%] Building CXX object CMakeFiles/clblast.dir/src/routines/level2/xgemv.cpp.o
[ 21%] Building CXX object CMakeFiles/clblast.dir/src/routines/level2/xgbmv.cpp.o
[ 22%] Building CXX object CMakeFiles/clblast.dir/src/routines/level2/xhemv.cpp.o
[ 23%] Building CXX object CMakeFiles/clblast.dir/src/routines/level2/xhbmv.cpp.o
[ 24%] Building CXX object CMakeFiles/clblast.dir/src/routines/level2/xhpmv.cpp.o
[ 25%] Building CXX object CMakeFiles/clblast.dir/src/routines/level2/xsymv.cpp.o
[ 26%] Building CXX object CMakeFiles/clblast.dir/src/routines/level2/xsbmv.cpp.o
[ 27%] Building CXX object CMakeFiles/clblast.dir/src/routines/level2/xspmv.cpp.o
[ 28%] Building CXX object CMakeFiles/clblast.dir/src/routines/level2/xtrmv.cpp.o
[ 30%] Building CXX object CMakeFiles/clblast.dir/src/routines/level2/xtbmv.cpp.o
[ 31%] Building CXX object CMakeFiles/clblast.dir/src/routines/level2/xtpmv.cpp.o
[ 32%] Building CXX object CMakeFiles/clblast.dir/src/routines/level2/xger.cpp.o
[ 33%] Building CXX object CMakeFiles/clblast.dir/src/routines/level2/xgeru.cpp.o
[ 34%] Building CXX object CMakeFiles/clblast.dir/src/routines/level2/xgerc.cpp.o
[ 35%] Building CXX object CMakeFiles/clblast.dir/src/routines/level2/xher.cpp.o
[ 36%] Building CXX object CMakeFiles/clblast.dir/src/routines/level2/xhpr.cpp.o
[ 37%] Building CXX object CMakeFiles/clblast.dir/src/routines/level2/xher2.cpp.o
[ 38%] Building CXX object CMakeFiles/clblast.dir/src/routines/level2/xhpr2.cpp.o
[ 40%] Building CXX object CMakeFiles/clblast.dir/src/routines/level2/xsyr.cpp.o
[ 41%] Building CXX object CMakeFiles/clblast.dir/src/routines/level2/xspr.cpp.o
[ 42%] Building CXX object CMakeFiles/clblast.dir/src/routines/level2/xsyr2.cpp.o
[ 43%] Building CXX object CMakeFiles/clblast.dir/src/routines/level2/xspr2.cpp.o
[ 44%] Building CXX object CMakeFiles/clblast.dir/src/routines/level3/xgemm.cpp.o
[ 45%] Building CXX object CMakeFiles/clblast.dir/src/routines/level3/xsymm.cpp.o
[ 46%] Building CXX object CMakeFiles/clblast.dir/src/routines/level3/xhemm.cpp.o
[ 47%] Building CXX object CMakeFiles/clblast.dir/src/routines/level3/xsyrk.cpp.o
[ 48%] Building CXX object CMakeFiles/clblast.dir/src/routines/level3/xherk.cpp.o
[ 50%] Building CXX object CMakeFiles/clblast.dir/src/routines/level3/xsyr2k.cpp.o
[ 51%] Building CXX object CMakeFiles/clblast.dir/src/routines/level3/xher2k.cpp.o
[ 52%] Building CXX object CMakeFiles/clblast.dir/src/routines/level3/xtrmm.cpp.o
[ 53%] Building CXX object CMakeFiles/clblast.dir/src/routines/levelx/xomatcopy.cpp.o
Linking CXX shared library libclblast.so
[ 53%] Built target clblast
Scanning dependencies of target test_performance_common
[ 54%] Building CXX object CMakeFiles/test_performance_common.dir/test/performance/client.cpp.o
In file included from /CLBlast/test/performance/client.cpp:14:0:
/CLBlast/test/performance/client.hpp: In function ‘void clblast::RunClient(int, char**)’:
/CLBlast/test/performance/client.hpp:104:23: internal compiler error: Segmentation fault
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://gcc.gnu.org/bugs.html> for instructions.
make[2]: *** [CMakeFiles/test_performance_common.dir/test/performance/client.cpp.o] Error 1
make[1]: *** [CMakeFiles/test_performance_common.dir/all] Error 2
make: *** [all] Error 2
`

is there a way to fix this problem? Or is there a way to get the gemm kernel runtime of clBlast without the performance tests of clBlast?

**Comment by CNugteren** [comment]
Your compiler segfaults, so this might be a bug in your compiler. I see you are using GCC, but which version? Could you try to update it? You can also try the latest version of CLBlast by checking out the `development` branch. Perhaps that solves it as well.

Of course you can measure execution time of CLBlast yourself without the performance tests. You could perhaps start from one of the samples and add some timers. Then you'll need to be sure to make a fair measurement, e.g. do one warm-up run first and then average over a couple of runs.

**Comment by JanAbbing** [comment]
I tried it using the GCC 4.7.3 and the GCC 4.9.2 on the master branch and both failed with the same segfault. Using the GCC 4.9.2 on the development branch, the same error accrues.

Is it fair to measure the time using for example the chrono library? I normally use the clGetProfilingInfo funktion of OpenCL. I tried it using the event taht clBlastSgemm gets as an optional parameter but the resulting time is far too less to be possible, I guess after the whole funktion call the event doesn't hold the data of the SGEMM kernel anymore because of other funktions afterwards. 

at the moment my time measuring lokks like this:

`//warmup
	status = CLBlastSgemm(kRowMajor, kNo, kNo,
									   M, N, K,
									   alpha,
									   device_a, 0, a_ld,
									   device_b, 0, b_ld,
									   beta,
									   device_c, 0, c_ld,
									   &queue, &event);


  for (int i=0;i<runs;i++){
	  // Call the SGEMM routine.
	   auto start = std::chrono::system_clock::now();
	  status = CLBlastSgemm(kRowMajor, kNo, kNo,
									   M, N, K,
									   alpha,
									   device_a, 0, a_ld,
									   device_b, 0, b_ld,
									   beta,
									   device_c, 0, c_ld,
									   &queue, &event);

	  // Wait for completion
	  clWaitForEvents(1, &event);
	  auto end = std::chrono::system_clock::now();
	  cl_ulong time_start, time_end;
	  double total_time;

	  clGetEventProfilingInfo(event, CL_PROFILING_COMMAND_START, sizeof(time_start), &time_start, NULL);
	  clGetEventProfilingInfo(event, CL_PROFILING_COMMAND_END, sizeof(time_end), &time_end, NULL);
	  total_time = time_end - time_start;
	  auto elapsed = std::chrono::duration_cast<std::chrono::milliseconds>(end - start);
	  time1 +=total_time;
	  time2 +=elapsed.count();
	  event=NULL;
  }
  time1/=runs;
  time2/=runs;
  printf("\nExecution time in milliseconds after %d runtimes = %f ms(eventprof)\nExecution time in milliseconds after %d runtimes = %f ms\n",runs, (time1 / 1000000.0) ,runs, time2);`

the resulting time for A and B being 2048x2048 matrices is for the chrono measuring 22.23 ms where cuBLAS needs 21.3 ms (on a GTX 480). Is that a realistic result because being that close to cuBLAS contradict the result of [http://www.cedricnugteren.nl/tutorial.php?page=12] where cuBlas is almost twice as fast. Or did you increase the perfomance in clBlast compared to those results?

**Comment by CNugteren** [comment]
The tutorial is a bit older already, so yeah, it could be that performance has increased. I am not sure about that.

But let's try to solve the issue of the compiler segfaulting first, then you can run the included performance tests and see what they report. I have a machine with GCC 4.9.2 as well (Debian 64-bit 4.9.2-10) and couldn't reproduce the issue. It seems to be related with using this function as far as I understand from your error report:
```
template <typename T, typename U>
static StatusCode ReferenceNotAvailable(const Arguments<U> &, Buffers<T> &, Queue &) {
  return StatusCode::kNotImplemented;
}
```

**Comment by JanAbbing** [comment]
The OS Im on is:

LSB Version:    :core-4.0-amd64:core-4.0-ia32:core-4.0-noarch:graphics-4.0-amd64:graphics-
4.0-ia32:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-ia32:printing-4.0-noarch

Distributor ID: CentOS
Description:    CentOS release 5.11 (Final)
Release:        5.11
Codename:       Final

My CPU is ´the following:

processor       : 9
vendor_id       : GenuineIntel
cpu family      : 6
model           : 44
model name      : Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz
stepping        : 2
cpu MHz         : 1600.000
cache size      : 12288 KB
physical id     : 1
siblings        : 6
core id         : 8
cpu cores       : 6
apicid          : 48
fpu             : yes
fpu_exception   : yes
cpuid level     : 11
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm syscall nx pdpe1gb rdtscp lm constant_tsc ida nonstop_tsc arat pni monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr sse4_1 sse4_2 popcnt lahf_lm
bogomips        : 5335.38
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual
power management: [8]


the memory is:

$ cat /proc/meminfo
MemTotal:     98979096 kB
MemFree:      90768876 kB
Buffers:        176112 kB
Cached:         960692 kB
SwapCached:    1149552 kB
Active:        5787028 kB
Inactive:       700868 kB
HighTotal:           0 kB
HighFree:            0 kB
LowTotal:     98979096 kB
LowFree:      90768876 kB
SwapTotal:    102398300 kB
SwapFree:     100659908 kB
Dirty:             836 kB
Writeback:           0 kB
AnonPages:     5329416 kB
Mapped:         386784 kB
Slab:           906380 kB
PageTables:      31980 kB
NFS_Unstable:        0 kB
Bounce:              0 kB
CommitLimit:  151887848 kB
Committed_AS:  7843072 kB
VmallocTotal: 34359738367 kB
VmallocUsed:    559384 kB
VmallocChunk: 34359057135 kB
HugePages_Total:     0
HugePages_Free:      0
HugePages_Rsvd:      0
Hugepagesize:     2048 kB

and there are 4 gtx 480 build in

**Comment by CNugteren** [comment]
OK, so just a normal x86-64 linux system. Can you please post one more time the output of CMake and make using the `development` branch and GCC 4.9.2? So please clean-up your build directory first to get fresh output. Thanks.

**Comment by JanAbbing** [comment]
I can't really explain but now it was 100% secussfull and I can check it. Thanks for the help!

Greetings,
Jan
