### ISSUE TITLE
Adding installable `find_package` file (for dependent projects) and bumping CMake dependency

### ISSUE THREAD

**Issue by intelfx** [CNugteren/CLBlast#85]
Hello,

I'm trying to make it easier to link to CLBlast from dependent projects (say Caffe). The typical way of writing a module script for `find_package()` seems like too much boilerplate for my idealistic mind, so I'm trying to use the "config" mode of find_package (second signature in the doc), that is, the `install(EXPORT ... DESTINATION ...)` command.

(It installs a declarative-like target description file with absolute pathes to the installed files, which may then be searched by the dependent project's CMakeLists.txt and imported to create an "imported target". This is very similar to pkg-config.)

The problem is that exporting targets needs at least CMake version 3.2. Can we bump the requirement from 2.8 to 3.2?

(The current Ubuntu 16.04 LTS has CMake 3.2 in base image and 3.5 in updates.)

**Comment by CNugteren** [comment]
That could be a nice addition indeed. But going to CMake 3.2 from 2.8 is quite a big jump in requirements to be honest. Can we somehow guard the relevant part such that it is only executed if the newest CMake is available?

By the way, can you point me to the docs of this specific feature (and it's dependency on 3.2). Thanks!

**Comment by intelfx** [comment]
As I've just said in the PR, I've misread the documentation three times in a row (`install(EXPORT ...)` vs `export(EXPORT ...)` vs `install(TARGETS ... EXPORT ...)`) and actually there is no change to CMake dependency.

**Comment by CNugteren** [comment]
Thanks again for improving the CMake infrastructure. I've accepted your PR and tested on CMake 3.0 and 3.5, both seem to work fine. I couldn't find a system with 2.8.11 at this moment. All targets build and run on my system, and indeed `CLBlastConfig.cmake` is now installed. Don't know how to test if that has proper contents though, I'll leave that up to you :-)
