### ISSUE TITLE
Compilation stuck with optimization options

### ISSUE THREAD

**Issue by dvasschemacq** [CNugteren/CLBlast#90]
Hi,

just for information, the compilation of the file CMakeFiles/clblast.dir/src/database/database.cpp.o is stuck on armv7hl using 'gcc (SUSE Linux) 4.8.3 20140627'.

GCC tries to compile that file for 15 minutes and then kill itself.

The workaround we have applied is to change the optimization options from '-O3' to '-O0'.
We have tested different GCC (older) but we have still the issue, this issue is not present on x64.

**Comment by CNugteren** [comment]
Most probably GCC is running out of memory and started to swap. How much do you have available? Have you checked usage?

I'll see if I can somehow mark this file to be compiled without optimisations or perhaps simplify it for the compiler.

**Comment by dvasschemacq** [comment]
It is possible, we have only 2GB of RAMM, ... 
We haven't checked the usage yet, as soon as I do the test again I will give you the answer.

**Comment by dvasschemacq** [comment]
Now the compilation works with -O3 since we have made some space available.
