### ISSUE TITLE
Inline function not found with Vivante OpenCL

### ISSUE THREAD

**Issue by dvasschemacq** [CNugteren/CLBlast#91]
When running the test 'clblast_test_xher2k' the system doesn't find the opencl inline defined functions, we have an error:

```
Testing: n=7 k=7 lda=7 ldb=7 ldc=64 offa=0 offb=0 offc=0 [CLBlast]OpenCL compiler error/warning:
(1245:0) : error : function: 'InitAccRegisters' hasn't the corresponding declaration
(1290:0) : error : function: 'MultiplyAccumulate' hasn't the corresponding declaration
(1339:0) : error : function: 'XgemmBody' hasn't the corresponding declaration
(1343:0) : error : function: 'StoreResults' hasn't the corresponding declaration
(1379:0) : error : function: 'XgemmBody' hasn't the corresponding declaration
(1383:0) : error : function: 'StoreResults' hasn't the corresponding declaration
```

We have tried to find where it does come from, but all the functions seem to be present in the openCL file, we have output the OpenCL code that is sent to the OpenCL compiler and those declaration are present, so we don't understand how to deal with it. Is there a way to avoid this issue ?

**Comment by CNugteren** [comment]
I am as puzzled as you are. And this only happens with `xher2k`? Some of the other level 3 routines use the exact same OpenCL sources: SYRK, SYR2K, and HERK, so they should also have the same issue.

And if you print the whole kernel string that is sent to the compiler and then try that in a small separate host program? If that still doesn't work, you can start stripping bits and pieces of the kernel until it compiles - hopefully that gives some more information.

**Comment by dvasschemacq** [comment]
Actually we have the same kind of problems with those ones. Examples for ./clblast_test_xgemm
`-OpenCL compiler error/warning: (553:0) : error : syntax error at '{'
(554:0) : error : syntax error at '{'
(555:0) : error : syntax error at '{'
(556:0) : error : syntax error at '{'
(1501:0) : error : function: 'InitAccRegisters' hasn't the corresponding declaration
(1546:0) : error : function: 'MultiplyAccumulate' hasn't the corresponding declaration
(1674:0) : error : function: 'XgemmBody' hasn't the corresponding declaration
(1678:0) : error : function: 'StoreResults' hasn't the corresponding declaration
`

**Comment by CNugteren** [comment]
OK, so that makes more sense: the other routines use the same GEMM kernel that's causing your issue.

Have you done any more debugging? I would propose to take the kernel string (as you have already printed it out) and write a small test host C++ file that tries to compile it. Then, if it is still fails, go and remove bits of the code until you find what's causing the issue. Perhaps the kernel is too long for your compiler?

**Comment by CNugteren** [comment]
Any update from your side? Is this a Vivante compiler issue or a genuine problem with CLBlast?

**Comment by CNugteren** [comment]
I'll close this due to inactivity. If this is still an issue with the latest CLBlast and is indeed not a bug in the Vivante compiler, please do re-open it.
