### ISSUE TITLE
No XgemmHalf in database on development branch?

### ISSUE THREAD

**Issue by intelfx** [CNugteren/CLBlast#96]
Is there any specific reason why there are [no entries](https://github.com/CNugteren/CLBlast/blob/development/src/database/database.cpp#L40) (not even the default) for half-precision GEMM on the `development` branch?

**Comment by CNugteren** [comment]
Yes, there is. I have only tested half-precision (fp16) on Intel GPUs with Beignet OpenCL. So far, I couldn't make the kernel work properly with Beignet under Linux. Thus, I haven't been able to run the tuners. As a result there are no entries for fp16 GEMM in the database.

I don't have access to other hardware supporting fp16, so I can't say for 100% that it is a Beignet-related issue - it could of course also be a bug in CLBlast. But until I have other fp16 hardware available (or someone else runs the tuners), it isn't tested.

**Comment by intelfx** [comment]
On Mali-T628 (OpenCL r10), the kernel runs, but there are test failures (not all: 85 passed / 278 skipped / 149 failed). Is this what you mean by "not working properly"?

**Comment by intelfx** [comment]
And if I swap the default kernel with the one written by ARM, then the numbers are 87/278/147. Couldn't it be an issue with precision?

**Comment by CNugteren** [comment]
With Beignet I haven't managed to get the tuner working for HGEMM.

I haven't tuned for Mali FP16, that's why the parameters are not included in the database. Feel free to do so and upload the results to #1. After that's done the next step would be to look at correctness.

**Comment by intelfx** [comment]
> Beignet

BTW, how does it support half-precision? Here (HD4600, beignet from git master) it says -2045.

**Comment by CNugteren** [comment]
The following 2 devices at least support `cl_khr_fp16` with the latest Beignet:
- HD Graphics 5500 BroadWell U-Processor GT2
- HD Graphics Skylake ULT GT2
Could very well be that your hardware doesn't support FP16.

**Comment by intelfx** [comment]
Ah, that matches the situation with proprietary drivers. Looks like I'm out of luck.

**Comment by CNugteren** [comment]
I changed the database script such that it now generates a default parameter set based on 32-bit precision (e.g SGEMM) in case there is no entry yet (e.g. HGEMM). This fixes your issue.
